---
permalink: protect-scsql/concept_snapcenter_plug_in_for_microsoft_sql_server_features.html 
sidebar: sidebar 
keywords:  
summary: 'Le plug-in pour SQL Server s"intègre à Microsoft SQL Server sur l"hôte Windows et à la technologie de copie NetApp Snapshot sur le système de stockage. Pour utiliser le plug-in pour SQL Server, utilisez l"interface SnapCenter.' 
---
= Fonctionnalités du plug-in SnapCenter pour Microsoft SQL Server
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Le plug-in pour SQL Server s'intègre à Microsoft SQL Server sur l'hôte Windows et à la technologie de copie NetApp Snapshot sur le système de stockage. Pour utiliser le plug-in pour SQL Server, utilisez l'interface SnapCenter.

Le plug-in pour SQL Server inclut les principales fonctionnalités suivantes :

* *Interface graphique utilisateur unifiée optimisée par SnapCenter*
+
L'interface SnapCenter vous permet de standardiser et d'assurer une cohérence entre les plug-ins et les environnements. L'interface SnapCenter vous permet d'effectuer des sauvegardes et des restaurations cohérentes dans l'ensemble des plug-ins, d'utiliser le reporting centralisé, d'utiliser des vues du tableau de bord en un coup d'œil, de configurer le contrôle d'accès basé sur les rôles et de surveiller les tâches dans tous les plug-ins. SnapCenter propose également une planification et une gestion centralisées des règles pour prendre en charge les opérations de sauvegarde et de clonage.

* *Administration centrale automatisée*
+
Vous pouvez planifier des sauvegardes SQL Server de routine, configurer la conservation des sauvegardes basée sur des règles et configurer des opérations de restauration instantanées et à chaud. Vous pouvez également surveiller de manière proactive votre environnement SQL Server en configurant SnapCenter pour envoyer des alertes par e-mail.

* *Technologie de copie Snapshot NetApp non disruptive*
+
Le plug-in pour SQL Server utilise la technologie de copie NetApp Snapshot et le plug-in NetApp SnapCenter pour Microsoft Windows. Vous pouvez ainsi sauvegarder des bases de données en quelques secondes et les restaurer rapidement sans mettre SQL Server hors ligne. Les copies Snapshot requièrent un espace de stockage minimal.



Outre ces fonctionnalités majeures, le plug-in pour SQL Server offre les avantages suivants :

* Prise en charge des sauvegardes, des restaurations, des clones et des workflows de vérification
* Sécurité prise en charge par le RBAC et délégation centralisée des rôles
* Création de copies instantanées compactes de bases de données de production à des fins de test ou d'extraction de données grâce à la technologie NetApp FlexClone
+
Une licence FlexClone est requise sur le système de stockage hébergeant le clone.

* Vérification automatisée et sans interruption des sauvegardes
* Possibilité d'exécuter plusieurs sauvegardes simultanément sur plusieurs serveurs
* Les applets de commande PowerShell pour créer des scripts pour les opérations de sauvegarde, de vérification, de restauration et de clonage
* Prise en charge des groupes AlwaysOn Availability Groups (AG) dans SQL Server pour accélérer les opérations AG de configuration, de sauvegarde et de restauration
* Base de données en mémoire et extension de pool de mémoire tampon (BPE) dans le cadre de SQL Server 2014
* Prise en charge des sauvegardes des LUN et des disques de machines virtuelles (VMDK)
* Prise en charge des infrastructures physiques et virtualisées
* Prise en charge des protocoles iSCSI, Fibre Channel, FCoE, Raw Device Mapping (RDM) et VMDK sur NFS et VMFS
+

NOTE: Les volumes NAS doivent disposer d'une export policy par défaut dans la machine virtuelle de stockage (SVM).

* Prise en charge de FileStream et de groupes de fichiers dans les bases de données autonomes SQL Server.

