---
permalink: protect-scsql/quick-start-to-prepare-for-snapcenter-plug-in-install-for-sql-server.html 
sidebar: sidebar 
keywords: credentials 
summary: 'Fournit des instructions pour préparer l"installation du serveur SnapCenter et du plug-in SnapCenter pour Microsoft SQL Server.' 
---
= Préparez l'installation du serveur et du plug-in SnapCenter
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Fournit un ensemble condensé d'instructions de préparation pour l'installation du serveur SnapCenter et du plug-in SnapCenter pour Microsoft SQL Server.



== Exigences relatives au domaine et au groupe de travail

SnapCenter Server peut être installé sur des systèmes se trouvant dans un domaine ou dans un groupe de travail.

Si vous utilisez un domaine Active Directory, vous devez utiliser un utilisateur de domaine avec des droits d'administrateur local. L'utilisateur de domaine doit être membre du groupe Administrateur local sur l'hôte Windows.

Si vous utilisez des groupes de travail, vous devez utiliser un compte local disposant des droits d'administrateur local.



== Conditions de licence

Le type de licence que vous installez dépend de votre environnement.

[cols="1,3"]
|===
| Licence | Si nécessaire 


 a| 
Contrôleur SnapCenter standard
 a| 
Requis pour les contrôleurs de stockage FAS ou AFF

La licence SnapCenter Standard est basée sur le contrôleur et incluse dans le bundle Premium. Si vous disposez de la licence SnapManager Suite, vous bénéficiez également des droits de licence SnapCenter Standard. Si vous souhaitez installer SnapCenter sous forme d'essai avec les systèmes de stockage FAS ou AFF, vous pouvez obtenir une licence d'évaluation Premium Bundle en contactant l'ingénieur commercial.



 a| 
SnapMirror ou SnapVault
 a| 
ONTAP

Une licence SnapMirror ou SnapVault est requise si la réplication est activée dans SnapCenter.



 a| 
Licences supplémentaires (en option)
 a| 
Voir link:../install/concept_snapcenter_licenses.html["Licences SnapCenter"^].



 a| 
Licences SnapCenter Standard (en option)
 a| 
Destinations secondaires


NOTE: Il est recommandé, mais pas obligatoire, d'ajouter des licences SnapCenter Standard aux destinations secondaires. Si les licences SnapCenter Standard ne sont pas activées sur les destinations secondaires, vous ne pouvez pas utiliser SnapCenter pour sauvegarder les ressources sur la destination secondaire après avoir effectué une opération de basculement. Une licence FlexClone est toutefois requise sur les destinations secondaires pour effectuer les opérations de clonage et de vérification.

|===


== Configuration requise pour l'hôte et le port

Pour connaître la configuration minimale requise pour ONTAP et le plug-in d'application https://imt.netapp.com/matrix/imt.jsp?components=121030;&solution=1259&isHWU&src=IMT[], consultez la [matrice d'interopérabilité Tool^].

[cols="1,3"]
|===
| Hôtes | Configuration minimale requise 


 a| 
Système d'exploitation (64 bits)
 a| 
Voir https://imt.netapp.com/matrix/imt.jsp?components=121030;&solution=1259&isHWU&src=IMT["Matrice d'interopérabilité"^]



 a| 
CPU
 a| 
* Hôte du serveur : 4 cœurs
* Hôte plug-in : 4 cœurs




 a| 
RAM
 a| 
* Hôte du serveur : 8 Go
* Hôte plug-in : 4 Go




 a| 
Espace disque dur
 a| 
Hôte serveur :

* 7 Go pour le logiciel SnapCenter Server et les journaux
* 8 Go pour le référentiel SnapCenter
* Chaque hôte de plug-in : 2 Go pour l'installation et les journaux, cette opération est requise uniquement si le plug-in est installé sur un hôte dédié.




 a| 
Bibliothèques tierces
 a| 
Requis sur l'hôte SnapCenter Server et l'hôte du plug-in :

* Microsoft .NET Framework 4.7.2 ou version ultérieure
* ASP. Bundle d'hébergement NET Core (8.0.5 ou version ultérieure)
* PowerShell 7.4.2 ou version ultérieure




 a| 
Navigateurs
 a| 
Chrome, Internet Explorer et Microsoft Edge

|===
[cols="1,3"]
|===
| Type de port | Port par défaut 


 a| 
Port SnapCenter
 a| 
8146 (HTTPS), bidirectionnel, personnalisable, comme dans l'URL _\https://server:8146_



 a| 
Port de communication SMCore de SnapCenter
 a| 
8145 (HTTPS), bidirectionnel, personnalisable



 a| 
Base de données de référentiel
 a| 
3306 (HTTPS), bidirectionnel



 a| 
Hôtes du plug-in Windows
 a| 
135, 445 (TCP)

En plus des ports 135 et 445, la plage de ports dynamiques spécifiée par Microsoft doit également être ouverte. Les opérations d'installation à distance utilisent le service Windows Management Instrumentation (WMI), qui recherche dynamiquement cette plage de ports.

Pour plus d'informations sur la plage de ports dynamiques prise en charge, reportez-vous à la section https://docs.microsoft.com/en-US/troubleshoot/windows-server/networking/service-overview-and-network-port-requirements["Présentation du service et configuration requise du port réseau pour Windows"^].



 a| 
Plug-in SnapCenter pour Windows
 a| 
8145 (HTTPS), bidirectionnel, personnalisable



 a| 
Cluster ONTAP ou port de communication SVM
 a| 
443 (HTTPS), bidirectionnel ; 80 (HTTP), bidirectionnel

Le port est utilisé pour la communication entre l'hôte du serveur SnapCenter, l'hôte du plug-in et le cluster SVM ou ONTAP.

|===


== Configuration requise pour le plug-in SnapCenter pour Microsoft SQL Server

Vous devez disposer d'un utilisateur disposant de privilèges d'administrateur local avec des autorisations de connexion locales sur l'hôte distant. Si vous gérez des nœuds de cluster, vous devez disposer d'un utilisateur disposant des privilèges d'administration pour tous les nœuds du cluster.

Vous devez disposer d'un utilisateur avec des autorisations sysadmin sur le serveur SQL. Le plug-in utilise la structure Microsoft VDI, qui requiert l'accès sysadmin.

Si vous utilisiez SnapManager pour Microsoft SQL Server et que vous souhaitez importer des données de SnapManager pour Microsoft SQL Server vers SnapCenter, reportez-vous à la section link:../protect-scsql/concept_import_archived_backups_from_snapmanager_for_sql_to_snapcenter.html["Importer les sauvegardes archivées"^]
