---
permalink: protect-scsql/task_define_a_clone_strategy_for_sql_server.html 
sidebar: sidebar 
keywords:  
summary: 'La définition d"une stratégie de clonage vous permet de cloner votre base de données avec succès.' 
---
= Définissez une stratégie de clonage pour SQL Server
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La définition d'une stratégie de clonage vous permet de cloner votre base de données avec succès.

. Examinez les limites liées aux opérations de clonage.
. Choisissez le type de clone dont vous avez besoin.




== Limites des opérations de clonage

Avant de cloner les bases de données, vous devez connaître les limites des opérations de clonage.

* Si vous utilisez une version d'Oracle de 11.2.0.4 à 12.1.0.1, l'opération clone sera à l'état suspendu lorsque vous exécutez la commande _renamedg_. Vous pouvez appliquer le correctif Oracle 19544733 pour résoudre ce problème.
* Le clonage de bases de données à partir d'une LUN directement connectée à un hôte (par exemple, en utilisant l'initiateur iSCSI Microsoft sur un hôte Windows) vers un VMDK ou une LUN RDM sur le même hôte Windows, ou un autre hôte Windows, ou vice versa, n'est pas pris en charge.
* Le répertoire racine du point de montage du volume ne peut pas être un répertoire partagé.
* Si vous déplacez une LUN contenant un clone vers un nouveau volume, le clone ne peut pas être supprimé.




== Types d'opérations de clonage

Vous pouvez utiliser SnapCenter pour cloner une base de données de sauvegarde SQL Server ou une base de données de production.

* Clonage à partir d'une sauvegarde de base de données
+
La base de données clonée peut servir de référence pour le développement de nouvelles applications et contribuer à isoler les erreurs liées aux applications qui se produisent dans l'environnement de production. La base de données clonée peut également être utilisée pour la restauration suite à des erreurs de base de données logicielle.

* Cycle de vie des clones
+
SnapCenter peut être utilisé pour planifier des tâches de clonage récurrentes qui se produiront lorsque la base de données de production n'est pas occupée.


