---
permalink: protect-scsql/task_install_snapcenter_plug_in_package_for_windows_server_on_multiple_remote_hosts_using_cmdlets_scsql.html 
sidebar: sidebar 
keywords: credentials 
summary: 'Vous pouvez installer le plug-in SnapCenter pour Microsoft SQL Server simultanément sur plusieurs hôtes à l"aide de l"applet de commande Install-SmHostPackage PowerShell.' 
---
= Installez le plug-in SnapCenter pour Microsoft SQL Server sur plusieurs hôtes distants à l'aide d'applets de commande
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez installer le plug-in SnapCenter pour Microsoft SQL Server simultanément sur plusieurs hôtes à l'aide de l'applet de commande Install-SmHostPackage PowerShell.

.Avant de commencer
Vous devez vous connecter à SnapCenter en tant qu'utilisateur de domaine disposant des droits d'administrateur local sur chaque hôte sur lequel vous souhaitez installer le module externe.

.Étapes
. Lancer PowerShell.
. Sur l'hôte du serveur SnapCenter, établissez une session à l'aide de l'applet de commande Open-SmConnection, puis saisissez vos informations d'identification.
. Installez le plug-in SnapCenter pour Microsoft SQL Server sur plusieurs hôtes distants à l'aide de l'applet de commande Install-SmHostPackage et des paramètres requis.
+
Les informations relatives aux paramètres pouvant être utilisés avec la cmdlet et leurs descriptions peuvent être obtenues en exécutant _get-Help nom_commande_. Vous pouvez également vous reporter à la https://docs.netapp.com/us-en/snapcenter-cmdlets/index.html["Guide de référence de l'applet de commande du logiciel SnapCenter"^].

+
Vous pouvez utiliser l'option -skippreccheck lorsque vous avez déjà installé les plug-ins manuellement et que vous ne souhaitez pas vérifier si l'hôte répond aux exigences d'installation du plug-in.

. Saisissez vos informations d'identification pour l'installation à distance.

