---
permalink: protect-scsql/task_get_the_CA_certificate_thumbprint.html 
sidebar: sidebar 
keywords: SnapCenter 
summary: Obtenez le certificat CA imprimé. 
---
= Obtenez le certificat CA imprimé
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


Une empreinte de certificat est une chaîne hexadécimale qui identifie un certificat. Une empreinte est calculée à partir du contenu du certificat à l'aide d'un algorithme d'empreinte.

*Étapes*

. Effectuez les opérations suivantes sur l'interface graphique :
+
.. Double-cliquez sur le certificat.
.. Dans la boîte de dialogue certificat, cliquez sur l'onglet *Détails*.
.. Faites défiler la liste des champs et cliquez sur *Thumbprint*.
.. Copiez les caractères hexadécimaux de la zone.
.. Supprimez les espaces entre les nombres hexadécimaux.
+
Par exemple, si l'empreinte est : "a9 09 50 2d d8 2a e4 14 33 e6 f8 38 86 b0 0d 42 77 a3 2a 7b", après avoir retiré les espaces, il sera : "a909502dd82a41433e6f83886b00d4277a32a7b".



. Effectuer les opérations suivantes à partir de PowerShell :
+
.. Exécutez la commande suivante pour lister l'empreinte du certificat installé et identifier le certificat récemment installé par le nom de l'objet.
+
_Get-ChildItem -Path Cert:\Localmachine\My_

.. Copiez l'empreinte.



