---
permalink: protect-scsql/task_disaster_recovery_scsql.html 
sidebar: sidebar 
keywords: disaster recovery 
summary: Lorsque le plug-in SnapCenter pour SQL Server est arrêté, effectuez les étapes manuelles suivantes pour restaurer le plug-in. 
---
= Récupérer le plug-in SnapCenter pour SQL Server après une catastrophe
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Lorsque le plug-in SnapCenter pour SQL Server est arrêté, procédez comme suit pour basculer vers un autre hôte SQL et restaurer les données.

.Avant de commencer
* L'hôte secondaire doit avoir le même système d'exploitation, l'application et le même nom d'hôte que l'hôte principal.
* Déployez le plug-in SnapCenter pour SQL Server sur un hôte alternatif à l'aide de la page *Ajouter un hôte* ou *Modifier l'hôte*. Voir link:https://docs.netapp.com/us-en/snapcenter/admin/concept_manage_hosts.html["Gérez les hôtes dans SnapCenter"] pour plus d'informations.


.Étapes
. Sélectionnez l'hôte dans la page *hosts* pour modifier et installer le plug-in SnapCenter pour SQL Server.
. (Facultatif) remplacez les fichiers de configuration du plug-in SnapCenter pour SQL Server de la sauvegarde de reprise après sinistre vers la nouvelle machine.
. Importez les planifications Windows et SQL à partir du dossier du plug-in SnapCenter pour SQL Server à partir de la sauvegarde DR.


.Informations associées
Voir la link:https://www.youtube.com/watch?v=_8NG-tTGy8k&list=PLdXI3bZJEw7nofM6lN44eOe4aOSoryckg["API de reprise après incident"^] vidéo.
