---
permalink: protect-scsql/task_set_up_credentials_for_snapcenter_plug_ins_package_for_windows.html 
sidebar: sidebar 
keywords: credentials 
summary: 'SnapCenter utilise des identifiants pour authentifier les utilisateurs pour les opérations SnapCenter. Vous devez créer des informations d"identification pour l"installation des plug-ins SnapCenter et des informations d"identification supplémentaires pour exécuter des opérations de protection des données sur des bases de données ou des systèmes de fichiers Windows.' 
---
= Configurer les informations d'identification pour le progiciel de plug-ins SnapCenter pour Windows
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenter utilise des identifiants pour authentifier les utilisateurs pour les opérations SnapCenter. Vous devez créer des informations d'identification pour l'installation des plug-ins SnapCenter et des informations d'identification supplémentaires pour exécuter des opérations de protection des données sur des bases de données ou des systèmes de fichiers Windows.

*Ce dont vous aurez besoin*

* Vous devez configurer les informations d'identification Windows avant d'installer les plug-ins.
* Vous devez configurer les informations d'identification avec les privilèges d'administrateur, y compris les droits d'administrateur sur l'hôte distant.
* Authentification SQL sur les hôtes Windows
+
Vous devez configurer les informations d'identification SQL après l'installation des plug-ins.

+
Si vous déployez le plug-in SnapCenter pour Microsoft SQL Server, vous devez configurer les informations d'identification SQL après l'installation des plug-ins. Configurez les informations d'identification d'un utilisateur avec les autorisations SQL Server sysadmin.

+
La méthode d'authentification SQL s'authentifie par rapport à une instance SQL Server. Cela signifie qu'une instance SQL Server doit être découverte dans SnapCenter. Par conséquent, avant d'ajouter un identifiant SQL, vous devez ajouter un hôte, installer des modules de plug-in et actualiser les ressources. Vous avez besoin de l'authentification SQL Server pour effectuer des opérations telles que la planification ou la détection des ressources.



*Étapes*

. Dans le volet de navigation de gauche, cliquez sur *Paramètres*.
. Dans la page Paramètres, cliquez sur *Credential*.
. Cliquez sur *Nouveau*.
. Dans la page informations d'identification, spécifiez les informations requises pour la configuration des informations d'identification :
+
|===
| Pour ce champ... | Procédez comme ça... 


 a| 
Nom d'identification
 a| 
Entrez un nom pour l'identifiant.



 a| 
Nom d'utilisateur/Mot de passe
 a| 
Entrez le nom d'utilisateur et le mot de passe à utiliser pour l'authentification.

** Administrateur de domaine
+
Spécifiez l'administrateur de domaine sur le système sur lequel vous installez le plug-in SnapCenter. Les formats valides pour le champ Nom d'utilisateur sont les suivants :

+
*** `NetBIOS\UserName`
*** `Domain FQDN\UserName`


** Administrateur local (groupes de travail uniquement)
+
Pour les systèmes appartenant à un groupe de travail, spécifiez l'administrateur local intégré sur le système sur lequel vous installez le plug-in SnapCenter. Vous pouvez spécifier un compte d'utilisateur local appartenant au groupe d'administrateurs locaux si le compte d'utilisateur dispose de privilèges élevés ou si la fonction de contrôle d'accès utilisateur est désactivée sur le système hôte. Le format valide du champ Nom d'utilisateur est : `UserName`

+
N'utilisez pas de guillemets (") ou de contre-coches (") dans les mots de passe. Vous ne devez pas utiliser moins de (<) et un point d'exclamation (!) symboles ensemble dans les mots de passe. Par exemple, moins<!10, moins dix<!, contre-recul 12.





 a| 
Mode d'authentification
 a| 
Sélectionnez le mode d'authentification que vous souhaitez utiliser. Si vous sélectionnez le mode d'authentification SQL, vous devez également spécifier l'instance de serveur SQL et l'hôte où se trouve l'instance SQL.

|===
. Cliquez sur *OK*.


Une fois les informations d'identification terminées, vous pouvez affecter la maintenance des informations d'identification à un utilisateur ou à un groupe d'utilisateurs de la page utilisateur et accès.
