---
permalink: protect-scsql/task_create_backup_policies_for_sql_server_databases.html 
sidebar: sidebar 
keywords: backup policy 
summary: 'Vous pouvez créer une stratégie de sauvegarde pour la ressource ou le groupe de ressources avant d"utiliser SnapCenter pour sauvegarder les ressources SQL Server, ou vous pouvez créer une stratégie de sauvegarde au moment où vous créez un groupe de ressources ou sauvegardez une seule ressource.' 
---
= Créer des stratégies de sauvegarde pour les bases de données SQL Server
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez créer une stratégie de sauvegarde pour la ressource ou le groupe de ressources avant d'utiliser SnapCenter pour sauvegarder les ressources SQL Server, ou vous pouvez créer une stratégie de sauvegarde au moment où vous créez un groupe de ressources ou sauvegardez une seule ressource.

.Avant de commencer
* Vous devez avoir défini votre stratégie de protection des données.
* Vous devez être prêt à préparer la protection des données en exécutant des tâches telles que l'installation d'SnapCenter, l'ajout d'hôtes, l'identification des ressources et la création de connexions du système de stockage.
* Vous devez avoir configuré le répertoire du journal hôte pour la sauvegarde des journaux.
* Vous devez avoir actualisé (découvert) les ressources SQL Server.
* Si vous répliquez des snapshots sur un miroir ou un coffre-fort, l'administrateur SnapCenter doit vous avoir attribué des machines virtuelles de stockage (SVM) pour les volumes source et de destination.
+
Pour plus d'informations sur la manière dont les administrateurs attribuent des ressources aux utilisateurs, consultez les informations d'installation de SnapCenter.

* Si vous souhaitez exécuter les scripts PowerShell dans les scripts prescripteurs et postscripts, définissez la valeur du paramètre usePowerProcessforScripts sur true dans le fichier web.config.
+
La valeur par défaut est FALSE.

* Vérifiez les prérequis et les limites spécifiques de la synchronisation active SnapMirror. Pour plus d'informations, reportez-vous à https://docs.netapp.com/us-en/ontap/smbc/considerations-limits.html#volumes["Limites d'objet pour la synchronisation active SnapMirror"].


.Description de la tâche
* Une stratégie de sauvegarde est un ensemble de règles qui régit la façon dont vous gérez et conservez les sauvegardes, ainsi que la fréquence de sauvegarde de la ressource ou du groupe de ressources. En outre, vous pouvez spécifier des paramètres de réplication et de script. La définition d'options dans une stratégie permet de gagner du temps lorsque vous souhaitez réutiliser la stratégie pour un autre groupe de ressources.
+
Le CHEMIN_SCRIPTS est défini à l'aide de la clé pré-défini WindowsScriptsDirectory située dans le fichier SMCoreServiceHost.exe.Config de l'hôte du plug-in.

+
Si nécessaire, vous pouvez modifier ce chemin et redémarrer le service SMcore. Il est recommandé d'utiliser le chemin par défaut pour la sécurité.

+
La valeur de la clé peut être affichée à partir de Swagger via l'API : API /4.7/configsettings

+
Vous pouvez utiliser L'API GET pour afficher la valeur de la clé. L'API DÉFINIE n'est pas prise en charge.

* SnapLock
+
** Si l'option « conserver les copies de sauvegarde pendant un nombre de jours spécifique » est sélectionnée, la période de conservation SnapLock doit être inférieure ou égale aux jours de conservation mentionnés.
+
La spécification d'une période de verrouillage de snapshot empêche la suppression des snapshots jusqu'à l'expiration de la période de conservation.  Cela peut entraîner la conservation d'un nombre plus important de snapshots que le nombre spécifié dans la règle.

+
Pour ONTAP 9.12.1 et les versions antérieures, les clones créés à partir des snapshots de coffre-fort SnapLock dans le cadre de la restauration hériteront de l'heure d'expiration du coffre-fort SnapLock. L'administrateur du stockage doit nettoyer manuellement les clones après l'heure d'expiration du SnapLock.







== Étape 1 : création d'un nom de stratégie

. Dans le volet de navigation de gauche, sélectionnez *Paramètres*.
. Dans la page Paramètres, sélectionnez *stratégies*.
. Sélectionnez *Nouveau*.
. Sur la page *Nom*, entrez le nom et les détails de la stratégie.




== Étape 2 : configuration des options de stratégie

. Dans la page Type de stratégie, effectuez les opérations suivantes :
+
.. Sélectionnez votre type de stockage.
.. Sélectionnez la portée de la règle.
+
[role="tabbed-block"]
====
.Sauvegarde complète et sauvegarde des journaux
--
Sauvegardez les fichiers de base de données et les journaux de transactions et tronquez les journaux de transactions.

... Sélectionnez *sauvegarde complète et sauvegarde du journal*.
... Entrez le nombre maximal de bases de données à sauvegarder pour chaque snapshot.
+

NOTE: Vous devez augmenter cette valeur si vous souhaitez exécuter simultanément plusieurs opérations de sauvegarde.



--
.Sauvegarde complète
--
Sauvegardez les fichiers de base de données.

... Sélectionnez *sauvegarde complète*.
... Entrez le nombre maximal de bases de données à sauvegarder pour chaque snapshot.
La valeur par défaut est 100
+

NOTE: Vous devez augmenter cette valeur si vous souhaitez exécuter simultanément plusieurs opérations de sauvegarde.



--
.Sauvegarde des journaux
--
... Sauvegardez les journaux de transactions.
... Sélectionnez *sauvegarde journal*.


--
.Copie seule sauvegarde
--
... Si vous sauvegardez vos ressources à l'aide d'une autre application de sauvegarde, sélectionnez *copie uniquement sauvegarde*.


Le fait de préserver l'intégrité des journaux de transactions permet à toute application de sauvegarde de restaurer les bases de données. En règle générale, vous ne devez pas utiliser l'option de copie uniquement dans d'autres cas.


NOTE: Microsoft SQL ne prend pas en charge l'option *copie uniquement sauvegarde* avec l'option *sauvegarde complète et sauvegarde de journal* pour stockage secondaire.

--
====






== Étape 3 : configurer les paramètres du groupe de disponibilité

. Dans la section Paramètres du groupe de disponibilité, effectuez les opérations suivantes :
+
.. Sauvegarde sur le réplica de sauvegarde préféré uniquement.
+
Sélectionnez cette option pour sauvegarder uniquement sur la réplique de sauvegarde préférée. La réplique de sauvegarde préférée est déterminée par les préférences de sauvegarde configurées pour l'AG dans SQL Server.

.. Sélectionnez les répliques pour la sauvegarde.
+
Choisissez la réplique AG principale ou la réplique AG secondaire pour la sauvegarde.

.. Sélectionnez la priorité de sauvegarde (priorité de sauvegarde minimale et maximale)
+
Spécifiez un numéro de priorité de sauvegarde minimum et un numéro de priorité de sauvegarde maximum qui déterminent la réplique AG pour la sauvegarde. Par exemple, vous pouvez avoir une priorité minimale de 10 et une priorité maximale de 50. Dans ce cas, toutes les répliques AG de priorité supérieure à 10 et inférieure à 50 sont considérées comme des sauvegardes.

+
Par défaut, la priorité minimale est 1 et la priorité maximale est 100.



+

NOTE: Dans les configurations en cluster, les sauvegardes sont conservées sur chaque nœud du cluster en fonction des paramètres de conservation définis dans la règle. Si le nœud propriétaire de l'AG change, les sauvegardes sont prises en fonction des paramètres de conservation et les sauvegardes du nœud propriétaire précédent seront conservées. La conservation pour le groupe AG est applicable uniquement au niveau du nœud.





== Étape 4 : configurer les paramètres de Snapshot et de réplication

. Dans la page instantané et réplication, effectuez les opérations suivantes :
+
.. Spécifiez le type d'horaire en sélectionnant *On Demand*, *Hourly*, *Daily*, *Weekly* ou *Monthly*.
+
Vous ne pouvez sélectionner qu'un seul type de planification pour une stratégie.

+

NOTE: Vous pouvez spécifier la planification (date de début, date de fin et fréquence) de l'opération de sauvegarde lors de la création d'un groupe de ressources. Cela vous permet de créer des groupes de ressources partageant la même stratégie et la même fréquence de sauvegarde, mais vous permet d'affecter des programmes de sauvegarde différents à chaque stratégie.

+

NOTE: Si vous avez prévu 2 h 00, l'horaire ne sera pas déclenché pendant l'heure d'été (DST).







== Étape 5 : configurez les paramètres de conservation à chaud

. Dans la section Paramètres de rétention à la minute, en fonction du type de sauvegarde sélectionné dans la page Type de sauvegarde, effectuez une ou plusieurs des opérations suivantes :


[role="tabbed-block"]
====
.Nombre spécifique de copies
--
Conservez uniquement un nombre spécifique d'instantanés.

. Sélectionnez l'option *conserver les sauvegardes de journal applicables au dernier <chiffre> jours* et indiquez le nombre de jours à conserver. Si vous vous approchez de cette limite, vous pouvez supprimer des anciennes copies.


--
.Nombre spécifique de jours
--
Conservation des copies de sauvegarde pendant un nombre spécifique de jours.

. Sélectionnez l'option *conserver les sauvegardes de journal applicables à <nombre> jours de sauvegardes complètes* et spécifiez le nombre de jours pour conserver les copies de sauvegarde de journal.


--
====


== Étape 6 : configurer les paramètres de snapshot

. Pour les paramètres de conservation de sauvegarde complète, effectuez les opérations suivantes :
+
.. Spécifiez le nombre total d'instantanés à conserver
+
... Pour spécifier le nombre d'instantanés à conserver, sélectionnez *copies à conserver*.
... Si le nombre d'instantanés dépasse le nombre spécifié, les instantanés sont supprimés avec les plus anciennes copies supprimées en premier.
+

IMPORTANT: Par défaut, la valeur du nombre de rétention est définie sur 2. Si vous définissez le nombre de rétention sur 1, l'opération de rétention risque d'échouer, car le premier snapshot est l'instantané de référence de la relation SnapVault jusqu'à ce qu'un nouvel instantané soit répliqué sur la cible.

+

NOTE: La valeur de rétention maximale est 1018. Les sauvegardes échouent si la conservation est définie sur une valeur supérieure à celle prise en charge par la version NetApp ONTAP sous-jacente.







. Durée de conservation des snapshots
+
.. Si vous souhaitez spécifier le nombre de jours pendant lesquels vous souhaitez conserver les snapshots avant de les supprimer, sélectionnez *conserver les copies pour*.


. Sélectionnez *Période de verrouillage de la copie instantanée* et spécifiez la durée en jours, mois ou années.
+
La période de conservation SnapLock doit être inférieure à 100 ans.

. Sélectionnez un libellé de stratégie.
+

NOTE: Vous pouvez attribuer des étiquettes SnapMirror aux snapshots principaux pour la réplication à distance, permettant ainsi aux snapshots principaux de décharger l'opération de réplication de snapshot de SnapCenter vers les systèmes secondaires ONTAP .  Cela peut être fait sans activer l’option SnapMirror ou SnapVault dans la page de politique.





== Étape 7 : configurer les options de réplication secondaire

. Dans la section Sélectionner les options de réplication secondaire, sélectionnez l'une des options de réplication secondaires suivantes ou les deux :


[role="tabbed-block"]
====
.Mettez SnapMirror à jour
--
Mettez à jour SnapMirror après la création d'une copie Snapshot locale.

. Sélectionnez cette option pour créer des copies miroir des jeux de sauvegarde sur un autre volume (SnapMirror).
+
Cette option doit être activée pour la synchronisation active SnapMirror.

+
Lors de la réplication secondaire, le délai d'expiration SnapLock charge le délai d'expiration du SnapLock principal. Si vous cliquez sur le bouton *Rafraîchir* de la page topologie, l'heure d'expiration SnapLock secondaire et primaire est actualisée à partir de ONTAP.

+
Voir link:../protect-scsql/task_view_sql_server_backups_and_clones_in_the_topology_page.html["Afficher les sauvegardes et clones SQL Server sur la page topologie"].



--
.Mettre à jour SnapVault
--
Mettre à jour SnapVault après avoir créé une copie Snapshot

. Sélectionnez cette option pour effectuer la réplication de sauvegarde disque à disque.
+
Lors de la réplication secondaire, le délai d'expiration SnapLock charge le délai d'expiration du SnapLock principal. Si vous cliquez sur le bouton *Rafraîchir* de la page topologie, l'heure d'expiration SnapLock secondaire et primaire est actualisée à partir de ONTAP.

+
Lorsque SnapLock est configuré uniquement sur le serveur secondaire à partir de ONTAP appelé coffre-fort SnapLock, cliquez sur le bouton *Actualiser* de la page topologie pour actualiser la période de verrouillage sur le serveur secondaire extrait de ONTAP.

+
Pour plus d'informations sur le coffre-fort SnapLock, voir https://docs.netapp.com/us-en/ontap/snaplock/commit-snapshot-copies-worm-concept.html["Archivage des copies Snapshot sur WORM sur une destination d'archivage sécurisé"]

+
Voir link:../protect-scsql/task_view_sql_server_backups_and_clones_in_the_topology_page.html["Afficher les sauvegardes et clones SQL Server sur la page topologie"].



--
.Nombre de tentatives d'erreur
--
. Saisissez le nombre de tentatives de réplication qui doivent se produire avant l'interruption du processus.


--
====


== Étape 8 : configurer les paramètres de script

. Dans la page script, entrez le chemin d'accès et les arguments du prescripteur ou du PostScript qui doivent être exécutés avant ou après l'opération de sauvegarde, respectivement.
+
Par exemple, vous pouvez exécuter un script pour mettre à jour les traps SNMP, automatiser les alertes et envoyer des logs.

+

NOTE: Le chemin prescripteurs ou postscripts ne doit pas inclure de disques ou de partages. Le chemin doit être relatif au CHEMIN_SCRIPTS.

+

NOTE: Vous devez configurer la règle de conservation SnapMirror dans ONTAP de sorte que le stockage secondaire n'atteigne pas la limite maximale des snapshots.





== Étape 9 : configurer les paramètres de vérification

Dans la page Vérification, effectuez les opérations suivantes :

. Dans la section Exécuter la vérification pour les programmes de sauvegarde suivants, sélectionnez la fréquence de planification.
. Dans la section Options de vérification de cohérence de la base de données, effectuez les opérations suivantes :
+
.. Limiter la structure d'intégrité à la structure physique de la base de données (PHYSIQUE_UNIQUEMENT)
+
... Sélectionnez *Limit the Integrity structure to Physical structure of the database (PHYSICAL_ONLY)* (limiter la vérification de l'intégrité à la structure physique de la base de données) et pour détecter les pages déchirées, les échecs de somme de contrôle et les défaillances matérielles courantes qui affectent la base de données.


.. Supprimer tous les messages d'information (PAS d'INFOMSGS)
+
... Sélectionnez *Supprimer tous les messages d'information (NO_INFOMSGS)* pour supprimer tous les messages d'information. Sélectionné par défaut.


.. Afficher tous les messages d'erreur signalés par objet (ALL_ERRORMSGS)
+
... Sélectionnez *Afficher tous les messages d'erreur signalés par objet (ALL_ERRORMSGS)* pour afficher toutes les erreurs signalées par objet.


.. Ne pas vérifier les index non mis en cluster (ABSENCE DE clusters)
+
... Sélectionnez *ne pas cocher les index non clusterisés (REGROUPÉS EN CLUSTERS)* si vous ne souhaitez pas vérifier les index non clusterisés. La base de données SQL Server utilise le vérificateur de cohérence de base de données Microsoft SQL Server (DBCC) pour vérifier l'intégrité logique et physique des objets de la base de données.


.. Limiter les vérifications et obtenir les verrous au lieu d'utiliser un instantané de base de données interne (TABLOCK)
+
... Sélectionnez *limiter les vérifications et obtenir les verrous au lieu d'utiliser une copie Snapshot de base de données interne (TABLOCK)* pour limiter les vérifications et obtenir des verrous au lieu d'utiliser un instantané de base de données interne.




. Dans la section *Log Backup*, sélectionnez *Verify log backup upon terminés* pour vérifier la sauvegarde du journal à la fin de l'opération.
. Dans la section *Paramètres du script de vérification*, entrez le chemin d'accès et les arguments du prescripteur ou du PostScript qui doivent être exécutés avant ou après l'opération de vérification, respectivement.
+

NOTE: Le chemin prescripteurs ou postscripts ne doit pas inclure de disques ou de partages. Le chemin doit être relatif au CHEMIN_SCRIPTS.





== Étape 10 : passez en revue le résumé

. Passez en revue le résumé, puis sélectionnez *Terminer*.

