---
permalink: protect-sco/alternate-ways-install-plug-in-linux-aix.html 
sidebar: sidebar 
keywords: alternate methods, install, plug-ins package, linux, aix, remote hosts, cmdlets, cluster host, silent mode, console mode 
summary: 'Vous pouvez utiliser d"autres méthodes pour installer SnapCenter Plug-ins Package pour Linux ou SnapCenter Plug-ins Package pour AIX.' 
---
= Autres méthodes d'installation de Plug-ins Package pour Linux ou AIX
:allow-uri-read: 
:icons: font
:imagesdir: ../media/




== Installation sur plusieurs hôtes distants à l'aide d'applets de commande

Vous devez utiliser l'applet de commande _Install-SmHostPackage_ PowerShell pour installer le module de plug-ins SnapCenter pour Linux ou le module de plug-ins SnapCenter pour AIX sur plusieurs hôtes.

*Ce dont vous aurez besoin*

Vous devez être connecté à SnapCenter en tant qu'utilisateur de domaine disposant des droits d'administrateur local sur chaque hôte sur lequel vous souhaitez installer le module externe.

*Étapes*

. Lancer PowerShell.
. Sur l'hôte du serveur SnapCenter, établissez une session à l'aide de l'applet de commande _Open-SmConnection_, puis saisissez vos informations d'identification.
. Installez le package de plug-ins SnapCenter pour Linux ou le package de plug-ins SnapCenter pour AIX à l'aide de l'applet de commande _Install-SmHostPackage_ et des paramètres requis.
+
Vous pouvez utiliser l'option _-skipprecheck_ lorsque vous avez déjà installé les plug-ins manuellement et ne voulez pas vérifier si l'hôte répond aux exigences requises pour installer le plug-in.

+

NOTE: Le script de vérification préalable ne valide pas l'état du pare-feu du port du plug-in s'il est spécifié dans les règles de rejet du pare-feu.

. Saisissez vos informations d'identification pour l'installation à distance.


Les informations relatives aux paramètres pouvant être utilisés avec la cmdlet et leurs descriptions peuvent être obtenues en exécutant _get-Help nom_commande_. Vous pouvez également vous reporter au https://library.netapp.com/ecm/ecm_download_file/ECMLP2883300["Guide de référence de l'applet de commande du logiciel SnapCenter"^].



== Installez-le sur l'hôte du cluster

Vous devez installer SnapCenter Plug-ins Package pour Linux ou SnapCenter Plug-ins Package pour AIX sur les deux nœuds de l'hôte cluster.

Chacun des nœuds de l'hôte de cluster a deux adresses IP. L'une des adresses IP sera l'adresse IP publique des nœuds respectifs et la seconde sera l'adresse IP du cluster partagée entre les deux nœuds.

*Étapes*

. Installez le package de plug-ins SnapCenter pour Linux ou le package de plug-ins SnapCenter pour AIX sur les deux nœuds de l'hôte de cluster.
. Vérifiez que les valeurs correctes pour les paramètres SNAPCENTER_SERVER_HOST, SPL_PORT, SNAPCENTER_SERVER_PORT et SPL_ENABLED_PLUGINS sont spécifiées dans le fichier spl.properties situé à _/var/opt/snapcenter/SPL/etc/_.
+
Si SPL_ENABLED_PLUGINS n'est pas spécifié dans spl.properties, vous pouvez l'ajouter et attribuer la valeur SCO,SCU.

. Sur l'hôte du serveur SnapCenter, établissez une session à l'aide de l'applet de commande _Open-SmConnection_, puis saisissez vos informations d'identification.
. Dans chacun des nœuds, définissez les adresses IP préférées du nœud à l'aide de la commande _set-PreferredHostIPsInStorageExportPolicy_ sccli et des paramètres requis.
. Dans l'hôte SnapCenter Server, ajoutez une entrée pour l'adresse IP du cluster et le nom DNS correspondant dans _C:\Windows\System32\drivers\etc\hosts_.
. Ajoutez le nœud au serveur SnapCenter à l'aide de l'applet de commande _Add-SmHost_ en spécifiant l'adresse IP du cluster pour le nom d'hôte.


Découvrez la base de données Oracle sur le nœud 1 (en supposant que l'adresse IP du cluster est hébergée sur le nœud 1) et créez une sauvegarde de la base de données. En cas de basculement, vous pouvez utiliser la sauvegarde créée sur le nœud 1 pour restaurer la base de données sur le nœud 2. Vous pouvez également utiliser la sauvegarde créée sur le nœud 1 pour créer un clone sur le nœud 2.


NOTE: En cas de basculement, des volumes, des répertoires et des fichiers seront obsolètes, lorsque d'autres opérations SnapCenter sont en cours d'exécution.



== Installez le module Plug-ins pour Linux en mode silencieux ou en mode console

Vous pouvez installer le module de plug-ins SnapCenter pour Linux en mode console ou en mode silencieux à l'aide de l'interface de ligne de commande (CLI).

*Ce dont vous aurez besoin*

* Vous devez passer en revue les conditions préalables à l'installation du package de plug-ins.
* Vous devez vous assurer que la variable d'environnement D'AFFICHAGE n'est pas définie.
+
Si la variable d'environnement D'AFFICHAGE est définie, vous devez annuler l'AFFICHAGE, puis essayer d'installer manuellement le plug-in.



*À propos de cette tâche*

Vous devez fournir les informations nécessaires à l'installation lors de l'installation en mode console, alors qu'en mode silencieux, vous n'avez pas à fournir d'informations d'installation.

*Étapes*

. Téléchargez le module de plug-ins SnapCenter pour Linux à partir de l'emplacement d'installation du serveur SnapCenter.
+
Le chemin d'installation par défaut est _C:\ProgramData\NetApp\SnapCenter\PackageRepository_. Ce chemin est accessible à partir de l'hôte sur lequel le serveur SnapCenter est installé.

. À partir de l'invite de commande, accédez au répertoire dans lequel vous avez téléchargé le fichier d'installation.
. En fonction de votre mode d'installation préféré, effectuez l'une des opérations suivantes.
+
|===
| Mode d'installation | Étapes 


 a| 
Mode console
 a| 
.. Exécuter :
+
`./SnapCenter_linux_host_plugin.bin –i console`

.. Suivez les invites à l'écran pour terminer l'installation.




 a| 
Mode silencieux
 a| 
Exécuter :

`./SnapCenter_linux_host_plugin.bin-i silent-DPORT=8145-DSERVER_IP=SnapCenter_Server_FQDN-DSERVER_HTTPS_PORT=SnapCenter_Server_Port-DUSER_INSTALL_DIR==/opt/custom_path`

|===
. Modifiez le fichier spl.properties situé à l'adresse _/var/opt/snapcenter/spl/etc/_ pour ajouter SPL_ENABLED_PLUGINS=SCO,SCU, puis redémarrez le service de chargeur de plug-in SnapCenter.



IMPORTANT: L'installation du package plug-ins enregistre les plug-ins sur l'hôte et non sur le serveur SnapCenter. Vous devez enregistrer les plug-ins sur le serveur SnapCenter en ajoutant l'hôte à l'aide de l'interface graphique de SnapCenter ou de l'applet de commande PowerShell. Lors de l'ajout de l'hôte, sélectionnez « aucun » comme identifiant. Une fois l'hôte ajouté, les plug-ins installés sont automatiquement découverts.



== Installez le module plug-ins pour AIX en mode silencieux

Vous pouvez installer le module de plug-ins SnapCenter pour AIX en mode silencieux à l'aide de l'interface de ligne de commande (CLI).

*Ce dont vous aurez besoin*

* Vous devez passer en revue les conditions préalables à l'installation du package de plug-ins.
* Vous devez vous assurer que la variable d'environnement D'AFFICHAGE n'est pas définie.
+
Si la variable d'environnement D'AFFICHAGE est définie, vous devez annuler l'AFFICHAGE, puis essayer d'installer manuellement le plug-in.



*Étapes*

. Téléchargez le module de plug-ins SnapCenter pour AIX à partir de l'emplacement d'installation du serveur SnapCenter.
+
Le chemin d'installation par défaut est _C:\ProgramData\NetApp\SnapCenter\PackageRepository_. Ce chemin est accessible à partir de l'hôte sur lequel le serveur SnapCenter est installé.

. À partir de l'invite de commande, accédez au répertoire dans lequel vous avez téléchargé le fichier d'installation.
. Courez
+
`./snapcenter_aix_host_plugin.bsx-i silent-DPORT=8145-DSERVER_IP=SnapCenter_Server_FQDN-DSERVER_HTTPS_PORT=SnapCenter_Server_Port-DUSER_INSTALL_DIR==/opt/custom_path-DINSTALL_LOG_NAME=SnapCenter_AIX_Host_Plug-in_Install_MANUAL.log-DCHOSEN_FEATURE_LIST=CUSTOMDSPL_USER=install_user`

. Modifiez le fichier spl.properties situé à l'adresse _/var/opt/snapcenter/spl/etc/_ pour ajouter SPL_ENABLED_PLUGINS=SCO,SCU, puis redémarrez le service de chargeur de plug-in SnapCenter.



IMPORTANT: L'installation du package plug-ins enregistre les plug-ins sur l'hôte et non sur le serveur SnapCenter. Vous devez enregistrer les plug-ins sur le serveur SnapCenter en ajoutant l'hôte à l'aide de l'interface graphique de SnapCenter ou de l'applet de commande PowerShell. Lors de l'ajout de l'hôte, sélectionnez « aucun » comme identifiant. Une fois l'hôte ajouté, les plug-ins installés sont automatiquement découverts.
