---
permalink: protect-sco/catalog-backups.html 
sidebar: sidebar 
keywords: oracle databases discover 
summary: Comment SnapCenter découvre les bases de données Oracle. 
---
= Comment cataloguer les sauvegardes avec Oracle Recovery Manager
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez cataloguer les sauvegardes de bases de données Oracle à l'aide d'Oracle Recovery Manager (RMAN) pour stocker les informations de sauvegarde dans le référentiel Oracle RMAN.

Les sauvegardes cataloguées peuvent être utilisées ultérieurement pour les opérations de restauration au niveau des blocs ou de restauration à un point dans le temps de l'espace de stockage. Lorsque vous n'avez pas besoin de ces sauvegardes cataloguées, vous pouvez supprimer les informations du catalogue.

La base de données doit être montée ou supérieure pour le catalogage. Vous pouvez catalogage des sauvegardes de données, des sauvegardes de journaux d'archivage et des sauvegardes complètes. Si le catalogage est activé pour une sauvegarde d'un groupe de ressources possédant plusieurs bases de données, le catalogage est effectué pour chaque base de données. Pour les bases de données Oracle RAC, le catalogage s'effectue sur le nœud préféré où la base de données est au moins à l'état montée.

Si vous souhaitez cataloguer les sauvegardes d'une base de données RAC, assurez-vous qu'aucune autre tâche n'est en cours d'exécution pour cette base de données. Si un autre travail est en cours d'exécution, l'opération de catalogage échoue au lieu d'être mise en file d'attente.



== Base de données de catalogue externe

Par défaut, le fichier de contrôle de la base de données cible est utilisé pour le catalogage. Si vous souhaitez ajouter une base de données de catalogue externe, vous pouvez la configurer en spécifiant les informations d'identification et le nom de support réseau transparent (TNS) du catalogue externe à l'aide de l'assistant Paramètres de base de données de l'interface utilisateur graphique de SnapCenter. Vous pouvez également configurer la base de données du catalogue externe à partir de l'interface CLI en exécutant la commande Configure-SmOracleDatabase avec les options -OracleRmanCatalCredentialName et -OracleRmanCatalTnsName.



== Commande RMAN

Si vous avez activé l'option de catalogage lors de la création d'une stratégie de sauvegarde Oracle à partir de l'interface utilisateur graphique SnapCenter, les sauvegardes sont cataloguées à l'aide d'Oracle RMAN dans le cadre de l'opération de sauvegarde. Vous pouvez également procéder au catalogage différé des sauvegardes en exécutant `Catalog-SmBackupWithOracleRMAN` commande.

Une fois les sauvegardes catalogués, vous pouvez exécuter `Get-SmBackupDetails` pour obtenir les informations de sauvegarde cataloguées, telles que la balise des fichiers de données catalogués, le chemin du catalogue de fichiers de contrôle et les emplacements des journaux d'archives catalogués.



== Format de dénomination

Si le nom du groupe de disques ASM est supérieur ou égal à 16 caractères, à partir de SnapCenter 3.0, le format de nommage utilisé pour la sauvegarde est SC_HASHCODEofDISKGROUP_DBSID_BACKUPID. Cependant, si le nom du groupe de disques est inférieur à 16 caractères, le format de nommage utilisé pour la sauvegarde est DISKGROUPNAME_DBSID_BACKUPID, qui est le même format que celui utilisé dans SnapCenter 2.0.

Le HASHCODEofDISKGROUP est un nombre généré automatiquement (2 à 10 chiffres) unique pour chaque groupe de disques ASM.



== Opérations de contre-vérification

Vous pouvez effectuer des vérifications croisées pour mettre à jour les informations de référentiel RMAN obsolètes concernant les sauvegardes dont les enregistrements de référentiel ne correspondent pas à leur état physique. Par exemple, si un utilisateur supprime les journaux archivés du disque à l'aide d'une commande du système d'exploitation, le fichier de contrôle indique toujours que les journaux sont sur le disque, alors qu'en fait ils ne le sont pas.

L'opération crosscheck vous permet de mettre à jour le fichier de contrôle avec les informations. Vous pouvez activer la fonction crosscheck en exécutant la commande set-SmConfigSettings et en attribuant la valeur TRUE au paramètre ENABLE_CROSSCHECK. La valeur par défaut est FALSE.

`sccli Set-SmConfigSettings-ConfigSettingsTypePlugin-PluginCodeSCO-ConfigSettings "KEY=ENABLE_CROSSCHECK, VALUE=TRUE"`



== Supprimer les informations du catalogue

Vous pouvez supprimer les informations de catalogue en exécutant la commande uncatalog-SmBackupWithOracleRMAN. Vous ne pouvez pas supprimer les informations du catalogue à l'aide de l'interface graphique de SnapCenter. Toutefois, les informations d'une sauvegarde cataloguée sont supprimées lors de la suppression de la sauvegarde ou lors de la suppression de la rétention et du groupe de ressources associés à cette sauvegarde cataloguée.


NOTE: Lorsque vous forcez la suppression de l'hôte SnapCenter, les informations des sauvegardes cataloguées associées à cet hôte ne sont pas supprimées. Vous devez supprimer les informations de toutes les sauvegardes cataloguées de cet hôte avant de forcer la suppression de l'hôte.

Si le catalogage et le décatalogage échoue parce que le temps d'opération a dépassé la valeur de temporisation spécifiée pour le paramètre ORACLE_PLUGIN_RMAN_CATALOG_TIMEOUT, vous devez modifier la valeur du paramètre en exécutant la commande suivante :

`/opt/Netapp/snapcenter/spl/bin/sccli Set-SmConfigSettings-ConfigSettingsType Plugin -PluginCode SCO-ConfigSettings "KEY=ORACLE_PLUGIN_RMAN_CATALOG_TIMEOUT,VALUE=user_defined_value"`

Après avoir modifié la valeur du paramètre, redémarrer le service SnapCenter Plug-in Loader (SPL) en exécutant la commande suivante :

`/opt/NetApp/snapcenter/spl/bin/spl restart`

Les informations concernant les paramètres qui peuvent être utilisés avec la commande et leurs descriptions peuvent être obtenues en exécutant Get-Help nom_commande. Vous pouvez également vous reporter au https://library.netapp.com/ecm/ecm_download_file/ECMLP2883301["Guide de référence sur les commandes du logiciel SnapCenter"^].
