---
permalink: protect-sco/discover-oracle-database.html 
sidebar: sidebar 
keywords: oracle databases discover 
summary: Comment SnapCenter découvre les bases de données Oracle. 
---
= Comment SnapCenter détecte les bases de données Oracle
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Les ressources sont des bases de données Oracle gérées par SnapCenter sur l'hôte. Vous pouvez ajouter ces bases de données à des groupes de ressources pour exécuter des opérations de protection des données après avoir découvert les bases de données disponibles.

Les sections suivantes décrivent le processus utilisé par SnapCenter pour détecter les différents types et versions de bases de données Oracle.



== Pour Oracle versions 11__g__ à 12__c__R1

.Base de données RAC
Les bases de données RAC ne sont découvertes que sur la base de /etc/oratab'intries. Vous devez avoir les entrées de la base de données dans le fichier /etc/oratab.

.Autonome
Les bases de données autonomes ne sont découvertes que sur la base des entrées /etc/oratab.

.DE
L'entrée d'instance ASM doit être disponible dans le fichier /etc/oratab.

.RAC un nœud
Les bases de données RAC One Node ne sont découvertes que sur la base des entrées /etc/oratab. Les bases de données doivent être à l'état nomount, mount ou open. Vous devez avoir les entrées de la base de données dans le fichier /etc/oratab.

L'état de la base de données RAC One Node sera marqué comme renommé ou supprimé si la base de données est déjà découverte et que les sauvegardes sont associées à la base de données.

Si la base de données est déplacée, procédez comme suit :

. Ajoutez manuellement l'entrée de base de données déplacée dans le fichier /etc/oratab sur le nœud RAC défaillant.
. Actualisez manuellement les ressources.
. Sélectionnez la base de données RAC One Node dans la page de ressources, puis cliquez sur Paramètres de base de données.
. Configurez la base de données pour définir les nœuds de cluster préférés sur le nœud RAC qui héberge actuellement la base de données.
. Effectuer les opérations SnapCenter.
. Si vous avez déplacé une base de données d'un nœud vers un autre et si l'entrée oratab du nœud précédent n'est pas supprimée, supprimez manuellement l'entrée oratab pour éviter que la même base de données ne s'affiche deux fois.




== Pour les versions 12cR2 à 18c d'Oracle

.Base de données RAC
Les bases de données RAC sont découvertes à l'aide de la commande srvctl config. Vous devez avoir les entrées de la base de données dans le fichier /etc/oratab.

.Autonome
Les bases de données autonomes sont découvertes en fonction des entrées du fichier /etc/oratab et de la sortie de la commande srvctl config.

.DE
L'entrée de l'instance ASM n'a pas besoin d'être dans le fichier /etc/oratab.

.RAC un nœud
Les bases de données RAC One Node sont découvertes à l'aide de la commande srvctl config uniquement. Les bases de données doivent être à l'état nomount, mount ou open. L'état de la base de données RAC One Node sera marqué comme renommé ou supprimé si la base de données est déjà découverte et que les sauvegardes sont associées à la base de données.

Si la base de données est déplacée, procédez comme suit : . Actualisez manuellement les ressources. . Sélectionnez la base de données RAC One Node dans la page de ressources, puis cliquez sur Paramètres de base de données. . Configurez la base de données pour définir les nœuds de cluster préférés sur le nœud RAC qui héberge actuellement la base de données. . Effectuer les opérations SnapCenter.


NOTE: S'il y a des entrées de base de données Oracle 12__c__R2 et 18__c__ dans le fichier /etc/oratab et que la même base de données est enregistrée avec la commande srvctl config, SnapCenter éliminera les entrées de base de données dupliquées. Si des entrées de base de données obsolètes sont présentes, la base de données sera découverte mais la base de données sera inaccessible et son statut sera déconnecté.
