---
permalink: protect-sco/reference_requirements_for_backing_up_an_oracle_database.html 
sidebar: sidebar 
keywords: requirements, prerequisites 
summary: Avant de sauvegarder une base de données Oracle, assurez-vous que les prérequis sont terminés. 
---
= Conditions requises pour la sauvegarde d'une base de données Oracle
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Avant de sauvegarder une base de données Oracle, assurez-vous que les prérequis sont terminés.

* Vous devez avoir créé un groupe de ressources associé à une stratégie.
* Si vous souhaitez sauvegarder une ressource avec une relation SnapMirror avec un système de stockage secondaire, le rôle ONTAP attribué à l'utilisateur de stockage doit inclure le privilège « napmirror All ». Toutefois, si vous utilisez le rôle « vsadmin », le privilège « napmirror all » n'est pas requis.
* Vous devez avoir attribué l'agrégat utilisé par l'opération de sauvegarde à la machine virtuelle de stockage (SVM) utilisée par la base de données.
* Vous devez avoir vérifié que tous les volumes de données et de journaux d'archivage appartenant à la base de données sont protégés si la protection secondaire est activée pour cette base de données.
* Vous devriez avoir vérifié que la base de données contenant des fichiers sur les groupes de disques ASM doit être à l'état "MONTANT" ou "OPEN" pour vérifier ses sauvegardes à l'aide de l'utilitaire DBVERIFY d'Oracle.
* Vous devez avoir vérifié que la longueur du point de montage du volume ne dépasse pas 240 caractères.
* Vous devez augmenter la valeur de RESTTimeout à 86400000 ms dans la valeur _C:\Program Files\NetApp \SMCore\SMCoreServiceHost.exe.config_ file de l'hôte SnapCenter Server, si la base de données en cours de sauvegarde est importante (taille en To).
+
Lors de la modification des valeurs, assurez-vous qu'il n'y a pas de travaux en cours d'exécution et redémarrez le service SnapCenter SMCore après avoir augmenté la valeur.


