---
permalink: protect-sce/reference_exchange_database_and_backup_verification.html 
sidebar: sidebar 
keywords:  
summary: 'Le plug-in SnapCenter pour Microsoft Exchange Server ne permet pas de vérifier les sauvegardes. Toutefois, vous pouvez utiliser l"outil SSET fourni avec Exchange pour vérifier les bases de données et les sauvegardes Exchange.' 
---
= Vérification des sauvegardes et des bases de données Exchange
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Le plug-in SnapCenter pour Microsoft Exchange Server ne permet pas de vérifier les sauvegardes. Toutefois, vous pouvez utiliser l'outil SSET fourni avec Exchange pour vérifier les bases de données et les sauvegardes Exchange.

L'outil Microsoft Exchange Eseutil est un utilitaire de ligne de commande inclus avec votre serveur Exchange. L'utilitaire vous permet d'effectuer des contrôles de cohérence pour vérifier l'intégrité des bases de données et des sauvegardes Exchange.

|===


| *Meilleure pratique:* il n'est pas nécessaire d'effectuer des contrôles de cohérence sur les bases de données faisant partie d'une configuration DAG (Database Availability Group) avec au moins deux répliques. 
|===
Pour plus d'informations, reportez-vous à la section https://docs.microsoft.com/en-us/exchange/exchange-server?view=exchserver-2019["Documentation Microsoft Exchange Server"^].
