---
permalink: protect-sce/reference_granular_recovery_of_mails_and_mailbox.html 
sidebar: sidebar 
keywords: SMBR, Single Mailbox recovery, Exchange database 
summary: 'Le logiciel Single Mailbox Recovery (SMBR) vous permet de restaurer et de récupérer des messages ou des boîtes aux lettres à la place de la base de données Exchange complète.' 
---
= Restauration granulaire des e-mails et des boîtes aux lettres
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Le logiciel Single Mailbox Recovery (SMBR) vous permet de restaurer et de récupérer des messages ou des boîtes aux lettres à la place de la base de données Exchange complète.

La restauration d'une base de données complète simplement pour restaurer un courrier spécifique prendra beaucoup de temps et de ressources. SMBR permet de restaurer rapidement les courriers électroniques en créant une copie clone du Snapshot, puis en utilisant des API Microsoft pour monter la boîte aux lettres dans SMBR. Pour plus d'informations sur l'utilisation de SMBR, reportez-vous à https://["Guide d'administration de SMBR"^].

*Plus d'informations*

* link:../install/concept_snapcenter_licenses.html#single-mailbox-recovery-smbr-licenses["Licences SMBR"^]
* https://["Bibliothèque de documentation SMBR"^]
* https://["Comment restaurer à partir d'un stockage secondaire dans SMBR avec SnapCenter"^]
* https://["Restauration de Microsoft Exchange Mail à partir de SnapVault à l'aide de SMBR"^]

