---
permalink: protect-sce/task_restore_exchange_resources_using_powershell_cmdlets.html 
sidebar: sidebar 
keywords: restore 
summary: 'La restauration d"une base de données Exchange inclut le lancement d"une session de connexion avec le serveur SnapCenter, la liste des sauvegardes, la récupération des informations de sauvegarde et la restauration d"une sauvegarde.' 
---
= Restauration des ressources Exchange à l'aide des applets de commande PowerShell
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La restauration d'une base de données Exchange inclut le lancement d'une session de connexion avec le serveur SnapCenter, la liste des sauvegardes, la récupération des informations de sauvegarde et la restauration d'une sauvegarde.

Vous devez avoir préparé l'environnement PowerShell pour exécuter les applets de commande PowerShell.

*Étapes*

. Démarrez une session de connexion avec le serveur SnapCenter pour un utilisateur spécifié en utilisant le `Open-SmConnection` applet de commande.
+
[listing]
----
Open-smconnection  -SMSbaseurl  https://snapctr.demo.netapp.com:8146/
----
. Récupérez les informations relatives à une ou plusieurs sauvegardes que vous souhaitez restaurer à l'aide de la `Get-SmBackup` applet de commande.
+
Cet exemple affiche des informations sur toutes les sauvegardes disponibles :

+
[listing]
----
PS C:\> Get-SmBackup

BackupId                      BackupName                    BackupTime                    BackupType
--------                      ----------                    ----------                    ----------
341                           ResourceGroup_36304978_UTM... 12/8/2017 4:13:24 PM          Full Backup
342                           ResourceGroup_36304978_UTM... 12/8/2017 4:16:23 PM          Full Backup
355                           ResourceGroup_06140588_UTM... 12/8/2017 6:32:36 PM          Log Backup
356                           ResourceGroup_06140588_UTM... 12/8/2017 6:36:20 PM          Full Backup
----
. Restaurez les données à partir de la sauvegarde à l'aide du `Restore-SmBackup` applet de commande.
+
Cet exemple restaure une sauvegarde en moins d'une minute :

+
[listing]
----
C:\PS> Restore-SmBackup -PluginCode SCE -AppObjectId 'sce-w2k12-exch.sceqa.com\sce-w2k12-exch_DB_2' -BackupId 341 -IsRecoverMount:$true
----
+
Cet exemple restaure une sauvegarde instantanée :

+
[listing]
----
C:\ PS> Restore-SmBackup -PluginCode SCE -AppObjectId 'sce-w2k12-exch.sceqa.com\sce-w2k12-exch_DB_2' -BackupId 341 -IsRecoverMount:$true -LogRestoreType ByTransactionLogs -LogCount 2
----
+
Cet exemple restaure une sauvegarde sur un système de stockage secondaire dans l'histoire principale :

+
[listing]
----
C:\ PS> Restore-SmBackup -PluginCode 'SCE' -AppObjectId 'DB2' -BackupId 81 -IsRecoverMount:$true -Confirm:$false
-archive @{Primary="paw_vs:vol1";Secondary="paw_vs:vol1_mirror"} -logrestoretype All
----
+
Le `-archive` paramètre vous permet de spécifier les volumes primaire et secondaire que vous souhaitez utiliser pour la restauration.

+
Le `-IsRecoverMount:$true` paramètre vous permet de monter la base de données après la restauration.



Les informations relatives aux paramètres pouvant être utilisés avec la cmdlet et leurs descriptions peuvent être obtenues en exécutant _get-Help nom_commande_. Vous pouvez également vous reporter au https://library.netapp.com/ecm/ecm_download_file/ECMLP2883300["Guide de référence de l'applet de commande du logiciel SnapCenter"^].
