---
permalink: protect-sce/task_install_the_snapcenter_plug_in_for_exchange_silently_from_the_command_line.html 
sidebar: sidebar 
keywords:  
summary: 'Vous devez installer le plug-in pour Exchange à partir de l"interface utilisateur SnapCenter. Cependant, si vous ne pouvez pas pour une raison quelconque, vous pouvez exécuter le programme d"installation de Plug-in pour Exchange sans surveillance en mode silencieux à partir de la ligne de commande Windows.' 
---
= Installez le plug-in SnapCenter pour l'échange silencieusement à partir de la ligne de commande
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous devez installer le plug-in pour Exchange à partir de l'interface utilisateur SnapCenter. Cependant, si vous ne pouvez pas pour une raison quelconque, vous pouvez exécuter le programme d'installation de Plug-in pour Exchange sans surveillance en mode silencieux à partir de la ligne de commande Windows.

*Ce dont vous aurez besoin*

* Vous devez avoir sauvegardé vos ressources Microsoft Exchange Server.
* Vous devez avoir installé les modules du plug-in SnapCenter.
* Vous devez supprimer la version antérieure du plug-in SnapCenter pour Microsoft SQL Server avant de procéder à l'installation.
+
Pour plus d'informations, voir https://kb.netapp.com/Advice_and_Troubleshooting/Data_Protection_and_Security/SnapCenter/How_to_Install_a_SnapCenter_Plug-In_manually_and_directly_from_thePlug-In_Host["Comment installer un plug-in SnapCenter manuellement et directement à partir de l'hôte du plug-in"^].



*Étapes*

. Vérifiez si le dossier _C:\temp_ existe sur l'hôte du plug-in et que l'utilisateur connecté dispose d'un accès complet.
. Téléchargez le plug-in SnapCenter pour Microsoft Windows depuis le site _C:\ProgramData\NetApp\SnapCenter\Package_ Repository.
+
Ce chemin est accessible à partir de l'hôte sur lequel le serveur SnapCenter est installé.

. Copiez le fichier d'installation sur l'hôte sur lequel vous souhaitez installer le plug-in.
. À partir d'une invite de commande Windows sur l'hôte local, accédez au répertoire dans lequel vous avez enregistré les fichiers d'installation du plug-in.
. Entrez la commande suivante pour installer le remplacement des variables par vos données :
+
_Snapcenter_Windows_host_plugin.exe"/muet /debuglog"<Debug_Log_Path>" /log"<Log_Path>« BI_SNAPCENTER_PORT=<Num> SUITE_INSTALLSCE=« Install_Directory_Path> » EPBI_SEREACCOUNT=<SERVICONTAP__PRODUCT_install_SICMADE>

+
Par exemple :

+
_C:\ProgramData\NetApp\SnapCenter\Package Repository\snapcenter_Windows_host_plugin.exe »/Silent /debulog« C:\HPPSCSQL_Install.log » /log« C:\temp » BI_SNAPCENTER_PORT=8145 SUITE_INSTALLDIR=« C:\Program Files\utilisateur_d'installation_de_HP_SICentrer=ISPs_SICentrer_SICentrer=s_SICentrer_SICentrer_SICentrer=s_SICentrer_SICentrer_SICentrer=s_SICentrer_SICentrer=s

+

NOTE: Tous les paramètres transmis lors de l'installation du plug-in pour Exchange sont sensibles à la casse.

+
.. _/muet /debuglog"C:\Installdebug.log" /log"C:\temp" BI_SNAPCENTER_PORT=8145 SUITE_INSTALLDIR="C:\Program Files" BI_SERVICEACCOUNT=DEMO\Administrator BI_SERVICEPWD=Netapp1! ISFeatureInstall=HPPW,SCW_
+
Entrez les valeurs suivantes pour les variables :

+
|===
| Variable | Valeur 


 a| 
_/debuglog »<Debug_Log_Path>_
 a| 
Spécifiez le nom et l'emplacement du fichier journal du programme d'installation de la suite, comme dans l'exemple suivant :

_Setup.exe /debuglog"C:\PathToLog\setupexe.log_



 a| 
BI_SNAPCENTER_PORT
 a| 
Spécifiez le port sur lequel SnapCenter communique avec SMCore.



 a| 
SUITE_INSTALLDIR
 a| 
Spécifiez le répertoire d'installation du module de plug-in hôte.



 a| 
BI_SERVICEACCOUNT
 a| 
Spécifiez le compte de service Web SnapCenter Plug-in pour Microsoft Windows.



 a| 
BI_SERVICEPWD
 a| 
Spécifiez le mot de passe du compte de service Web SnapCenter Plug-in pour Microsoft Windows.



 a| 
Installation de ISFeatureInstall
 a| 
Spécifier la solution à déployer par SnapCenter sur un hôte distant

|===


. Surveillez le planificateur de tâches Windows, le fichier journal d'installation principal _C:\Installdebug.log_ et les fichiers d'installation supplémentaires dans _C:\Temp_.
. Surveillez le répertoire _%temp%_ pour vérifier si les programmes d'installation _msiexe.exe_ installent le logiciel sans erreur.
+

NOTE: L'installation du plug-in pour Exchange enregistre le plug-in sur l'hôte et non sur le serveur SnapCenter. Vous pouvez enregistrer le plug-in sur le serveur SnapCenter en ajoutant l'hôte à l'aide de l'interface graphique de SnapCenter ou de l'applet de commande PowerShell. Une fois l'hôte ajouté, le plug-in est automatiquement découvert.


