---
permalink: protect-sce/task_set_up_credentials_for_the_snapcenter_plug_in_for_windows_sce.html 
sidebar: sidebar 
keywords:  
summary: 'SnapCenter utilise des identifiants pour authentifier les utilisateurs pour les opérations SnapCenter. Vous devez créer des informations d"identification pour l"installation du module d"extension et des informations d"identification supplémentaires pour effectuer des opérations de protection des données sur les bases de données.' 
---
= Configuration des informations d'identification pour le plug-in SnapCenter pour Windows
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenter utilise des identifiants pour authentifier les utilisateurs pour les opérations SnapCenter. Vous devez créer des informations d'identification pour l'installation du module d'extension et des informations d'identification supplémentaires pour effectuer des opérations de protection des données sur les bases de données.

*À propos de cette tâche*

Vous devez configurer les informations d'identification pour l'installation des plug-ins sur les hôtes Windows. Bien que vous puissiez créer des identifiants pour Windows après le déploiement d'hôtes et l'installation de plug-ins, il est conseillé de créer des identifiants après l'ajout de SVM, avant de déployer des hôtes et d'installer des plug-ins.

Configurez les informations d'identification avec les privilèges d'administrateur, y compris les droits d'administrateur sur l'hôte distant.

Si vous configurez des informations d'identification pour des groupes de ressources individuels et que le nom d'utilisateur ne dispose pas de privilèges d'administrateur complets, vous devez affecter au moins le groupe de ressources et les privilèges de sauvegarde au nom d'utilisateur.

*Étapes*

. Dans le volet de navigation de gauche, cliquez sur *Paramètres*.
. Dans la page Paramètres, cliquez sur *Credential*.
. Cliquez sur *Nouveau*.
+
La fenêtre Credential s'affiche.

. Dans la page informations d'identification, procédez comme suit :
+
|===
| Pour ce champ... | Procédez comme ça... 


 a| 
Nom d'identification
 a| 
Entrez un nom pour l'identifiant.



 a| 
Nom d'utilisateur
 a| 
Entrez le nom d'utilisateur utilisé pour l'authentification.

** Administrateur de domaine ou tout membre du groupe d'administrateurs
+
Spécifiez l'administrateur de domaine ou tout membre du groupe d'administrateurs sur le système sur lequel vous installez le plug-in SnapCenter. Les formats valides pour le champ Nom d'utilisateur sont les suivants :

+
*** `NetBIOS\UserName`
*** `Domain FQDN\UserName`


** Administrateur local (groupes de travail uniquement)
+
Pour les systèmes appartenant à un groupe de travail, spécifiez l'administrateur local intégré sur le système sur lequel vous installez le plug-in SnapCenter. Vous pouvez spécifier un compte d'utilisateur local appartenant au groupe d'administrateurs locaux si le compte d'utilisateur dispose de privilèges élevés ou si la fonction de contrôle d'accès utilisateur est désactivée sur le système hôte. Le format valide du champ Nom d'utilisateur est : `UserName`





 a| 
Mot de passe
 a| 
Entrez le mot de passe utilisé pour l'authentification.



 a| 
Authentification
 a| 
Sélectionnez Windows comme mode d'authentification.

|===
. Cliquez sur *OK*.

