---
settings:
  name: SnapCenter Software 4.8
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  versions:
  - name: Logiciel SnapCenter
    url: "/snapcenter"
    version-number: '4.8'
  - name: Logiciel SnapCenter
    url: "/snapcenter-47"
    version-number: '4.7'
  - name: Logiciel SnapCenter
    url: "/snapcenter-46"
    version-number: '4.6'
  - name: Logiciel SnapCenter
    url: "/snapcenter-45"
    version-number: '4.5'
  langs: fr-fr,us-en,ja-jp,ko-kr,zh-cn,zh-tw,de-de,es-es
sidebar:
  entries:
  - title: Documentation relative au logiciel SnapCenter 4.8
    url: "/index.html"
  - title: Notes de mise à jour
    url: "/release-notes.html"
  - section: concept
  - section: install
  - section: protect-scsql
  - section: protect-hana
  - section: protect-sco
  - section: protect-scw
  - section: protect-sce
  - section: protect-scc
  - section: admin
  - section: upgrade
  - section: uninstall
  - section: sc-automation
  - title: Mentions légales
    url: "/legal-notices.html"
