---
permalink: protect-scw/task_create_a_storage_system_connection_and_a_credential_using_powershell_cmdlets_for_windows.html 
sidebar: sidebar 
keywords: credentials 
summary: 'Vous devez créer une connexion SVM (Storage Virtual machine) et une identifiant avant d"utiliser les applets de commande PowerShell pour réaliser les opérations de protection des données.' 
---
= Créer une connexion au système de stockage et une autorisation d'accès à l'aide des applets de commande PowerShell
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


Vous devez créer une connexion SVM (Storage Virtual machine) et une identifiant avant d'utiliser les applets de commande PowerShell pour réaliser les opérations de protection des données.

*Ce dont vous aurez besoin*

* Vous devez avoir préparé l'environnement PowerShell pour exécuter les applets de commande PowerShell.
* Pour créer des connexions de stockage, vous devez disposer des autorisations requises dans le rôle d'administrateur d'infrastructure.
* Vous devez vous assurer que les installations du plug-in ne sont pas en cours.
+
Les installations de plug-ins hôtes ne doivent pas être en cours d'ajout d'une connexion au système de stockage, car le cache hôte n'est pas nécessairement mis à jour et l'état des bases de données peut être affiché dans l'interface utilisateur graphique de SnapCenter sous la forme « non disponible pour la sauvegarde » ou « non sur le stockage NetApp ».

* Les noms des systèmes de stockage doivent être uniques.
+
SnapCenter ne prend pas en charge plusieurs systèmes de stockage portant le même nom sur des clusters différents. Chaque système de stockage pris en charge par SnapCenter doit disposer d'un nom unique et d'une adresse IP de LIF de gestion unique.



*Étapes*

. Lancez une session de connexion PowerShell à l'aide de la cmdlet Open-SmConnection.
+
Cet exemple ouvre une session PowerShell :

+
[listing]
----
PS C:\> Open-SmConnection
----
. Créez une nouvelle connexion au système de stockage à l'aide de l'applet de commande Add-SmStorageConnection.
+
Dans cet exemple, une nouvelle connexion au système de stockage est créée :

+
[listing]
----
PS C:\> Add-SmStorageConnection -Storage test_vs1 -Protocol Https
-Timeout 60
----
. Créez une nouvelle information d'identification à l'aide de l'applet de commande Add-SmCredential.
+
Cet exemple crée un nouvel identifiant nommé FinancieAdmin avec les informations d'identification Windows :

+
[listing]
----
PS C:> Add-SmCredential -Name FinanceAdmin -AuthMode Windows
-Credential sddev\administrator
----


Les informations relatives aux paramètres pouvant être utilisés avec la cmdlet et leurs descriptions peuvent être obtenues en exécutant _get-Help nom_commande_. Vous pouvez également vous reporter au https://library.netapp.com/ecm/ecm_download_file/ECMLP2883300["Guide de référence de l'applet de commande du logiciel SnapCenter"^].
