---
permalink: protect-scw/task_define_a_backup_strategy_for_windows_file_systems.html 
sidebar: sidebar 
keywords:  
summary: 'En définissant une stratégie de sauvegarde avant de créer vos sauvegardes, vous obtenez les sauvegardes dont vous avez besoin pour restaurer ou cloner vos systèmes de fichiers. Votre contrat de niveau de service (SLA), votre objectif de délai de restauration (RTO) et votre objectif de point de restauration (RPO) déterminent largement votre stratégie de sauvegarde.' 
---
= Définir une stratégie de sauvegarde pour les systèmes de fichiers Windows
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
En définissant une stratégie de sauvegarde avant de créer vos sauvegardes, vous obtenez les sauvegardes dont vous avez besoin pour restaurer ou cloner vos systèmes de fichiers. Votre contrat de niveau de service (SLA), votre objectif de délai de restauration (RTO) et votre objectif de point de restauration (RPO) déterminent largement votre stratégie de sauvegarde.

Un SLA définit le niveau de service attendu et traite de nombreux problèmes liés à la prestation, notamment la disponibilité et les performances du service. Le RTO est le moment par lequel un processus métier doit être restauré suite à une interruption de service. L'objectif RPO définit la stratégie selon laquelle les fichiers doivent être récupérés depuis le stockage de sauvegarde afin que les opérations régulières puissent reprendre après une défaillance. Les niveaux de service, RTO et RPO contribuent à la stratégie de protection des données.



== Planifications de sauvegarde pour les systèmes de fichiers Windows

La fréquence de sauvegarde est spécifiée dans les stratégies ; un planning de sauvegarde est spécifié dans la configuration du groupe de ressources. Le facteur le plus important dans la détermination d'une fréquence ou d'un planning de sauvegarde est le taux de changement pour la ressource et l'importance des données. Vous pouvez sauvegarder chaque heure une ressource largement utilisée et il vous est possible de sauvegarder une ressource peu utilisée une fois par jour. Parmi les autres facteurs figurent l'importance de la ressource pour votre organisation, votre contrat de niveau de service (SLA) et votre objectif de point de récupération (RPO).

Un SLA définit le niveau de service attendu et traite de nombreux problèmes liés au service, notamment la disponibilité et les performances de celui-ci. Un RPO définit la stratégie selon laquelle les fichiers doivent être récupérés à partir du stockage de sauvegarde afin que des opérations régulières puissent reprendre après une défaillance. Les SLA et RPO contribuent à la stratégie de protection des données.

Même avec une ressource largement utilisée, il n'est pas nécessaire d'exécuter une sauvegarde complète plus d'une fois ou deux fois par jour.

Les planifications de sauvegarde ont deux parties, comme suit :

* Fréquence des sauvegardes
+
La fréquence de sauvegarde (fréquence d'exécution des sauvegardes), appelée _schedule type_ pour certains plug-ins, fait partie d'une configuration de stratégie. Par exemple, vous pouvez configurer la fréquence de sauvegarde en tant qu'heures, quotidiennes, hebdomadaires ou mensuelles, ou vous pouvez spécifier *aucun* qui fait de la stratégie une stratégie à la demande uniquement. Vous pouvez accéder aux stratégies en cliquant sur *Paramètres* > *stratégies*.

* Planifications de sauvegarde
+
Les planifications de sauvegarde (exactement quand les sauvegardes doivent être effectuées) font partie d'une configuration de groupe de ressources. Par exemple, si un groupe de ressources dispose d'une stratégie configurée pour les sauvegardes hebdomadaires, vous pouvez configurer la planification pour sauvegarder chaque jeudi à 10 h 00. Vous pouvez accéder aux planifications de groupes de ressources en cliquant sur *Ressources* > *groupes de ressources*.





== Nombre de sauvegardes nécessaires pour les systèmes de fichiers Windows

Les facteurs déterminant le nombre de sauvegardes nécessaires incluent la taille du système de fichiers Windows, le nombre de volumes utilisés, le taux de changement du système de fichiers et votre contrat de niveau de service.



== convention de dénomination des sauvegardes pour les systèmes de fichiers Windows

Les sauvegardes du système de fichiers Windows utilisent la convention d'appellation des copies Snapshot par défaut. la convention de nommage des sauvegardes par défaut ajoute un horodatage aux noms de copie Snapshot qui vous aide à identifier le moment de la création des copies.

La copie snapshot utilise la convention de dénomination par défaut suivante : resourgroupe_nom_nom_hôte_horodatage

Vous devez nommer vos groupes de ressources de sauvegarde de manière logique, comme dans l'exemple suivant :

[listing]
----
dts1_mach1x88_03-12-2015_23.17.26
----
Dans cet exemple, les éléments de syntaxe ont la signification suivante :

* `dts1` est le nom du groupe de ressources.
* `mach1x88` est le nom d'hôte.
* `03-12-2016_23.17.26` est la date et l'horodatage.


Lors de la création d'une sauvegarde, vous pouvez également ajouter une balise descriptive pour vous aider à identifier la sauvegarde. En revanche, si vous souhaitez utiliser une convention de dénomination de sauvegarde personnalisée, vous devez renommer la sauvegarde une fois l'opération terminée.



== Options de conservation des sauvegardes

Vous pouvez choisir le nombre de jours pendant lesquels vous souhaitez conserver les copies de sauvegarde ou spécifier le nombre de copies de sauvegarde à conserver, dans un maximum de 255 copies ONTAP. Par exemple, votre entreprise peut avoir besoin de conserver 10 jours de copies de sauvegarde ou 130 copies de sauvegarde.

Lors de la création d'une stratégie, vous pouvez spécifier les options de rétention pour le type de sauvegarde et le type de planification.

Si vous configurez la réplication SnapMirror, la règle de conservation est mise en miroir sur le volume de destination.

SnapCenter supprime les sauvegardes conservées dont les étiquettes de conservation correspondent au type de planification. Si le type de planification a été modifié pour la ressource ou le groupe de ressources, les sauvegardes avec l'ancienne étiquette de type de planification peuvent rester sur le système.


NOTE: Pour la conservation à long terme des copies de sauvegarde, nous vous recommandons d'utiliser la sauvegarde SnapVault.
