---
permalink: protect-scw/task_clone_from_a_windows_file_system_backup.html 
sidebar: sidebar 
keywords: clone 
summary: Vous pouvez utiliser SnapCenter pour cloner une sauvegarde du système de fichiers Windows. Pour copier un fichier qui a été supprimé ou modifié par erreur, vous pouvez cloner une sauvegarde et accéder à ce fichier dans le clone. 
---
= Clonage à partir d'une sauvegarde du système de fichiers Windows
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez utiliser SnapCenter pour cloner une sauvegarde du système de fichiers Windows. Pour copier un fichier qui a été supprimé ou modifié par erreur, vous pouvez cloner une sauvegarde et accéder à ce fichier dans le clone.

*Ce dont vous aurez besoin*

* Vous devez être prêt à préparer la protection des données en effectuant des tâches telles que l'ajout d'hôtes, l'identification des ressources et la création de connexions de machines virtuelles de stockage (SVM).
* Vous devez avoir une sauvegarde du système de fichiers.
* Vous devez vous assurer que les agrégats hébergeant les volumes doivent se trouver dans la liste des agrégats attribués de la machine virtuelle de stockage (SVM).
* Vous ne pouvez pas cloner un groupe de ressources. Vous ne pouvez cloner que des sauvegardes de systèmes de fichiers individuels.
* Si une sauvegarde réside sur une machine virtuelle dotée d'un disque VMDK, SnapCenter ne peut pas cloner la sauvegarde sur un serveur physique.
* Si vous clonez un cluster Windows (par exemple une LUN partagée ou une LUN CSV (Cluster Shared volume), le clone est stocké en tant que LUN dédiée sur l'hôte que vous spécifiez.
* Pour une opération de clonage, le répertoire racine du point de montage du volume ne peut pas être un répertoire partagé.
* Le clone ne peut pas être créé sur un nœud qui n'est pas le home node de l'agrégat.
* Vous ne pouvez pas planifier d'opérations de clonage récurrentes (ou de cycle de vie des clones) pour les systèmes de fichiers Windows ; vous pouvez uniquement cloner une sauvegarde à la demande.
* Si vous déplacez une LUN contenant un clone vers un nouveau volume, SnapCenter ne peut plus prendre en charge le clone. Par exemple, vous ne pouvez pas utiliser SnapCenter pour supprimer le clone.
* Vous ne pouvez pas cloner des environnements. Par exemple, le clonage d'un disque physique vers un disque virtuel ou vice versa.


*À propos de cette tâche*

* Le CHEMIN_SCRIPTS est défini à l'aide de la clé pré-défini WindowsScriptsDirectory située dans le fichier SMCoreServiceHost.exe.Config de l'hôte du plug-in.
+
Si nécessaire, vous pouvez modifier ce chemin et redémarrer le service SMcore. Il est recommandé d'utiliser le chemin par défaut pour la sécurité.

+
La valeur de la clé peut être affichée à partir de Swagger via l'API : API /4.7/configsettings

+
Vous pouvez utiliser L'API GET pour afficher la valeur de la clé. L'API DÉFINIE n'est pas prise en charge.



*Étapes*

. Dans le volet de navigation de gauche, cliquez sur *Ressources*, puis sélectionnez le plug-in approprié dans la liste.
. Dans la page Ressources, sélectionnez *systèmes de fichiers* dans la liste.
. Sélectionnez l'hôte.
+
La vue topologique s'affiche automatiquement si la ressource est protégée.

. Dans la liste des ressources, sélectionnez la sauvegarde à cloner, puis cliquez sur l'icône cloner.
. Dans la page Options, procédez comme suit :
+
|===
| Pour ce champ... | Procédez comme ça... 


 a| 
Serveur clone
 a| 
Choisissez l'hôte sur lequel le clone doit être créé.



 a| 
« Attribuer automatiquement un point de montage » ou « attribuer automatiquement un point de montage de volume sous la trajectoire »
 a| 
Choisissez d'attribuer automatiquement un point de montage ou un point de montage de volume sous un chemin d'accès.

Affectation automatique d'un point de montage de volume sous le chemin : le point de montage sous un chemin vous permet de fournir un répertoire spécifique dans lequel les points de montage seront créés. Avant de choisir cette option, vous devez vérifier que le répertoire est vide. Si une sauvegarde est effectuée dans le répertoire, la sauvegarde sera dans un état non valide après l'opération de montage.



 a| 
Emplacement d'archivage
 a| 
Choisissez un emplacement d'archivage si vous procédez au clonage d'une sauvegarde secondaire.

|===
. Dans la page script, spécifiez les prescripteurs ou les postscripts que vous souhaitez exécuter.
+

NOTE: Le chemin prescripteurs ou postscripts ne doit pas inclure de disques ou de partages. Le chemin doit être relatif au CHEMIN_SCRIPTS.

. Vérifiez le résumé, puis cliquez sur *Terminer*.
. Surveillez la progression de l'opération en cliquant sur *moniteur* > *travaux*.

