---
permalink: upgrade/upgrade_snapcenter_server_linux.html 
sidebar: sidebar 
keywords: upgrade, upgrade snapcenter server, linux 
summary: 'Vous pouvez utiliser le fichier d"installation du serveur SnapCenter pour mettre à niveau le serveur SnapCenter.' 
---
= Mettez à niveau le serveur SnapCenter sur un hôte Linux
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez utiliser le fichier d'installation du serveur SnapCenter pour mettre à niveau le serveur SnapCenter.

*Étapes*

. Effectuez l'une des actions de mise à niveau du serveur SnapCenter.
+
|===
| Si vous souhaitez effectuer... | Procédez comme ça... 


 a| 
Mise à niveau non interactive
 a| 
`sudo ./snapcenter-linux-server-(el8/el9/sles15).bin -i silent -DUPGRADE=<value> -DINSTALL_LOG_NAME=<filename>`

Exemple : sudo ./snapcenter_linux_server.bin -i silent -DUPGRADE=1 -DINSTALL_LOG_NAME=InstallerLog.log

Les journaux seront stockés à _/var/opt/snapcenter/logs_.

Paramètres à transmettre pour la mise à niveau :

** DINSTALL_LOG_NAME : nom du fichier journal dans lequel les journaux d'installation seront stockés.
** DUPGRADE : la valeur par défaut est 0. Spécifiez ce paramètre et sa valeur comme tout entier autre que 0 pour mettre à niveau le serveur SnapCenter.




 a| 
Installation interactive
 a| 
`./snapcenter-linux-server-(el8/el9/sles15).bin`

Vous serez invité à confirmer la mise à niveau. Entrez une valeur autre que 0 pour confirmer la mise à niveau du serveur SnapCenter.

|===



NOTE: Vous devez vous déconnecter puis vous connecter à SnapCenter, ou fermer puis ouvrir un nouveau navigateur pour accéder à l'interface graphique de SnapCenter.
