---
permalink: protect-hana/concept_how_snapcenter_plug_in_for_sap_hana_database_uses_consistency_group_snapshot_copies.html 
sidebar: sidebar 
keywords: SnapCenter Plug-in for SAP HANA Database 
summary: 'Vous pouvez utiliser le plug-in pour créer des snapshots de groupe de ressources. Un groupe de cohérence est un conteneur qui peut héberger plusieurs volumes, de sorte que vous puissiez les gérer comme une entité unique. Un groupe de cohérence est constitué de copies Snapshot simultanées de plusieurs volumes, ce qui procure des copies cohérentes d"un groupe de volumes.' 
---
= Comment le plug-in SnapCenter pour SAP HANA Database utilise les snapshots de groupe de cohérence
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez utiliser le plug-in pour créer des snapshots de groupe de ressources. Un groupe de cohérence est un conteneur qui peut héberger plusieurs volumes, de sorte que vous puissiez les gérer comme une entité unique. Un groupe de cohérence est constitué de copies Snapshot simultanées de plusieurs volumes, ce qui procure des copies cohérentes d'un groupe de volumes.

Vous pouvez également spécifier le temps d'attente nécessaire au contrôleur de stockage pour regrouper les snapshots de manière cohérente. Les options de temps d'attente disponibles sont *urgent*, *Moyen* et *détendu*. Vous pouvez également activer ou désactiver la synchronisation WAFL (Write Anywhere File Layout) pendant le fonctionnement d'un snapshot de groupe cohérent. Le système WAFL Sync améliore les performances d'un snapshot de groupe de cohérence.
