---
permalink: protect-hana/reference_considerations_for_determining_backup_schedules_for_sap_hana_database.html 
sidebar: sidebar 
keywords: SnapCenter Plug-in for SAP HANA Database 
summary: 'Le facteur le plus important dans la détermination d"un planning de sauvegarde est le taux de modification de la ressource. Vous pouvez sauvegarder chaque heure une ressource largement utilisée et il vous est possible de sauvegarder une ressource peu utilisée une fois par jour. D"autres facteurs entrent en ligne de compte l"importance de la ressource pour votre entreprise, votre accord de niveau de service \(SLA\) et votre objectif de point de récupération \(RPO\).' 
---
= Considérations relatives à la détermination des planifications de sauvegarde pour les bases de données SAP HANA
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Le facteur le plus important dans la détermination d'un planning de sauvegarde est le taux de modification de la ressource. Vous pouvez sauvegarder chaque heure une ressource largement utilisée et il vous est possible de sauvegarder une ressource peu utilisée une fois par jour. D'autres facteurs entrent en ligne de compte l'importance des ressources pour votre entreprise, votre contrat de niveau de service et votre objectif de point de récupération (RPO).

Les planifications de sauvegarde ont deux parties, comme suit :

* Fréquence des sauvegardes (fréquence des sauvegardes)
+
La fréquence de sauvegarde, également appelée type de planification pour certains plug-ins, fait partie d'une configuration de règles. Par exemple, vous pouvez configurer la fréquence des sauvegardes sous forme horaire, quotidienne, hebdomadaire ou mensuelle.

* Planifications de sauvegardes (exactement quand les sauvegardes doivent être effectuées
+
Les planifications de sauvegarde font partie d'une configuration de ressource ou de groupe de ressources. Par exemple, si un groupe de ressources dispose d'une stratégie configurée pour les sauvegardes hebdomadaires, vous pouvez configurer la planification pour la sauvegarder tous les jeudis à 10 h 00


