---
permalink: protect-hana/reference_prerequisites_to_adding_hosts_and_installing_snapcenter_plug_in_for_sap_hana_database.html 
sidebar: sidebar 
keywords: credentials 
summary: 'Avant d"ajouter un hôte et d"installer les modules d"extension, vous devez remplir toutes les conditions requises. Le plug-in SnapCenter pour base de données SAP HANA est disponible dans les environnements Windows et Linux.' 
---
= Conditions préalables pour l'ajout d'hôtes et l'installation du plug-in SnapCenter pour la base de données SAP HANA
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Avant d'ajouter un hôte et d'installer les modules d'extension, vous devez remplir toutes les conditions requises. Le plug-in SnapCenter pour base de données SAP HANA est disponible dans les environnements Windows et Linux.

* Vous devez avoir installé Java 1.8 64 bits sur votre hôte.
+

NOTE: IBM Java n'est pas pris en charge.

* Vous devez avoir installé le terminal interactif de la base de données SAP HANA (client HDBSQL) sur l'hôte.
* Pour Windows, Plug-in Creator Service doit être en cours d'exécution à l'aide de l'utilisateur Windows « LocalSystem », ce qui est le comportement par défaut lorsque Plug-in pour SAP HANA Database est installé en tant qu'administrateur de domaine.
* Pour Windows, les clés de la boutique utilisateur doivent être créées en tant qu'utilisateur SYSTÈME.
* Lors de l'installation d'un plug-in sur un hôte Windows, si vous spécifiez un identifiant qui n'est pas intégré ou si l'utilisateur appartient à un utilisateur de groupe de travail local, vous devez désactiver l'UAC sur l'hôte. Le plug-in SnapCenter pour Microsoft Windows sera déployé par défaut avec le plug-in SAP HANA sur les hôtes Windows.
* Pour l'hôte Linux, les clés HDB Secure User Store sont accessibles en tant qu'utilisateur HDBSQL OS.
* Le serveur SnapCenter doit avoir accès au port 8145 ou personnalisé du plug-in pour l'hôte de base de données SAP HANA.




== Hôtes Windows

* Vous devez disposer d'un utilisateur de domaine disposant de privilèges d'administrateur local avec des autorisations de connexion locales sur l'hôte distant.
* Lors de l'installation du plug-in pour base de données SAP HANA sur un hôte Windows, le plug-in SnapCenter pour Microsoft Windows est installé automatiquement.
* Vous devez avoir activé la connexion SSH par mot de passe pour l'utilisateur root ou non-root.
* Vous devez avoir installé Java 1.8 64 bits sur votre hôte Windows.
+
http://www.java.com/en/download/manual.jsp["Téléchargements Java pour tous les systèmes d'exploitation"]

+
https://imt.netapp.com/matrix/imt.jsp?components=112393;&solution=1259&isHWU&src=IMT["Matrice d'interopérabilité NetApp"]





== Hôtes Linux

* Vous devez avoir activé la connexion SSH par mot de passe pour l'utilisateur root ou non-root.
* Vous devez avoir installé Java 1.8 64 bits sur votre hôte Linux.
+
http://www.java.com/en/download/manual.jsp["Téléchargements Java pour tous les systèmes d'exploitation"]

+
https://imt.netapp.com/matrix/imt.jsp?components=112393;&solution=1259&isHWU&src=IMT["Matrice d'interopérabilité NetApp"]

* Pour les bases de données SAP HANA qui s'exécutent sur un hôte Linux, lors de l'installation du plug-in pour base de données SAP HANA, le plug-in SnapCenter pour UNIX est installé automatiquement.
* Vous devez avoir *bash* comme shell par défaut pour l'installation du plug-in.




== Commandes supplémentaires

Pour exécuter une commande supplémentaire sur le plug-in SnapCenter pour SAP HANA, vous devez l'inclure dans le `allowed_commands.config` fichier.

`allowed_commands.config` Ce fichier se trouve dans le sous-répertoire « etc » du répertoire du plug-in SnapCenter pour SAP HANA.

.Hôtes Windows
Valeur par défaut : `C:\Program Files\NetApp\SnapCenter\HANA\etc\allowed_commands.config`

Chemin personnalisé : `<Custome_Directory>\NetApp\SnapCenter\HANA\etc\allowed_commands.config`
Hôte Windows :

.Hôtes Linux
Valeur par défaut : `/opt/NetApp/snapcenter/scc/etc/allowed_commands.config`

Chemin personnalisé : `<Custome_Directory>/NetApp/snapcenter/scc/etc/allowed_commands.config`

Pour autoriser des commandes supplémentaires sur l'hôte du plug-in, ouvrez `allowed_commands.config` fichier dans un éditeur. Entrez chaque commande sur une ligne distincte. Il n'est pas sensible à la casse.
Par exemple :

commande : mount

commande : umount

Assurez-vous de spécifier le chemin d'accès complet. Placez le chemin d'accès entre guillemets (") s'il contient des espaces.
Par exemple :

Commande : « C:\Program Files\NetApp\SnapCreator commands\sdcli.exe »

commande : myscript.bat

Si le `allowed_commands.config` le fichier n'est pas présent, les commandes ou l'exécution de script seront bloquées et le flux de travail échouera avec l'erreur suivante :

"[/mnt/mount -a] exécution non autorisée. Autoriser en ajoutant la commande dans le fichier %s sur l'hôte du plug-in. »

Si la commande ou le script n'est pas présent dans `allowed_commands.config`, l'exécution de la commande ou du script sera bloquée et le flux de travail échouera avec l'erreur suivante :

"[/mnt/mount -a] exécution non autorisée. Autoriser en ajoutant la commande dans le fichier %s sur l'hôte du plug-in. »


NOTE: Vous ne devez pas utiliser de caractère générique (*) pour autoriser toutes les commandes.
