---
permalink: protect-hana/reference_host_requirements_to_install_snapcenter_plug_in_package_for_linux.html 
sidebar: sidebar 
keywords: SnapCenter 
summary: 'Avant d"installer le module de plug-ins SnapCenter pour Linux, vous devez connaître certains besoins en espace système hôte de base et en dimensionnement.' 
---
= Configuration requise pour l'installation du module de plug-ins SnapCenter pour Linux
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Avant d'installer le module de plug-ins SnapCenter pour Linux, vous devez connaître certains besoins en espace système hôte de base et en dimensionnement.

|===
| Élément | De formation 


 a| 
Systèmes d'exploitation
 a| 
* Red Hat Enterprise Linux
* SUSE Linux Enterprise Server (SLES)


Pour obtenir les dernières informations sur les versions prises en charge, reportez-vous à la section https://imt.netapp.com/matrix/imt.jsp?components=103047;&solution=1257&isHWU&src=IMT["Matrice d'interopérabilité NetApp"].



 a| 
RAM minimale pour le plug-in SnapCenter sur l'hôte
 a| 
1 GO



 a| 
Espace minimal d'installation et de journalisation pour le plug-in SnapCenter sur l'hôte
 a| 
2 GO


NOTE: Vous devez allouer suffisamment d'espace disque et surveiller la consommation de stockage par le dossier des journaux. L'espace de journalisation requis varie en fonction du nombre d'entités à protéger et de la fréquence des opérations de protection des données. S'il n'y a pas suffisamment d'espace disque, les journaux ne seront pas créés pour les opérations récentes.



 a| 
Packs logiciels requis
 a| 
Java 1.8.x (64 bits)Java Oracle et OpenJDK Flavors

Si vous avez mis à niveau JAVA vers la dernière version, vous devez vous assurer que l'option JAVA_HOME située dans /var/opt/snapcenter/spl/etc/spl.properties est définie sur la version JAVA correcte et le chemin correct.

Pour obtenir les dernières informations sur les versions prises en charge, reportez-vous à la section https://imt.netapp.com/matrix/imt.jsp?components=103047;&solution=1257&isHWU&src=IMT["Matrice d'interopérabilité NetApp"].

|===