---
permalink: protect-hana/task_prepare_multitenant_database_containers_for_data_protection.html 
sidebar: sidebar 
keywords: multitenant database containers 
summary: 'Pour les hôtes SAP HANA directement enregistrés dans SnapCenter, l"installation ou la mise à niveau du plug-in SnapCenter pour base de données SAP HANA déclenchera une détection automatique des ressources sur l"hôte. Après l"installation ou la mise à niveau du plug-in, pour chaque conteneur de base de données multitenant \(MDC\) situé sur l"hôte du plug-in, une autre ressource MDC sera automatiquement découverte avec un format GUID différent et enregistrée dans SnapCenter. La nouvelle ressource sera à l"état "verrouillée".' 
---
= Préparez des conteneurs de bases de données mutualisés pour protéger les données
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Pour les hôtes SAP HANA directement enregistrés dans SnapCenter, l'installation ou la mise à niveau du plug-in SnapCenter pour base de données SAP HANA déclenchera une détection automatique des ressources sur l'hôte. Après l'installation ou la mise à niveau du plug-in, pour chaque ressource MDC (conteneur de base de données multitenant) située sur l'hôte du plug-in, une autre ressource MDC sera automatiquement découverte avec un format GUID différent et enregistrée dans SnapCenter. La nouvelle ressource sera à l'état « verrouillée ».

*À propos de cette tâche*

Par exemple, dans SnapCenter 4.2, si la ressource MDC E90 était située sur l'hôte du plug-in et enregistrée manuellement, après la mise à niveau vers SnapCenter 4.3, une autre ressource MDC E90 avec un GUID différent sera découverte et enregistrée dans SnapCenter.


NOTE: Les sauvegardes associées à la ressource de SnapCenter 4.2 et versions antérieures doivent être conservées jusqu'à l'expiration de la période de conservation. Après l'expiration de la période de conservation, vous pouvez supprimer l'ancienne ressource MDC et continuer à gérer la nouvelle ressource MDC découverte automatiquement.

`Old MDC resource` Est la ressource MDC pour un hôte de plug-in qui a été ajouté manuellement dans SnapCenter 4.2 ou une version antérieure.

Pour commencer à utiliser la nouvelle ressource découverte dans SnapCenter 4.3 pour les opérations de protection des données, procédez comme suit :

*Étapes*

. Dans la page Ressources, sélectionnez l'ancienne ressource MDC avec les sauvegardes ajoutées à la version précédente de SnapCenter, puis placez-la dans "mode de maintenance" à partir de la page topologie.
+
Si la ressource fait partie d'un groupe de ressources, placez le groupe de ressources dans "mode de provenance".

. Configurez la nouvelle ressource MDC découverte après la mise à niveau vers SnapCenter 4.3 en sélectionnant la nouvelle ressource dans la page Ressources.
+
« Nouvelle ressource MDC » est la nouvelle ressource MDC découverte une fois le serveur SnapCenter et l'hôte du plug-in mis à niveau vers 4.3. La nouvelle ressource MDC peut être identifiée comme une ressource avec le même SID que l'ancienne ressource MDC, pour un hôte donné, et avec une icône de cadenas rouge à côté de celle-ci dans la page Ressources.

. Protégez la nouvelle ressource MDC détectée après la mise à niveau vers SnapCenter 4.3 en sélectionnant des stratégies de protection, des plannings et des paramètres de notification.
. Supprimez les sauvegardes effectuées dans SnapCenter 4.2 ou les versions antérieures en fonction des paramètres de conservation.
. Supprimez le groupe de ressources de la page topologie.
. Supprimez l'ancienne ressource MDC de la page Ressources.
+
Par exemple, si la période de conservation des copies Snapshot primaires est de 7 jours et que la conservation des copies Snapshot secondaires est de 45 jours, après 45 jours et après la suppression de toutes les sauvegardes, vous devez supprimer le groupe de ressources et l'ancienne ressource MDC.



*Plus d'informations*

link:task_configure_hdb_user_store_key_and_hdbsql_os_user_for_the_sap_hana_database.html["Configurez la clé HDB User Store et l'utilisateur HDBSQL OS pour la base de données SAP HANA"]

link:task_view_sap_hana_database_backups_and_clones_in_the_topology_page_sap_hana.html["Affichez les sauvegardes et les clones des bases de données SAP HANA sur la page topologie"]
