---
permalink: protect-hana/task_restore_sap_hana_database_using_powershell_cmdlets.html 
sidebar: sidebar 
keywords: restore 
summary: 'La restauration d"une sauvegarde de base de données SAP HANA inclut le lancement d"une session de connexion avec le serveur SnapCenter, la liste des sauvegardes, la récupération des informations de sauvegarde et la restauration d"une sauvegarde.' 
---
= Restaurer la base de données SAP HANA à l'aide des applets de commande PowerShell
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La restauration d'une sauvegarde de base de données SAP HANA inclut le lancement d'une session de connexion avec le serveur SnapCenter, la liste des sauvegardes, la récupération des informations de sauvegarde et la restauration d'une sauvegarde.

*Ce dont vous aurez besoin*

Vous devez avoir préparé l'environnement PowerShell pour exécuter les applets de commande PowerShell.

*Étapes*

. Lancez une session de connexion avec le serveur SnapCenter pour un utilisateur spécifié à l'aide de l'applet de commande Open-SmConnection.
+
[listing]
----
Open-smconnection  -SMSbaseurl  https:\\snapctr.demo.netapp.com:8146/
----
. Identifiez la sauvegarde que vous souhaitez restaurer à l'aide des applets de commande Get-SmBackup and get-SmBackupReport.
+
Cet exemple montre que deux sauvegardes sont disponibles pour la restauration :

+
[listing]
----
 PS C:\> Get-SmBackup

        BackupId    BackupName                    BackupTime            BackupType
        --------    ----------                    ----------            ----------
         1          Payroll Dataset_vise-f6_08... 8/4/2015 11:02:32 AM  Full Backup
         2          Payroll Dataset_vise-f6_08... 8/4/2015 11:23:17 AM
----
+
Cet exemple contient des informations détaillées sur la sauvegarde du 29 janvier 2015 au 3 février 2015 :

+
[listing]
----
PS C:\> Get-SmBackupReport -FromDateTime "1/29/2015" -ToDateTime "2/3/2015"

SmBackupId           : 113
   SmJobId              : 2032
   StartDateTime        : 2/2/2015 6:57:03 AM
   EndDateTime          : 2/2/2015 6:57:11 AM
   Duration             : 00:00:07.3060000
   CreatedDateTime      : 2/2/2015 6:57:23 AM
   Status               : Completed
   ProtectionGroupName  : Clone
   SmProtectionGroupId  : 34
   PolicyName           : Vault
   SmPolicyId           : 18
   BackupName           : Clone_SCSPR0019366001_02-02-2015_06.57.08
   VerificationStatus   : NotVerified

   SmBackupId           : 114
   SmJobId              : 2183
   StartDateTime        : 2/2/2015 1:02:41 PM
   EndDateTime          : 2/2/2015 1:02:38 PM
   Duration             : -00:00:03.2300000
   CreatedDateTime      : 2/2/2015 1:02:53 PM
   Status               : Completed
   ProtectionGroupName  : Clone
   SmProtectionGroupId  : 34
   PolicyName           : Vault
   SmPolicyId           : 18
   BackupName           : Clone_SCSPR0019366001_02-02-2015_13.02.45
   VerificationStatus   : NotVerified
----
. Démarrez le processus de restauration dans le studio HANA.
+
La base de données est arrêtée.

. Restaurez les données de la sauvegarde à l'aide de la cmdlet Restore-SmBackup.
+

NOTE: AppObjectId est « Host\Plugin\UID », où UID = SID est pour une ressource de type conteneur unique et UID = MDC\SID est pour une ressource de conteneurs multiples. Vous pouvez obtenir ResourceID à partir de l'applet de commande Get-smResources.

+
[listing]
----
Get-smResources  -HostName cn24.sccore.test.com  -PluginCode HANA
----
+
Cet exemple montre comment restaurer la base de données à partir du stockage primaire :

+
[listing]
----
Restore-SmBackup -PluginCode HANA -AppObjectId cn24.sccore.test.com\hana\H10 -BackupId 3
----
+
Cet exemple montre comment restaurer la base de données à partir du stockage secondaire :

+
[listing]
----
Restore-SmBackup -PluginCode 'HANA' -AppObjectId cn24.sccore.test.com\hana\H10 -BackupId 399 -Confirm:$false  -Archive @( @{"Primary"="<Primary Vserver>:<PrimaryVolume>";"Secondary"="<Secondary Vserver>:<SecondaryVolume>"})
----
+
Les sauvegardes seront disponibles dans HANA Studio à des fins de restauration.



Les informations relatives aux paramètres pouvant être utilisés avec la cmdlet et leurs descriptions peuvent être obtenues en exécutant _get-Help nom_commande_. Vous pouvez également vous reporter au https://library.netapp.com/ecm/ecm_download_file/ECMLP2883300["Guide de référence de l'applet de commande du logiciel SnapCenter"^].
