---
permalink: protect-hana/task_install_the_snapcenter_plug_in_for_sap_hana_database_on_linux_hosts_using_the_command_line_interface.html 
sidebar: sidebar 
keywords:  
summary: 'Vous devez installer le plug-in SnapCenter pour la base de données SAP HANA à l"aide de l"interface utilisateur de SnapCenter. Si votre environnement n"autorise pas l"installation à distance du plug-in à partir de l"interface utilisateur SnapCenter, vous pouvez installer le plug-in pour base de données SAP HANA en mode console ou en mode silencieux à l"aide de l"interface de ligne de commandes \(CLI\).' 
---
= Installez le plug-in SnapCenter pour SAP HANA Database sur des hôtes Linux à l'aide de l'interface de ligne de commandes
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous devez installer le plug-in SnapCenter pour la base de données SAP HANA à l'aide de l'interface utilisateur de SnapCenter. Si votre environnement n'autorise pas l'installation à distance du plug-in à partir de l'interface utilisateur SnapCenter, vous pouvez installer le plug-in pour base de données SAP HANA en mode console ou en mode silencieux à l'aide de l'interface de ligne de commandes.

*Ce dont vous aurez besoin*

* Vous devez installer le plug-in pour la base de données SAP HANA sur chacun des hôtes Linux sur lesquels réside le client HDBSQL.
* L'hôte Linux sur lequel vous installez le plug-in SnapCenter pour la base de données SAP HANA doit répondre aux exigences des logiciels, bases de données et systèmes d'exploitation qui en dépendent.
+
La matrice d'interopérabilité (IMT) contient les dernières informations sur les configurations prises en charge.

+
https://imt.netapp.com/matrix/imt.jsp?components=105284;&solution=1259&isHWU&src=IMT["Matrice d'interopérabilité NetApp"]

* Le plug-in SnapCenter pour base de données SAP HANA fait partie du package de plug-ins SnapCenter pour Linux. Avant d'installer SnapCenter Plug-ins Package pour Linux, vous devez avoir déjà installé SnapCenter sur un hôte Windows.


*Étapes*

. Copiez le fichier d'installation du package de plug-ins SnapCenter pour Linux (snapcenter_linux_host_plugin.bin) depuis C:\ProgramData\NetApp\SnapCenter\Package Repository vers l'hôte où vous souhaitez installer le plug-in pour la base de données SAP HANA.
+
Vous pouvez accéder à ce chemin à partir de l'hôte sur lequel le serveur SnapCenter est installé.

. À partir de l'invite de commande, accédez au répertoire dans lequel vous avez copié le fichier d'installation.
. Installez le plug-in : `path_to_installation_bin_file/snapcenter_linux_host_plugin.bin -i silent -DPORT=port_number_for_host -DSERVER_IP=server_name_or_ip_address -DSERVER_HTTPS_PORT=port_number_for_server`
+
** -DPORT spécifie le port de communication SMCore HTTPS.
** -DSERVER_IP spécifie l'adresse IP du serveur SnapCenter.
** -DSERVER_HTTPS_PORT spécifie le port HTTPS du serveur SnapCenter.
** -DUSER_INSTALL_DIR indique le répertoire dans lequel vous souhaitez installer le module de plug-ins SnapCenter pour Linux.
** DINSTALL_LOG_NAME indique le nom du fichier journal.


+
[listing]
----
/tmp/sc-plugin-installer/snapcenter_linux_host_plugin.bin -i silent  -DPORT=8145 -DSERVER_IP=scserver.domain.com -DSERVER_HTTPS_PORT=8146 -DUSER_INSTALL_DIR=/opt -DINSTALL_LOG_NAME=SnapCenter_Linux_Host_Plugin_Install_2.log -DCHOSEN_FEATURE_LIST=CUSTOM
----
. Modifiez le fichier /<répertoire d'installation>/NetApp/snapcenter/scc/etc/SC_SMS_Services.properties, puis ajoutez le paramètre PLUGINS_ENABLED = hana:3.0.
. Ajoutez l'hôte au serveur SnapCenter à l'aide de l'applet de commande Add-Smhost et des paramètres requis.
+
Les informations relatives aux paramètres pouvant être utilisés avec la commande et leurs descriptions peuvent être obtenues en exécutant _get-Help nom_commande_. Vous pouvez également vous reporter au https://library.netapp.com/ecm/ecm_download_file/ECMLP2883300["Guide de référence de l'applet de commande du logiciel SnapCenter"^].


