---
permalink: protect-scc/concept_how_resources_resource_groups_and_policies_are_used_for_protecting_custom_plug_in_resources.html 
sidebar: sidebar 
keywords:  
summary: 'Avant d"utiliser SnapCenter, il est utile de maîtriser les concepts de base associés aux opérations de sauvegarde, de clonage et de restauration que vous souhaitez effectuer. Vous interagissez avec les ressources, les groupes de ressources et les stratégies pour différentes opérations.' 
---
= Utilisation des ressources, des groupes de ressources et des stratégies pour protéger les ressources personnalisées des plug-ins
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Avant d'utiliser SnapCenter, il est utile de maîtriser les concepts de base associés aux opérations de sauvegarde, de clonage et de restauration que vous souhaitez effectuer. Vous interagissez avec les ressources, les groupes de ressources et les stratégies pour différentes opérations.

* Les ressources sont généralement des bases de données, des systèmes de fichiers Windows ou des machines virtuelles que vous sauvegardez ou clonez avec SnapCenter.
* Un groupe de ressources SnapCenter est un ensemble de ressources sur un hôte ou un cluster.
+
Lorsque vous effectuez une opération sur un groupe de ressources, vous effectuez cette opération sur les ressources définies dans le groupe de ressources en fonction du planning que vous spécifiez pour le groupe de ressources.

+
Vous pouvez sauvegarder à la demande une seule ressource ou un groupe de ressources. Vous pouvez également effectuer des sauvegardes planifiées pour des ressources et des groupes de ressources uniques.

* Ces règles précisent la fréquence des sauvegardes, la conservation des copies, la réplication, les scripts et d'autres caractéristiques des opérations de protection des données.
+
Lorsque vous créez un groupe de ressources, vous sélectionnez une ou plusieurs stratégies pour ce groupe. Vous pouvez également sélectionner une stratégie lorsque vous effectuez une sauvegarde à la demande pour une seule ressource.



Pensez à un groupe de ressources comme définissant _quoi_ vous voulez protéger et quand vous voulez le protéger en termes de jour et de temps. Pensez à une stratégie comme définir _comment_ vous voulez la protéger. Si vous sauvegardez toutes les bases de données ou que vous sauvegardez tous les systèmes de fichiers d'un hôte, par exemple, vous pouvez créer un groupe de ressources qui inclut toutes les bases de données ou tous les systèmes de fichiers de l'hôte. Vous pouvez ensuite associer deux stratégies au groupe de ressources : une stratégie quotidienne et une stratégie horaire. Lorsque vous créez le groupe de ressources et joignez les stratégies, vous pouvez configurer le groupe de ressources de manière à effectuer une sauvegarde quotidienne basée sur les fichiers et un autre programme qui effectue une sauvegarde horaire basée sur les copies Snapshot.
