---
permalink: protect-scc/snapcenter_custom_plug_ins_overview.html 
sidebar: sidebar 
keywords: custom plug-ins 
summary: 'Vous pouvez développer des plug-ins personnalisés pour les applications que vous utilisez, puis utiliser SnapCenter pour la sauvegarde, la restauration ou le clonage de ces applications. Comme d"autres plug-ins SnapCenter, vos plug-ins personnalisés font office de composants côté hôte du logiciel NetApp SnapCenter, permettant ainsi de protéger et de gérer les données intégrant la cohérence applicative.' 
---
= Présentation des plug-ins personnalisés SnapCenter
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez développer des plug-ins personnalisés pour les applications que vous utilisez, puis utiliser SnapCenter pour la sauvegarde, la restauration ou le clonage de ces applications. Vos plug-ins personnalisés font office de composants côté hôte du logiciel NetApp SnapCenter, ce qui permet une protection des données compatible avec les applications et une gestion des ressources.

Lorsque des plug-ins personnalisés sont installés, vous pouvez utiliser SnapCenter avec la technologie NetApp SnapMirror pour créer des copies miroir de jeux de sauvegarde sur un autre volume et utiliser la technologie NetApp SnapVault pour effectuer une réplication de sauvegarde disque à disque. Les plug-ins personnalisés peuvent être utilisés dans les environnements Windows et Linux.


NOTE: SnapCenter CLI ne prend pas en charge les commandes de plug-ins personnalisés.

Vous pouvez installer le plug-in personnalisé à partir de la page Ajouter un hôte.

link:add_hosts_and_install_plug_in_packages_on_remote_hosts.html["Ajoutez des hôtes et installez des modules plug-ins sur des hôtes distants."^]


NOTE: La politique de support de SnapCenter prendra en charge le framework personnalisé de SnapCenter, le moteur principal et les API associées. Le support ne couvre pas le code source du plug-in et les scripts associés basés sur le framework personnalisé du plug-in.

Vous pouvez créer vos propres plug-ins personnalisés en vous reportant au link:develop_a_plug_in_for_your_application.html["Développez un plug-in pour votre application"^] guide.
