---
permalink: protect-azure/create-azure-credential.html 
sidebar: sidebar 
keywords: snapcenter, azure, azure credential 
summary: 'Créez les informations d"identification Azure dans SnapCenter pour accéder au compte Azure NetApp.' 
---
= Créez les informations d'identification Azure dans SnapCenter
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous devez créer les identifiants Azure dans SnapCenter pour accéder au compte Azure NetApp.

.Avant de commencer
* Vérifiez que vous avez créé le principal de service dans Azure.
* Assurez-vous que vous disposez de l'ID locataire, de l'ID client et de la clé secrète associés à l'entité de service.
+
** L'ID de locataire est disponible sur le portail Azure sur la page de présentation de l'identifiant Entra.
** L'ID client est également connu sous le nom d'ID de l'application pour le principal d'application/de service d'entreprise. Vous trouverez ces informations sur le portail Azure sur la page de présentation de l'application d'entreprise que vous avez créée pour agir en tant que responsable de service pour SnapCenter.
** La clé secrète du client est également appelée valeur secrète. Vous pouvez créer ce secret de client dans le portail Azure en accédant à *enregistrements d'applications* sous Entra ID. Après avoir sélectionné l'application Enterprise que vous avez créée, accédez à *certificats et secrets*, puis à *Nouveau secret client*.
+

NOTE: La valeur secrète est uniquement accessible lors de sa création. Vous ne pouvez pas y accéder ultérieurement.

** Le responsable de service doit obtenir des autorisations. Le rôle de Contributor permettra au principal de service d'effectuer les actions requises dans Azure. Ceci peut être accordé à partir de la page contrôle d'accès (IAM) de la page abonnement.




.Étapes
. Dans le volet de navigation de gauche, cliquez sur *Paramètres*.
. Dans la page Paramètres, cliquez sur *Credential*.
. Cliquez sur *Nouveau*.
. Dans la page informations d'identification, spécifiez les informations suivantes requises pour créer les informations d'identification.
+
|===
| Pour ce champ... | Procédez comme ça... 


 a| 
Nom des informations d'identification
 a| 
Entrez un nom pour l'identifiant.



 a| 
Mode d'authentification
 a| 
Sélectionnez *Azure Credential* dans la liste déroulante.



 a| 
ID locataire
 a| 
Entrez l'ID du locataire.



 a| 
ID client
 a| 
Entrez l'ID client.



 a| 
Clé secrète du client
 a| 
Entrez la clé secrète du client.

|===
. Cliquez sur *OK*.

