---
permalink: protect-azure/create-backup-policies-sql.html 
sidebar: sidebar 
keywords: create policies, sql, backup policies 
summary: Créez une stratégie de sauvegarde pour le groupe de ressources ou de ressources que vous souhaitez sauvegarder. 
---
= Créer des stratégies de sauvegarde pour les bases de données SQL Server
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez créer une stratégie de sauvegarde pour la ressource ou le groupe de ressources avant d'utiliser SnapCenter pour sauvegarder les ressources SQL Server, ou vous pouvez créer une stratégie de sauvegarde au moment où vous créez un groupe de ressources ou sauvegardez une seule ressource.

.Étapes
. Dans le volet de navigation de gauche, cliquez sur *Paramètres*.
. Dans la page Paramètres, cliquez sur *stratégies*.
. Cliquez sur *Nouveau*.
. Dans la page Nom, entrez le nom et la description de la stratégie.
. Dans la page Paramètres, effectuez les opérations suivantes :
+
.. Sélectionnez le type de sauvegarde.
+
... Sélectionnez *sauvegarde complète et sauvegarde du journal* si vous souhaitez sauvegarder les fichiers de base de données et les journaux de transactions.
... Sélectionnez *sauvegarde complète* si vous souhaitez sauvegarder uniquement les fichiers de base de données.
... Sélectionnez *Log Backup* si vous souhaitez sauvegarder uniquement les journaux de transactions.
... Sélectionnez *Copier uniquement la sauvegarde* si vous souhaitez sauvegarder vos ressources à l'aide d'une autre application.


.. Dans la section Paramètres du groupe de disponibilité, effectuez les opérations suivantes :
+
... Sélectionnez Sauvegarder sur la réplique de sauvegarde préférée si vous souhaitez sauvegarder uniquement sur la réplique.
... Sélectionnez le réplica GA principal ou le réplica GA secondaire pour la sauvegarde.
... Sélectionnez la priorité de sauvegarde.


.. Spécifiez le type de planification.


. Dans la page Retention, en fonction du type de sauvegarde sélectionné, spécifiez les paramètres de rétention.
+

NOTE: La réplication vers un stockage secondaire n'est pas prise en charge.

. Dans la page Vérification, effectuez les opérations suivantes :
+
.. Dans la section Exécuter la vérification pour les programmes de sauvegarde suivants, sélectionnez la fréquence de planification.
.. Dans la section Options de vérification de cohérence de la base de données, effectuez les opérations suivantes :
+
... Sélectionnez *Limit the Integrity structure to Physical structure of the database (PHYSICAL_ONLY)* (limiter la vérification de l'intégrité à la structure physique de la base de données) et pour détecter les pages déchirées, les échecs de somme de contrôle et les défaillances matérielles courantes qui affectent la base de données.
... Sélectionnez *Supprimer tous les messages d'information (NO_INFOMSGS)* pour supprimer tous les messages d'information.
+
Sélectionné par défaut.

... Sélectionnez *Afficher tous les messages d'erreur signalés par objet (ALL_ERRORMSGS)* pour afficher toutes les erreurs signalées par objet.
... Sélectionnez *ne pas cocher les index non clusterisés (REGROUPÉS EN CLUSTERS)* si vous ne souhaitez pas vérifier les index non clusterisés.
+
La base de données SQL Server utilise le vérificateur de cohérence de base de données Microsoft SQL Server (DBCC) pour vérifier l'intégrité logique et physique des objets de la base de données.

... Sélectionnez *limiter les vérifications et obtenir les verrous au lieu d'utiliser une copie Snapshot de base de données interne (TABLOCK)* pour limiter les vérifications et obtenir des verrous au lieu d'utiliser un instantané de base de données interne.


.. Dans la section *Log Backup*, sélectionnez *Verify log backup upon terminés* pour vérifier la sauvegarde du journal à la fin de l'opération.
.. Dans la section *Paramètres du script de vérification*, entrez le chemin d'accès et les arguments du prescripteur ou du PostScript qui doivent être exécutés avant ou après l'opération de vérification, respectivement.


. Vérifiez le résumé et cliquez sur *Terminer*.

