---
permalink: protect-azure/create-azure-credential.html 
sidebar: sidebar 
keywords: snapcenter, azure, azure credential 
summary: 'Créez les informations d"identification Azure dans SnapCenter pour accéder au compte Azure NetApp.' 
---
= Créez les informations d'identification Azure dans SnapCenter
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous devez créer les identifiants Azure dans SnapCenter pour accéder au compte Azure NetApp.

Avant de créer les informations d'identification Azure, assurez-vous d'avoir créé le principal de service dans Azure. L'ID de locataire, l'ID client et la clé secrète associés au principal de service seront requis pour créer les informations d'identification Azure.

.Étapes
. Dans le volet de navigation de gauche, cliquez sur *Paramètres*.
. Dans la page Paramètres, cliquez sur *Credential*.
. Cliquez sur *Nouveau*.
. Dans la page informations d'identification, spécifiez les informations suivantes requises pour créer les informations d'identification.
+
|===
| Pour ce champ... | Procédez comme ça... 


 a| 
Nom des informations d'identification
 a| 
Entrez un nom pour l'identifiant.



 a| 
Mode d'authentification
 a| 
Sélectionnez *Azure Credential* dans la liste déroulante.



 a| 
ID locataire
 a| 
Entrez l'ID du locataire.



 a| 
ID client
 a| 
Entrez l'ID client.



 a| 
Clé secrète du client
 a| 
Entrez la clé secrète du client.

|===
. Cliquez sur *OK*.

