---
permalink: protect-azure/create-credential-add-plugin-host.html 
sidebar: sidebar 
keywords: snapcenter, azure, credential, plug-in host 
summary: 'Créez les informations d"identification pour ajouter l"hôte du plug-in.' 
---
= Créez les informations d'identification pour ajouter l'hôte du plug-in
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenter utilise des identifiants pour authentifier les utilisateurs pour les opérations SnapCenter.

Vous devez créer des informations d'identification pour l'installation des plug-ins SnapCenter et des informations d'identification supplémentaires pour les opérations de protection des données.

.Étapes
. Dans le volet de navigation de gauche, cliquez sur *Paramètres*.
. Dans la page Paramètres, cliquez sur *Credential*.
. Cliquez sur *Nouveau*.
. Dans la page informations d'identification, spécifiez les informations suivantes requises pour créer les informations d'identification.
+
|===
| Pour ce champ... | Procédez comme ça... 


 a| 
Nom des informations d'identification
 a| 
Entrez un nom pour l'identifiant.



 a| 
Mode d'authentification
 a| 
Sélectionnez le mode d'authentification dans la liste déroulante.



 a| 
Type d'authentification
 a| 
Sélectionnez *Mot de passe* ou *clé SSH* (uniquement pour l'hôte Linux).



 a| 
Nom d'utilisateur
 a| 
Spécifiez le nom d'utilisateur.



 a| 
Mot de passe
 a| 
Si vous avez sélectionné authentification par mot de passe, spécifiez le mot de passe.



 a| 
Clé privée SSH
 a| 
Si vous avez sélectionné l'authentification basée sur une clé SSH, spécifiez la clé privée.



 a| 
Utilisez les privilèges sudo
 a| 
Cochez la case utiliser les privilèges sudo si vous créez des informations d'identification pour un utilisateur non root.


NOTE: Ceci s'applique uniquement aux utilisateurs de Linux.

|===
. Cliquez sur *OK*.

