---
permalink: protect-azure/protect-applications-azure-netapp-files.html 
sidebar: sidebar 
keywords: azure netapp files, ANF, back up, restore, clone, ANF backup, Azure Blob storage 
summary: 'Vous pouvez sauvegarder, restaurer et cloner les applications s"exécutant sur Azure NetApp Files.' 
---
= Protégez les applications exécutées sur Azure NetApp Files
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenter prend en charge la protection de vos applications telles qu'Oracle, SQL et SAP HANA résidant sur Azure NetApp Files. Depuis la version 6.0.1, SnapCenter prend en charge la fonction de sauvegarde Azure NetApp Files qui étend les fonctionnalités de protection des données d'Azure NetApp Files en fournissant une solution de sauvegarde entièrement gérée pour la restauration, l'archivage et la conformité à long terme.

Azure NetApp Files est une solution de stockage premium qui peut s'avérer coûteuse pour la conservation à long terme des sauvegardes. Pour optimiser les coûts, vous pouvez déplacer les sauvegardes du stockage Azure NetApp Files vers un magasin d'objets Azure. Depuis la version SnapCenter 6.0.1, vous pouvez sauvegarder et cloner les applications résidant sur Azure NetApp Files vers Azure Blob Storage (magasin d'objets). Vous pouvez conserver deux copies de vos données, des copies Snapshot de volume sur un système de stockage Azure NetApp Files pour une restauration à court terme et une autre copie sur Azure Blob Storage pour une restauration à long terme.

Lorsqu'une règle avec sauvegarde Azure NetApp Files est activée et associée à une ressource, SnapCenter gère la création de snapshots de volume et la sauvegarde dans Azure Blob Storage. SnapCenter crée le coffre-fort de sauvegarde et active la sauvegarde pour le volume. Si vous avez activé la sauvegarde pour le volume, SnapCenter utilise le coffre-fort existant.



== Limites

* Les fonctionnalités de stockage objet pour les systèmes de stockage FAS ou AFF ONTAP et FSxN ne sont pas prises en charge.
* Les workflows de montage et de catalogue Oracle et SAP HANA ne sont pas pris en charge pour les sauvegardes de stockage objet, mais pour les copies Snapshot.
* Les clones PDB Oracle ne sont pas pris en charge pour les sauvegardes de stockage objet, mais pour les snapshots.
* La vérification des sauvegardes à partir du stockage objet, la prise en charge de l'API REST, la gestion du cycle de vie des clones à partir du stockage objet et les fonctionnalités de reporting pour les sauvegardes de stockage objet ne sont pas prises en charge.
* La restauration à partir de sauvegardes du stockage Azure Blob Storage vers Azure NetApp Files n'est pas prise en charge. Vous pouvez également utiliser l'option de clonage.
* La répartition des clones n'est pas prise en charge.

