---
permalink: admin/concept_what_operations_can_be_performed_from_the_resource_page.html 
sidebar: sidebar 
keywords:  
summary: Pour découvrir les ressources et exécuter les opérations de protection des données, consultez la page Ressources. Les opérations que vous pouvez effectuer diffèrent en fonction du plug-in que vous utilisez pour gérer vos ressources. 
---
= Opérations prises en charge à partir de la page Ressources
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Pour découvrir les ressources et exécuter les opérations de protection des données, consultez la page Ressources. Les opérations que vous pouvez effectuer diffèrent en fonction du plug-in que vous utilisez pour gérer vos ressources.

À partir de la page Ressources, vous pouvez effectuer les tâches suivantes :

|===
| Vous pouvez effectuer ces tâches... | Pour Microsoft Exchange Server | Pour Microsoft SQL Server | Pour Microsoft Windows | Pour Oracle Database | Pour les bases de données SAP HANA | Pour les plug-ins personnalisés 


 a| 
Déterminer si des ressources sont disponibles pour les sauvegardes
 a| 
Oui.
 a| 
Oui.
 a| 
Oui.
 a| 
Oui.
 a| 
Oui.
 a| 
Oui.



 a| 
Sauvegarde à la demande d'une ressource
 a| 
Oui.
 a| 
Oui.
 a| 
Oui.
 a| 
Oui.
 a| 
Oui.
 a| 
Oui.



 a| 
Effectuez des restaurations à partir des sauvegardes
 a| 
Oui.
 a| 
Oui.
 a| 
Oui.
 a| 
Oui.
 a| 
Oui.
 a| 
Oui.



 a| 
Sauvegardes clones
 a| 
Non
 a| 
Oui.
 a| 
Oui.
 a| 
Oui.
 a| 
Oui.
 a| 
Oui.



 a| 
Gérer les sauvegardes
 a| 
Oui.
 a| 
Oui.
 a| 
Oui.
 a| 
Oui.
 a| 
Oui.
 a| 
Oui.



 a| 
Gérer les clones
 a| 
Non
 a| 
Oui.
 a| 
Oui.
 a| 
Oui.
 a| 
Oui.
 a| 
Oui.



 a| 
Gestion des règles
 a| 
Oui.
 a| 
Oui.
 a| 
Oui.
 a| 
Oui.
 a| 
Oui.
 a| 
Oui.



 a| 
Gérer les connexions de stockage
 a| 
Oui.
 a| 
Oui.
 a| 
Oui.
 a| 
Oui.
 a| 
Oui.
 a| 
Oui.



 a| 
Montez les sauvegardes
 a| 
Non
 a| 
Non
 a| 
Non
 a| 
Oui.
 a| 
Non
 a| 
Non



 a| 
Démonter les sauvegardes
 a| 
Non
 a| 
Non
 a| 
Non
 a| 
Oui.
 a| 
Non
 a| 
Non



 a| 
Afficher les détails
 a| 
Oui.
 a| 
Oui.
 a| 
Oui.
 a| 
Oui.
 a| 
Oui.
 a| 
Oui.

|===