---
permalink: install/concept_snapcenter_licenses.html 
sidebar: sidebar 
keywords: licenses, FAS, AFF, ASA, SnapMirror, SnapVault, SnapRestore, FlexClone, SMBR, Single Mailbox Recovery 
summary: SnapCenter nécessite plusieurs licences pour permettre les opérations de protection des données. Le type de licence SnapCenter que vous installez dépend de votre environnement de stockage et des fonctionnalités que vous souhaitez utiliser. 
---
= Licences SnapCenter
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenter nécessite plusieurs licences pour permettre la protection des données des applications, des bases de données, des systèmes de fichiers et des machines virtuelles. Le type de licence SnapCenter que vous installez dépend de votre environnement de stockage et des fonctionnalités que vous souhaitez utiliser.

|===
| Licence | Si nécessaire 


 a| 
Contrôleur SnapCenter standard
 a| 
Requis pour les baies FAS, AFF et ASA

La licence standard SnapCenter est basée sur le contrôleur et est incluse dans ONTAP One. Si vous disposez de la licence SnapManager Suite, vous bénéficiez également des droits de licence SnapCenter Standard. Si vous souhaitez installer SnapCenter en version d'essai avec un système de stockage FAS, AFF ou ASA, vous pouvez obtenir une licence d'évaluation ONTAP One en contactant l'ingénieur commercial.

Pour plus d'informations sur les licences incluses avec ONTAP One, reportez-vous à la section https://docs.netapp.com/us-en/ontap/system-admin/manage-licenses-concept.html#licenses-included-with-ontap-one["Licences incluses avec ONTAP One"].


NOTE: SnapCenter fait également partie du pack de protection des données. Si vous avez acheté A400 ou une version ultérieure, vous devez acheter le pack de protection des données.



 a| 
SnapMirror ou SnapVault
 a| 
ONTAP

Une licence SnapMirror ou SnapVault est requise si la réplication est activée dans SnapCenter.



 a| 
SnapRestore
 a| 
Indispensable pour restaurer et vérifier les sauvegardes.

Sur les systèmes de stockage primaires

* Indispensable sur les systèmes de destination SnapVault pour effectuer une vérification à distance et une restauration à partir d'une sauvegarde.
* Nécessaire sur les systèmes de destination SnapMirror pour effectuer une vérification à distance.




 a| 
FlexClone
 a| 
Requises pour cloner les bases de données et les opérations de vérification.

Sur les systèmes de stockage primaires et secondaires

* Requis sur les systèmes de destination SnapVault pour créer des clones à partir d'une sauvegarde secondaire à distance.
* Requis sur les systèmes de destination SnapMirror pour créer des clones à partir d'une sauvegarde SnapMirror secondaire




 a| 
Protocoles
 a| 
* Licence iSCSI ou FC pour LUN
* Licence CIFS pour les partages SMB
* Licence NFS pour VMDK de type NFS
* Licence iSCSI ou FC pour les VMDK de type VMFS


Indispensable sur les systèmes de destination SnapMirror pour transmettre les données en cas d'indisponibilité d'un volume source.



 a| 
Licences SnapCenter Standard (en option)
 a| 
Destinations secondaires


NOTE: Il est recommandé, mais pas obligatoire, d'ajouter des licences SnapCenter Standard aux destinations secondaires. Si les licences SnapCenter Standard ne sont pas activées sur les destinations secondaires, vous ne pouvez pas utiliser SnapCenter pour sauvegarder les ressources sur la destination secondaire après avoir effectué une opération de basculement. Une licence FlexClone est toutefois requise sur les destinations secondaires pour effectuer les opérations de clonage et de vérification.

|===

NOTE: Les licences SnapCenter Advanced et SnapCenter NAS File Services sont obsolètes et ne sont plus disponibles. La licence standard et la licence basée sur la capacité ne sont plus nécessaires pour Amazon FSX for NetApp ONTAP, ONTAP Select, Cloud Volumes ONTAP et Azure NetApp Files.

Vous devez installer une ou plusieurs licences SnapCenter. Pour plus d'informations sur l'ajout de licences, reportez-vous à la section link:../install/concept_snapcenter_standard_controller_based_licenses.html["Ajout de licences SnapCenter standard basées sur le contrôleur"].



== Licences Single Mailbox Recovery (SMBR)

Si vous utilisez le plug-in SnapCenter pour Exchange pour gérer les bases de données Microsoft Exchange Server et SMBR (Single Mailbox Recovery), vous devez disposer d'une licence supplémentaire pour SMBR qui doit être achetée séparément selon la boîte aux lettres des utilisateurs.

NetApp® Single Mailbox Recovery a pris fin le 12 mai 2023. Pour plus d'informations, reportez-vous à la section link:https://mysupport.netapp.com/info/communications/ECMLP2885729.html["CPC-00507"]. NetApp continuera d'assurer le support des clients ayant acheté une capacité de boîte aux lettres, des services de maintenance et un support via des références marketing introduites le 24 juin 2020, pendant la durée du support souscrit.

NetApp Single Mailbox Recovery est un produit partenaire fourni par Ontrack. OnTrack PowerControls offre des fonctionnalités similaires à celles de NetApp Single Mailbox Recovery. Les clients peuvent se procurer de nouvelles licences logicielles Ontrack PowerControls et des renouvellements de maintenance et de support Ontrack PowerControls auprès d'Ontrack (jusqu'à licensingteam@ontrack.com) pour une récupération granulaire des boîtes aux lettres après la date de fin de disponibilité du 12 mai 2023.
