---
permalink: install/concept_authentication_methods_for_your_credentials.html 
sidebar: sidebar 
keywords: credentials, authentication 
summary: 'Les informations d"identification utilisent différentes méthodes d"authentification en fonction de l"application ou de l"environnement. Les informations d"identification authentifient les utilisateurs pour qu"ils puissent exécuter des opérations SnapCenter. Vous devez créer un ensemble d"informations d"identification pour l"installation de plug-ins et un autre ensemble pour les opérations de protection des données.' 
---
= Méthodes d'authentification pour vos informations d'identification
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Les informations d'identification utilisent différentes méthodes d'authentification en fonction de l'application ou de l'environnement. Les informations d'identification authentifient les utilisateurs pour qu'ils puissent exécuter des opérations SnapCenter. Vous devez créer un ensemble d'informations d'identification pour l'installation de plug-ins et un autre ensemble pour les opérations de protection des données.



== Authentification Windows

La méthode d'authentification Windows s'authentifie auprès d'Active Directory. Pour l'authentification Windows, Active Directory est configuré en dehors de SnapCenter. L'authentification SnapCenter s'effectue sans configuration supplémentaire. Vous avez besoin d'une information d'identification Windows pour effectuer des tâches telles que l'ajout d'hôtes, l'installation de modules enfichables et les tâches de planification.



== Authentification de domaine non fiable

SnapCenter permet la création d'informations d'identification Windows à l'aide d'utilisateurs et de groupes appartenant aux domaines non fiables. Pour que l'authentification réussisse, vous devez enregistrer les domaines non approuvés avec SnapCenter.



== Authentification locale du groupe de travail

SnapCenter permet la création d'informations d'identification Windows avec des groupes et des utilisateurs de groupes de travail locaux. L'authentification Windows pour les utilisateurs et les groupes de travail locaux n'a pas lieu au moment de la création des informations d'identification Windows, mais est différée jusqu'à ce que l'enregistrement de l'hôte et d'autres opérations de l'hôte soient effectués.



== Authentification SQL Server

La méthode d'authentification SQL s'authentifie par rapport à une instance SQL Server. Cela signifie qu'une instance SQL Server doit être découverte dans SnapCenter. Par conséquent, avant d'ajouter un identifiant SQL, vous devez ajouter un hôte, installer des modules de plug-in et actualiser les ressources. Vous avez besoin de l'authentification SQL Server pour effectuer des opérations telles que la planification sur SQL Server ou la détection des ressources.



== Authentification Linux

La méthode d'authentification Linux s'authentifie par rapport à un hôte Linux. Vous avez besoin d'une authentification Linux au cours de la première étape de l'ajout de l'hôte Linux et de l'installation du module SnapCenter Plug-ins Package pour Linux à distance à partir de l'interface graphique SnapCenter.



== Authentification AIX

La méthode d'authentification AIX s'authentifie auprès d'un hôte AIX. L'authentification AIX doit être effectuée lors de l'étape initiale de l'ajout de l'hôte AIX et de l'installation du module plug-ins SnapCenter pour AIX à distance à partir de l'interface utilisateur graphique SnapCenter.



== Authentification de la base de données Oracle

La méthode d'authentification de la base de données Oracle s'authentifie par rapport à une base de données Oracle. Une authentification de base de données Oracle est nécessaire pour effectuer des opérations sur la base de données Oracle si l'authentification du système d'exploitation est désactivée sur l'hôte de la base de données. Par conséquent, avant d'ajouter des informations d'identification de base de données Oracle, vous devez créer un utilisateur Oracle dans la base de données Oracle avec des privilèges sysdba.



== Authentification Oracle ASM

La méthode d'authentification Oracle ASM s'authentifie par rapport à une instance Oracle Automatic Storage Management (ASM). Si vous devez accéder à l'instance Oracle ASM et si l'authentification du système d'exploitation est désactivée sur l'hôte de la base de données, vous devez disposer d'une authentification Oracle ASM. Par conséquent, avant d'ajouter une information d'identification Oracle ASM, vous devez créer un utilisateur Oracle avec des privilèges sysasm dans l'instance ASM.



== Authentification du catalogue RMAN

La méthode d'authentification du catalogue RMAN s'authentifie par rapport à la base de données du catalogue Oracle Recovery Manager (RMAN). Si vous avez configuré un mécanisme de catalogue externe et enregistré votre base de données dans la base de données de catalogue, vous devez ajouter l'authentification de catalogue RMAN.
