---
permalink: install/configure_two_way_ssl_linux.html 
sidebar: sidebar 
keywords: security,two-way ssl,configure two-way ssl, linux host 
summary: 'Vous devez configurer la communication SSL bidirectionnelle pour sécuriser la communication mutuelle entre le serveur SnapCenter sur l"hôte Linux et les plug-ins.' 
---
= Configurez la communication SSL bidirectionnelle sur l'hôte Linux
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous devez configurer la communication SSL bidirectionnelle pour sécuriser la communication mutuelle entre le serveur SnapCenter sur l'hôte Linux et les plug-ins.

.Avant de commencer
* Vous devez avoir configuré le certificat CA pour l'hôte Linux.
* Vous devez avoir activé la communication SSL bidirectionnelle sur tous les hôtes de plug-in et sur le serveur SnapCenter.


.Étapes
. Copiez *certificate.pem* dans _/etc/pki/ca-trust/source/ancres/_.
. Ajoutez les certificats dans la liste de confiance de votre hôte Linux.
+
** `cp root-ca.pem /etc/pki/ca-trust/source/anchors/`
** `cp certificate.pem /etc/pki/ca-trust/source/anchors/`
** `update-ca-trust extract`


. Vérifiez si les certificats ont été ajoutés à la liste de confiance.
`trust list | grep "<CN of your certificate>"`
. Mettez à jour *ssl_certificate* et *ssl_certificate_key* dans le fichier SnapCenter *nginx* et redémarrez.
+
** `vim /etc/nginx/conf.d/snapcenter.conf`
** `systemctl restart nginx`


. Actualisez le lien de l'interface graphique du serveur SnapCenter.
. Mettez à jour les valeurs des clés suivantes dans *SnapManager.Web.UI.dll.config* situées à l'adresse _ /<installation path>/NetApp/snapcenter/SnapManagerWeb_ et *SMCoreServiceHost.dll.config* situées à l'adresse _/<installation path>/NetApp/snapcenter/SMCore_.
+
** <add key="SERVICE_CERTIFICATE_PATH" value="<path of certificate.pfx>" />
** <add key="SERVICE_CERTIFICATE_PASSWORD" value="<password>"/>


. Redémarrez les services suivants.
+
** `systemctl restart smcore.service`
** `systemctl restart snapmanagerweb.service`


. Vérifiez que le certificat est connecté au port Web SnapManager.
`openssl s_client -connect localhost:8146 -brief`
. Vérifiez que le certificat est connecté au port smcore.
`openssl s_client -connect localhost:8145 -brief`
. Gérer le mot de passe pour la base de stockage de clés SPL et l'alias.
+
.. Récupérer le mot de passe par défaut de la SPL KEYSTORE attribué à la clé *SPL_KEYSTORE_PASS* dans le fichier de propriétés de la SPL.
.. Modifiez le mot de passe de la base de stockage de clés.
`keytool -storepasswd -keystore keystore.jks`
.. Modifiez le mot de passe pour tous les alias des entrées de clé privée.
`keytool -keypasswd -alias "<alias_name>" -keystore keystore.jks`
.. Mettez à jour le même mot de passe pour la clé *SPL_KEYSTORE_PASS* dans _spl.properties_.
.. Redémarrez le service.


. Sur l'hôte Linux du plug-in, ajoutez les certificats racine et intermédiaire dans la base de stockage de clés du plug-in SPL.
+
** `keytool -import -trustcacerts -alias <any preferred alias name> -file <path of root-ca.pem> -keystore <path of keystore.jks mentioned in spl.properties file>`
** `keytool -importkeystore -srckeystore <path of certificate.pfx> -srcstoretype pkcs12 -destkeystore <path of keystore.jks mentioned in spl.properties file> -deststoretype JKS`
+
... Vérifiez les entrées dans keystore.jks.
`keytool -list -v -keystore <path to keystore.jks>`
... Renommez tout alias si nécessaire.
`keytool -changealias -alias "old-alias" -destalias "new-alias" -keypass keypass -keystore </path/to/keystore> -storepass storepas`




. Mettez à jour la valeur de *SPL_CERTIFICATE_ALIAS* dans le fichier _spl.properties_ avec l'alias de *certificate.pfx* stocké dans _keystore.jks_ et redémarrez le service SPL : `systemctl restart spl`
. Vérifiez que le certificat est connecté au port smcore.
`openssl s_client -connect localhost:8145 -brief`

