---
permalink: install/learn-about-supporting-asa-r2-in-snapcenter.html 
sidebar: sidebar 
keywords: ASA r2 systems 
summary: SnapCenter 6.1 prend en charge les systèmes ASA r2 qui offrent une expérience simplifiée adaptée aux besoins des clients SAN uniquement. 
---
= En savoir plus sur la prise en charge des systèmes ASA r2 dans SnapCenter
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenter 6.1 prend en charge les systèmes ASA r2 qui offrent une expérience simplifiée adaptée aux besoins des clients SAN uniquement.

Les systèmes ASA r2 prennent en charge tous les protocoles SAN (iSCSI, FC et NVMe over TCP/IP) sur un déploiement de paire haute disponibilité unique. Les protocoles SCSI (iSCSI et FC) utilisent une architecture actif-actif symétrique pour les chemins d'accès multiples, de sorte que tous les chemins entre les hôtes et le stockage soient actifs/optimisés. Les protocoles iSCSI et NVMe/TCP prennent en charge les chemins directs entre les hôtes et le stockage.


NOTE: SnapCenter prend uniquement en charge VMware Virtual machine File System (VMFS) sur les systèmes ASA r2.

Les systèmes ASA r2 introduisent l'utilisation d'unités de stockage avec groupes de cohérence :

* Une unité de stockage met l'espace de stockage à la disposition de vos hôtes SAN pour les opérations de données. Une unité de stockage désigne une LUN pour les hôtes SCSI ou un namespace NVMe pour les hôtes NVMe.
* Un groupe de cohérence est un ensemble d'unités de stockage gérées comme une seule unité.


Les systèmes ASA r2 utilisent des unités de stockage et des groupes de cohérence pour simplifier la gestion du stockage et la protection des données. Supposons par exemple que vous disposez d'une base de données constituée de 10 unités de stockage dans un groupe de cohérence et que vous devez sauvegarder l'ensemble de la base de données. Au lieu de sauvegarder chaque unité de stockage individuellement, vous pouvez protéger l'ensemble de la base de données en sauvegardant le groupe de cohérence.

https://docs.netapp.com/us-en/asa-r2/get-started/learn-about.html["En savoir plus sur les systèmes ASA r2"].



== Ce qui est pris en charge par SnapCenter 6.1 pour les systèmes ASA r2

SnapCenter vous permet d'effectuer les opérations suivantes sur toutes les applications prises en charge par SnapCenter si vous utilisez des systèmes de stockage ASA r2 :

* Création de sauvegardes primaires d'applications sur VMDK
* Transfert des snapshots de groupes de cohérence vers le système de stockage secondaire
* Restauration des sauvegardes et restauration à partir d'un autre emplacement
+
** Restauration sur place à partir du stockage principal et secondaire à l'aide de VMware vMotion
** Connectez et copiez la restauration à partir du stockage principal et secondaire


* Clonage des sauvegardes et clonage vers un autre emplacement




== Ce qui n'est pas pris en charge par SnapCenter 6.1 pour les systèmes ASA r2

* RDM (Raw Device Mapping)
* Volumes d'application pour Oracle
* NDV SAP HANA
* LockVault
* Copies Snapshot à toute épreuve
* Groupe Flex
* Groupe de cohérence hiérarchique
* Migration de ONTAP 9.x vers des systèmes ASA r2
* Modification du nom des snapshots
* Le provisionnement secondaire du répertoire de journaux de l'hôte de plug-in SQL n'est pas pris en charge par SnapCenter. La configuration doit être effectuée manuellement via l'interface de ligne de commandes ONTAP ou System Manager.

