---
permalink: install/reference_connection_and_port_requirements.html 
sidebar: sidebar 
keywords: ports, port requirements 
summary: 'Assurez-vous que les connexions et les ports requis sont satisfaits avant d"installer le serveur SnapCenter et les plug-ins d"application ou de base de données.' 
---
= Connexion et port requis
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Assurez-vous que les connexions et les ports requis sont satisfaits avant d'installer le serveur SnapCenter et les plug-ins d'application ou de base de données.

* Les applications ne peuvent pas partager de port.
+
Chaque port doit être dédié à l'application appropriée.

* Pour les ports personnalisables, vous pouvez sélectionner un port personnalisé lors de l'installation si vous ne souhaitez pas utiliser le port par défaut.
+
Vous pouvez modifier un port de plug-in après l'installation à l'aide de l'assistant Modifier l'hôte.

* Pour les ports fixes, vous devez accepter le numéro de port par défaut.
* Pare-feu
+
** Les pare-feu, proxys ou autres périphériques réseau ne doivent pas interférer avec les connexions.
** Si vous spécifiez un port personnalisé lors de l'installation de SnapCenter, vous devez ajouter une règle de pare-feu sur l'hôte du plug-in pour ce port pour le chargeur Plug-in SnapCenter.




Le tableau ci-dessous répertorie les différents ports et leurs valeurs par défaut.

|===
| Nom du port | Numéros de port | Protocole | Direction | Description 


 a| 
Port SnapCenter
 a| 
8146
 a| 
HTTPS
 a| 
Bidirectionnel
 a| 
Ce port est utilisé pour la communication entre le client SnapCenter (l'utilisateur SnapCenter) et le serveur SnapCenter et est également utilisé pour la communication entre les hôtes de plug-in et le serveur SnapCenter.

Vous pouvez personnaliser le numéro de port.



 a| 
Port de communication SMCore de SnapCenter
 a| 
8145
 a| 
HTTPS
 a| 
Bidirectionnel
 a| 
Ce port est utilisé pour la communication entre le serveur SnapCenter et les hôtes sur lesquels les plug-ins SnapCenter sont installés.

Vous pouvez personnaliser le numéro de port.



 a| 
Port de service du planificateur
 a| 
8154
 a| 
HTTPS
 a| 
 a| 
Ce port permet d'orchestrer de manière centralisée les flux de travail du planificateur SnapCenter pour tous les plug-ins gérés au sein de l'hôte du serveur SnapCenter.

Vous pouvez personnaliser le numéro de port.



 a| 
Port RabbitMQ
 a| 
5672
 a| 
TCP
 a| 
 a| 
Il s'agit du port par défaut sur lequel RabbitMQ écoute et il est utilisé pour la communication du modèle éditeur-abonné entre le service Planificateur et SnapCenter.



 a| 
Port MySQL
 a| 
3306
 a| 
HTTPS
 a| 
 a| 
Le port est utilisé pour communiquer avec la base de données du référentiel SnapCenter. Vous pouvez créer des connexions sécurisées du serveur SnapCenter au serveur MySQL. link:../install/concept_configure_secured_mysql_connections_with_snapcenter_server.html["En savoir plus >>"]



 a| 
Hôtes du plug-in Windows
 a| 
135, 445
 a| 
TCP
 a| 
 a| 
Ce port est utilisé pour la communication entre le serveur SnapCenter et l'hôte sur lequel le plug-in est installé. La plage de ports dynamique supplémentaire spécifiée par Microsoft doit également être ouverte.



 a| 
Hôtes du plug-in Linux ou AIX
 a| 
22
 a| 
SSH
 a| 
Unidirectionnel
 a| 
Ce port est utilisé pour la communication entre le serveur SnapCenter et l'hôte, lancé du serveur à l'hôte client.



 a| 
Module de plug-ins SnapCenter pour Windows, Linux ou AIX
 a| 
8145
 a| 
HTTPS
 a| 
Bidirectionnel
 a| 
Ce port est utilisé pour la communication entre SMCore et les hôtes sur lesquels le package de plug-ins est installé. Personnalisable.

Vous pouvez personnaliser le numéro de port.



 a| 
Plug-in SnapCenter pour bases de données Oracle
 a| 
27216
 a| 
 a| 
 a| 
Le port JDBC par défaut est utilisé par le plug-in pour Oracle pour se connecter à la base de données Oracle.



 a| 
Plug-in SnapCenter pour base de données Exchange
 a| 
909
 a| 
 a| 
 a| 
Le NET par défaut. Le port TCP est utilisé par le plug-in pour Windows pour se connecter aux rappels Exchange VSS.



 a| 
Plug-ins pris en charge par NetApp pour SnapCenter
 a| 
9090
 a| 
HTTPS
 a| 
 a| 
Il s'agit d'un port interne utilisé uniquement sur l'hôte personnalisé du plug-in ; aucune exception de pare-feu n'est requise.

La communication entre le serveur SnapCenter et les plug-ins personnalisés est routée via le port 8145.



 a| 
Cluster ONTAP ou port de communication SVM
 a| 
* 443 (HTTPS)
* 80 (HTTP)

 a| 
* HTTPS
* HTTP

 a| 
Bidirectionnel
 a| 
Le port est utilisé par le SAL (Storage abstraction Layer) pour la communication entre l'hôte exécutant le serveur SnapCenter et le SVM. Le port est actuellement utilisé par le SAL sur SnapCenter pour les hôtes du plug-in Windows pour la communication entre l'hôte du plug-in SnapCenter et le SVM.



 a| 
Plug-in SnapCenter pour base de données SAP HANA
 a| 
* 3instance_number13
* 3instance_number15

 a| 
* HTTPS
* HTTP

 a| 
Bidirectionnel
 a| 
Pour un seul tenant de conteneur de base de données multitenant (MDC), le numéro de port se termine par 13 ; pour non MDC, le numéro de port se termine par 15.

Vous pouvez personnaliser le numéro de port.



 a| 
Plug-in SnapCenter pour PostgreSQL
 a| 
5432
 a| 
 a| 
 a| 
Ce port est le port PostgreSQL par défaut utilisé pour la communication entre le plug-in pour PostgreSQL et le cluster PostgreSQL.

Vous pouvez personnaliser le numéro de port.

|===
Pour modifier les détails du port, voir link:../admin/concept_manage_hosts.html#modify-plug-in-hosts["Modifier les hôtes du plug-in"].
