---
permalink: install/reference_space_and_sizing_requirements.html 
sidebar: sidebar 
keywords: SnapCenter 
summary: 'Avant d"installer le serveur SnapCenter, vous devez connaître les exigences en matière d"espace et de dimensionnement. Vous devez également appliquer les mises à jour système et de sécurité disponibles.' 
---
= Les besoins en termes d'espace et de dimensionnement
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Avant d'installer le serveur SnapCenter, vous devez connaître les exigences en matière d'espace et de dimensionnement. Vous devez également appliquer les mises à jour système et de sécurité disponibles.

|===
| Élément | Configuration requise pour les hôtes Windows | Configuration requise pour l'hôte Linux 


 a| 
Systèmes d'exploitation
 a| 
Microsoft Windows

Seules les versions anglaise, allemande, japonaise et chinoise simplifiée des systèmes d'exploitation sont prises en charge.

Pour obtenir les informations les plus récentes sur les versions prises en charge, reportez-vous à la section https://imt.netapp.com/matrix/imt.jsp?components=121033;&solution=1258&isHWU&src=IMT["Matrice d'interopérabilité NetApp"^].
 a| 
* Red Hat Enterprise Linux (RHEL) 8 et 9
* SUSE Linux Enterprise Server (SLES) 15


Pour obtenir les informations les plus récentes sur les versions prises en charge, reportez-vous à la section https://imt.netapp.com/matrix/imt.jsp?components=121032;&solution=1258&isHWU&src=IMT["Matrice d'interopérabilité NetApp"^].



 a| 
Nombre minimal de processeurs
 a| 
4 cœurs
 a| 
4 cœurs



 a| 
RAM minimale
 a| 
8 Go


NOTE: Le pool de mémoire tampon du serveur MySQL utilise 20 % de la RAM totale.
 a| 
8 Go



 a| 
Espace minimal sur le disque dur pour le logiciel et les journaux du serveur SnapCenter
 a| 
7 GO


NOTE: Si vous disposez du référentiel SnapCenter dans le lecteur où est installé le serveur SnapCenter, il est recommandé d'avoir 15 Go.
 a| 
15 GO



 a| 
Espace disque minimum pour le référentiel SnapCenter
 a| 
8 Go


NOTE: REMARQUE : si le serveur SnapCenter se trouve dans le même lecteur que le référentiel SnapCenter, il est recommandé d'avoir 15 Go.
 a| 
Sans objet



 a| 
Packs logiciels requis
 a| 
* Microsoft .NET Framework 4.7.2 ou version ultérieure
* ASP. Bundle d'hébergement NET Core (8.0.5 ou version ultérieure)
* PowerShell 7.4.2 ou version ultérieure


Pour obtenir des informations de dépannage spécifiques à .NET, reportez-vous à la section https://kb.netapp.com/Advice_and_Troubleshooting/Data_Protection_and_Security/SnapCenter/SnapCenter_upgrade_or_install_fails_with_%22This_KB_is_not_related_to_the_OS%22["Échec de la mise à niveau ou de l'installation de SnapCenter pour les systèmes hérités qui ne disposent pas d'une connexion Internet"^].
 a| 
* ASP. NET Core Runtime version 8.0.5 ou ultérieure
* PowerShell 7.4.2 ou version ultérieure
* Ce serveur Web peut être utilisé comme proxy inverse
* Devel-PAM
+
PAM (Pluggable Authentication modules) est un outil de sécurité système qui permet aux administrateurs système de définir une stratégie d'authentification sans avoir à recompiler les programmes qui effectuent l'authentification.



|===