---
permalink: install/task_configure_CA_certificate_with_snapcenter_site.html 
sidebar: sidebar 
keywords: SnapCenter, configure, CA certificate 
summary: 'Vous devez configurer le certificat d"autorité de certification avec le site SnapCenter sur l"hôte Windows.' 
---
= Configuration du certificat d'autorité de certification avec le site SnapCenter
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous devez configurer le certificat d'autorité de certification avec le site SnapCenter sur l'hôte Windows.

*Étapes*

. Ouvrez le Gestionnaire IIS sur le serveur Windows sur lequel SnapCenter est installé.
. Dans le volet de navigation de gauche, cliquez sur *connexions*.
. Développez le nom du serveur et *sites*.
. Sélectionnez le site Web SnapCenter sur lequel vous souhaitez installer le certificat SSL.
. Accédez à *actions* > *Modifier le site*, cliquez sur *liaisons*.
. Dans la page liaisons, sélectionnez *Reliure pour https*.
. Cliquez sur *Modifier*.
. Dans la liste déroulante certificat SSL, sélectionnez le certificat SSL récemment importé.
. Cliquez sur *OK*.



NOTE: Si le certificat de l'autorité de certification récemment déployé n'apparaît pas dans le menu déroulant, vérifiez si le certificat de l'autorité de certification est associé à la clé privée.


IMPORTANT: Assurez-vous que le certificat est ajouté à l'aide du chemin suivant : *racine de la console > certificats – ordinateur local > autorités de certification racine de confiance > certificats*.
