---
permalink: protect-scu/task_create_backup_policies_for_unix_file_systems.html 
sidebar: sidebar 
keywords: backup policies, policies, unix file systems, file systems 
summary: Créez une stratégie de sauvegarde pour les systèmes de fichiers Unix que vous souhaitez sauvegarder. 
---
= Créez des règles de sauvegarde pour les systèmes de fichiers Unix
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Avant d'utiliser SnapCenter pour sauvegarder des systèmes de fichiers Unix, vous devez créer une stratégie de sauvegarde pour la ressource ou le groupe de ressources que vous souhaitez sauvegarder. Une stratégie de sauvegarde est un ensemble de règles qui régit la gestion, la planification et la conservation des sauvegardes. Vous pouvez également spécifier les paramètres de réplication, de script et de type de sauvegarde. La création d'une stratégie permet de gagner du temps lorsque vous souhaitez réutiliser la stratégie sur une autre ressource ou un autre groupe de ressources.

.Avant de commencer
* Vous devez vous préparer à la protection des données en réalisant des tâches telles que l'installation de SnapCenter, l'ajout d'hôtes, la découverte des systèmes de fichiers et la création de connexions au système de stockage.
* Si vous répliquez des snapshots sur un stockage secondaire de copie miroir ou d'archivage sécurisé, l'administrateur SnapCenter doit vous avoir assigné les SVM pour les volumes source et de destination.
* Vérifiez les prérequis et les limites spécifiques de la synchronisation active SnapMirror. Pour plus d'informations, reportez-vous à https://docs.netapp.com/us-en/ontap/smbc/considerations-limits.html#volumes["Limites d'objet pour la synchronisation active SnapMirror"].


.Description de la tâche
* SnapLock
+
** Si l'option « conserver les copies de sauvegarde pendant un nombre de jours spécifique » est sélectionnée, la période de conservation SnapLock doit être inférieure ou égale aux jours de conservation mentionnés.
+
La spécification d'une période de verrouillage de snapshot empêche la suppression des snapshots jusqu'à l'expiration de la période de conservation.  Cela peut entraîner la conservation d'un nombre plus important de snapshots que le nombre spécifié dans la règle.

+
Pour ONTAP 9.12.1 et les versions antérieures, les clones créés à partir des snapshots de coffre-fort SnapLock dans le cadre de la restauration hériteront de l'heure d'expiration du coffre-fort SnapLock. L'administrateur du stockage doit nettoyer manuellement les clones après l'heure d'expiration du SnapLock.





.Étapes
. Dans le volet de navigation de gauche, cliquez sur *Paramètres*.
. Dans la page Paramètres, cliquez sur *stratégies*.
. Sélectionnez *Unix File Systems* dans la liste déroulante.
. Cliquez sur *Nouveau*.
. Dans la page Nom, entrez le nom et les détails de la stratégie.
. Dans la page sauvegarde et réplication, effectuez les opérations suivantes :
+
.. Spécifiez les paramètres de sauvegarde.
.. Spécifiez la fréquence d'horaire en sélectionnant *sur demande*, *horaire*, *quotidien*, *hebdomadaire* ou *mensuel*.
.. Dans la section Sélectionner les options de réplication secondaire, sélectionnez l'une des options de réplication secondaires suivantes ou les deux :


+
|===
| Pour ce champ... | Procédez comme ça... 


 a| 
Mettez à jour SnapMirror après avoir créé une copie Snapshot locale
 a| 
Sélectionnez ce champ pour créer des copies en miroir des jeux de sauvegarde sur un autre volume (réplication SnapMirror).

Cette option doit être activée pour la synchronisation active SnapMirror.



 a| 
Mettez à jour SnapVault après avoir créé une copie Snapshot locale
 a| 
Sélectionnez cette option pour effectuer la réplication de sauvegarde disque à disque (sauvegardes SnapVault).



 a| 
Nombre de tentatives d'erreur
 a| 
Saisissez le nombre maximal de tentatives de réplication pouvant être autorisées avant l'arrêt de l'opération.

|===
. Dans la page Retention, spécifiez les paramètres de rétention pour le type de sauvegarde et le type de planification sélectionnés dans la page sauvegarde et réplication :
+
|===


| Les fonctions que vous recherchez... | Alors... 


 a| 
Conserver un certain nombre d'instantanés
 a| 
Sélectionnez *copies à conserver*, puis indiquez le nombre d'instantanés que vous souhaitez conserver.

Si le nombre d'instantanés dépasse le nombre spécifié, les instantanés sont supprimés avec les plus anciennes copies supprimées en premier.


NOTE: La valeur de rétention maximale est 1018. Les sauvegardes échouent si la conservation est définie sur une valeur supérieure à celle prise en charge par la version ONTAP sous-jacente.


IMPORTANT: Si vous prévoyez d'activer la réplication SnapVault, vous devez définir le nombre de rétention sur 2 ou plus. Si vous définissez le nombre de rétention sur 1, l'opération de conservation peut échouer, car le premier snapshot est l'instantané de référence de la relation SnapVault jusqu'à ce qu'un nouvel instantané soit répliqué sur la cible.



 a| 
Conserver les instantanés pendant un certain nombre de jours
 a| 
Sélectionnez *conserver les copies pour*, puis indiquez le nombre de jours pendant lesquels vous souhaitez conserver les instantanés avant de les supprimer.



 a| 
Période de verrouillage de la copie instantanée
 a| 
Sélectionnez *Période de verrouillage de la copie instantanée* et spécifiez la durée en jours, mois ou années.

La période de conservation SnapLock doit être inférieure à 100 ans.

|===
. Sélectionnez le libellé de la stratégie.
+

NOTE: Vous pouvez attribuer des étiquettes SnapMirror aux snapshots principaux pour la réplication à distance, permettant ainsi aux snapshots principaux de décharger l'opération de réplication de snapshot de SnapCenter vers les systèmes secondaires ONTAP .  Cela peut être fait sans activer l’option SnapMirror ou SnapVault dans la page de politique.

. Dans la page script, entrez le chemin d'accès et les arguments du prescripteur ou du PostScript que vous souhaitez exécuter avant ou après l'opération de sauvegarde, respectivement.
+

NOTE: Vous devez vérifier si les commandes existent dans la liste de commandes disponible sur l'hôte du plug-in à partir de _ /opt/NetApp/SnapCenter/scc/etc/allowed_commands.config_path.

+
Vous pouvez également spécifier la valeur du délai d'expiration du script. La valeur par défaut est 60 secondes.

. Vérifiez le résumé, puis cliquez sur *Terminer*.

