---
permalink: protect-db2/how-resources-resource-groups-and-policies-are-used-for-protecting-ibm-db2.html 
sidebar: sidebar 
keywords: IBM DB2 
summary: 'Avant d"utiliser SnapCenter, il est utile de maîtriser les concepts de base associés aux opérations de sauvegarde, de clonage et de restauration que vous souhaitez effectuer. Vous interagissez avec les ressources, les groupes de ressources et les stratégies pour différentes opérations.' 
---
= Utilisation des ressources, des groupes de ressources et des stratégies pour protéger IBM DB2
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Avant d'utiliser SnapCenter, il est utile de maîtriser les concepts de base associés aux opérations de sauvegarde, de clonage et de restauration que vous souhaitez effectuer. Vous interagissez avec les ressources, les groupes de ressources et les stratégies pour différentes opérations.

* Les ressources sont généralement des bases de données IBM DB2 que vous sauvegardez ou clonez avec SnapCenter.
* Un groupe de ressources SnapCenter est un ensemble de ressources sur un hôte.
+
Lorsque vous effectuez une opération sur un groupe de ressources, vous effectuez cette opération sur les ressources définies dans le groupe de ressources en fonction du planning que vous spécifiez pour le groupe de ressources.

+
Vous pouvez sauvegarder à la demande une seule ressource ou un groupe de ressources. Vous pouvez également effectuer des sauvegardes planifiées pour des ressources et des groupes de ressources uniques.

* Les règles spécifient la fréquence des sauvegardes, la réplication, les scripts et d'autres caractéristiques des opérations de protection des données.
+
Lorsque vous créez un groupe de ressources, vous sélectionnez une ou plusieurs stratégies pour ce groupe. Vous pouvez également sélectionner une stratégie lorsque vous effectuez une sauvegarde à la demande pour une seule ressource.



Considérez un groupe de ressources comme définissant ce que vous voulez protéger et quand vous voulez le protéger en termes de jour et d'heure. Considérez une stratégie comme une définition de la façon dont vous voulez la protéger. Si vous sauvegardez toutes les bases de données, par exemple, vous pouvez créer un groupe de ressources qui inclut toutes les bases de données de l'hôte. Vous pouvez ensuite associer deux stratégies au groupe de ressources : une stratégie quotidienne et une stratégie horaire. Lorsque vous créez le groupe de ressources et joignez les stratégies, vous pouvez configurer le groupe de ressources de manière à effectuer une sauvegarde complète tous les jours.
