---
permalink: protect-db2/install-the-snapcenter-plug-in-for-ibm-db2-on-linux-hosts-using-the-command-line-interface.html 
sidebar: sidebar 
keywords: install, SnapCenter Plug-in for IBM Db2 
summary: 'Vous devez installer le plug-in SnapCenter pour IBM DB2 Database à l"aide de l"interface utilisateur SnapCenter. Si votre environnement ne permet pas l"installation à distance du plug-in à partir de l"interface utilisateur SnapCenter, vous pouvez installer le plug-in pour IBM DB2 Database en mode console ou en mode silencieux à l"aide de l"interface de ligne de commande (CLI1).' 
---
= Installez le plug-in SnapCenter pour IBM DB2 sur les hôtes Linux à l'aide de l'interface de ligne de commande
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous devez installer le plug-in SnapCenter pour IBM DB2 Database à l'aide de l'interface utilisateur SnapCenter. Si votre environnement ne permet pas l'installation à distance du plug-in à partir de l'interface utilisateur SnapCenter, vous pouvez installer le plug-in pour la base de données IBM DB2 en mode console ou en mode silencieux à l'aide de l'interface de ligne de commande (CLI).

.Avant de commencer
* Vous devez installer le plug-in pour IBM DB2 Database sur chaque hôte Linux sur lequel réside le client IBM DB2.
* L'hôte Linux sur lequel vous installez le plug-in SnapCenter pour IBM DB2 Database doit répondre à la configuration logicielle, de base de données et de système d'exploitation.
+
La matrice d'interopérabilité (IMT) contient les dernières informations sur les configurations prises en charge.

+
https://imt.netapp.com/matrix/imt.jsp?components=121066;&solution=1259&isHWU&src=IMT["Matrice d'interopérabilité NetApp"]

* Le plug-in SnapCenter pour IBM DB2 Database fait partie du module de plug-ins SnapCenter pour Linux. Avant d'installer SnapCenter Plug-ins Package pour Linux, vous devez avoir déjà installé SnapCenter sur un hôte Windows.


.Description de la tâche
Si les paramètres ne sont pas mentionnés, SnapCenter est installé avec les valeurs par défaut.

.Étapes
. Copiez le fichier d'installation du pack de plug-ins SnapCenter pour Linux (snapcenter_linux_host_plugin.bin) depuis C:\ProgramData\NetApp\SnapCenter\Package Repository vers l'hôte sur lequel vous souhaitez installer le plug-in pour IBM DB2.
+
Vous pouvez accéder à ce chemin à partir de l'hôte sur lequel le serveur SnapCenter est installé.

. À partir de l'invite de commande, accédez au répertoire dans lequel vous avez copié le fichier d'installation.
. Installez le plug-in : `path_to_installation_bin_file/snapcenter_linux_host_plugin.bin -i silent -DPORT=port_number_for_host -DSERVER_IP=server_name_or_ip_address -DSERVER_HTTPS_PORT=port_number_for_server`
+
** -DPORT spécifie le port de communication SMCore HTTPS.
** -DSERVER_IP spécifie l'adresse IP du serveur SnapCenter.
** -DSERVER_HTTPS_PORT spécifie le port HTTPS du serveur SnapCenter.
** -DUSER_INSTALL_DIR indique le répertoire dans lequel vous souhaitez installer le module de plug-ins SnapCenter pour Linux.
** DINSTALL_LOG_NAME indique le nom du fichier journal.


+
[listing]
----
/tmp/sc-plugin-installer/snapcenter_linux_host_plugin.bin -i silent  -DPORT=8145 -DSERVER_IP=scserver.domain.com -DSERVER_HTTPS_PORT=8146 -DUSER_INSTALL_DIR=/opt -DINSTALL_LOG_NAME=SnapCenter_Linux_Host_Plugin_Install_2.log -DCHOSEN_FEATURE_LIST=CUSTOM
----
. Modifiez le fichier /<installation directory>/NetApp/snapcenter/scc/etc/SC_SMS_Services.properties, puis ajoutez le paramètre PLUGINS_ENABLED = DB2:3.0.
. Ajoutez l'hôte au serveur SnapCenter à l'aide de l'applet de commande Add-Smhost et des paramètres requis.
+
Les informations relatives aux paramètres pouvant être utilisés avec la commande et leurs descriptions peuvent être obtenues en exécutant _get-Help nom_commande_. Vous pouvez également vous reporter à la https://docs.netapp.com/us-en/snapcenter-cmdlets/index.html["Guide de référence de l'applet de commande du logiciel SnapCenter"^].


