---
permalink: protect-db2/storage-types-supported-by-snapcenter-plug-in-for-ibm-db2.html 
sidebar: sidebar 
keywords: storage types, 
summary: 'SnapCenter prend en charge de nombreux types de stockage sur les serveurs physiques et virtuels. Vous devez vérifier le support de votre type de stockage avant d"installer le plug-in SnapCenter pour IBM DB2.' 
---
= Types de stockage pris en charge par le plug-in SnapCenter pour IBM DB2
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenter prend en charge de nombreux types de stockage sur les serveurs physiques et virtuels. Vous devez vérifier le support de votre type de stockage avant d'installer le plug-in SnapCenter pour IBM DB2.

|===
| Machine | Type de stockage 


 a| 
Serveur physique
 a| 
* LUN connectés via FC
* LUN connectées à l'iSCSI
* Volumes connectés par NFS




 a| 
VMware ESXi
 a| 
* L'exécution des LUN RDM connectés par un HBA FC ou iSCSI ESXi peut prendre du temps car SnapCenter analyse tous les adaptateurs de bus hôte présents dans l'hôte.
+
Vous pouvez modifier le fichier *LinuxConfig.pm* situé à _/opt/NetApp/snapcenter/spl/plugins/scu/scucore/modules/SCU/Config_ pour définir la valeur du paramètre *SCSI_HOSTS_OPTIMIZED_RESCAN* à 1 pour analyser uniquement les HBA répertoriés dans les NOMS de PILOTE HBA.

* LUN iSCSI connectés directement au système invité par l'initiateur iSCSI
* VMDK sur des datastores NFS
* VMDK sur VMFS créés
* Volumes NFS connectés directement au système invité
* Datastores vVol sur NFS et SAN
+
Le datastore vVol peut uniquement être provisionné avec les outils ONTAP pour VMware vSphere.



|===