---
permalink: protect-db2/types-of-restore-strategies-supported-for-manually-added-ibm-db2.html 
sidebar: sidebar 
keywords: SnapCenter 
summary: 'Vous devez définir une stratégie pour pouvoir effectuer les opérations de restauration à l"aide de SnapCenter. Il existe deux types de stratégies de restauration pour les ressources IBM DB2 ajoutées manuellement. Vous ne pouvez pas récupérer les ressources IBM DB2 ajoutées manuellement.' 
---
= Stratégies de restauration pour les ressources IBM Db2 ajoutées manuellement dans SnapCenter
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous devez définir une stratégie pour pouvoir effectuer les opérations de restauration à l'aide de SnapCenter. Il existe deux types de stratégies de restauration pour les ressources IBM DB2 ajoutées manuellement.


NOTE: Vous ne pouvez pas récupérer les ressources IBM DB2 ajoutées manuellement.



[[complete-resource-restore]]
== Restauration des ressources terminée

* Restauration de tous les volumes, qtrees et LUN d'une ressource



NOTE: Si la ressource contient des volumes ou des qtrees, les snapshots pris après le snapshot sélectionné pour la restauration sur ces volumes ou ces qtrees sont supprimés et ne peuvent pas être restaurés. De même, si une autre ressource est hébergée sur les mêmes volumes ou qtrees, cette ressource est également supprimée.
