---
permalink: protect-nsp/install_snapcenter_plug_in_packages_for_linux_or_windows_on_multiple_remote_hosts_using_cmdlets.html 
sidebar: sidebar 
keywords: install, snapcenter 
summary: 'Vous pouvez installer simultanément les modules SnapCenter Plug-in pour Linux ou Windows sur plusieurs hôtes à l"aide de l"applet de commande Install-SmHostPackage PowerShell.' 
---
= Installez des packages de plug-ins SnapCenter sur plusieurs hôtes distants à l'aide d'applets de commande
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez installer simultanément les modules de plug-in SnapCenter pour Linux, Windows ou AIX sur plusieurs hôtes à l'aide de l'applet de commande PowerShell Install-SmHostPackage.

.Avant de commencer
L'utilisateur qui ajoute un hôte doit disposer des droits d'administration sur l'hôte.


NOTE: Les applications de stockage et Oracle sont prises en charge sous AIX.

.Étapes
. Lancer PowerShell.
. Sur l'hôte du serveur SnapCenter, établissez une session à l'aide de l'applet de commande Open-SmConnection, puis saisissez vos informations d'identification.
. Installez le plug-in sur plusieurs hôtes à l'aide de l'applet de commande Install-SmHostPackage et des paramètres requis.
+
Les informations relatives aux paramètres pouvant être utilisés avec la cmdlet et leurs descriptions peuvent être obtenues en exécutant _get-Help nom_commande_. Vous pouvez également vous reporter à la https://docs.netapp.com/us-en/snapcenter-cmdlets/index.html["Guide de référence de l'applet de commande du logiciel SnapCenter"^].

+
Vous pouvez utiliser l'option -skippreccheck lorsque vous avez installé les plug-ins manuellement et ne souhaitez pas vérifier si l'hôte répond aux exigences d'installation du plug-in.

. Saisissez vos informations d'identification pour l'installation à distance.

