---
permalink: get-started/learn-about-snapcenter-support-for-asa-r2-systems.html 
sidebar: sidebar 
keywords: storage system, ONTAP version, ASA r2 systems 
summary: Vous devez connaître le système de stockage, les applications et les bases de données pris en charge. 
---
= Opérations SnapCenter prises en charge pour les systèmes ASA r2
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Les systèmes de stockage ASA r2 sont pris en charge à partir de SnapCenter 6.1. https://docs.netapp.com/us-en/asa-r2/get-started/learn-about.html["En savoir plus sur les systèmes ASA r2"^] .

SnapCenter prend en charge la protection primaire et secondaire des applications exécutées sur des systèmes physiques et sur des systèmes de fichiers de machines virtuelles (VMFS).  SnapCenter utilise les API REST pour toutes les opérations sur les systèmes ASA r2.  Les systèmes ASA r2 ne prennent pas en charge les ZAPI.

*Opérations prises en charge par SnapCenter pour les systèmes ASA r2*

* Création de sauvegardes primaires d'applications
* Déplacement des instantanés de groupe de cohérence hiérarchique vers un système de stockage secondaire
* Restauration des sauvegardes des systèmes de stockage principal et secondaire vers l'hôte d'origine ou alternatif
+
** Restauration sur place à partir des systèmes de stockage principaux et secondaires à l'aide de VMware vMotion
** Connectez et copiez la restauration à partir des systèmes de stockage principal et secondaire


* Clonage des sauvegardes sur l'hôte d'origine ou sur l'hôte alternatif
* RDM (Raw Device Mapping)
* Protection des volumes d'application pour Oracle
* Protection de SAP HANA NDV
* LockVault
* Provisionnement secondaire du répertoire de journaux de l'hôte du plug-in SQL


SnapCenter découvre ou crée des groupes de cohérence ONTAP .  Il configure les relations SnapMirror sur le cluster de destination pour une protection secondaire. https://docs.netapp.com/us-en/ontap/consistency-groups["En savoir plus sur les groupes de cohérence ONTAP"^] .


NOTE: Après la mise à niveau vers SnapCenter 6.2 (serveur et plug-ins) et ONTAP 9.17.1, SnapCenter modifie les groupes de cohérence plats en groupes de cohérence hiérarchiques lors de la première sauvegarde planifiée.

Pour savoir comment activer la protection secondaire sur les systèmes ASA r2 pour votre application, consultez :

* https://docs.netapp.com/us-en/snapcenter/protect-scsql/create-resource-groups-secondary-protection-for-asa-r2-mssql-resources.html["Activer la protection secondaire pour les ressources Microsoft SQL Server"]
* https://docs.netapp.com/us-en/snapcenter/protect-hana/create-resource-groups-secondary-protection-for-asa-r2-hana-resources.html["Activer la protection secondaire pour les ressources SAP HANA"]
* https://docs.netapp.com/us-en/snapcenter/protect-sco/create-resource-groups-secondary-protection-for-asa-r2-oracle-resources.html["Activer la protection secondaire pour les ressources Oracle"]
* https://docs.netapp.com/us-en/snapcenter/protect-scw/create-resource-groups-secondary-protection-for-asa-r2-windows-file-systems.html["Activer la protection secondaire pour les systèmes de fichiers Windows"]
* https://docs.netapp.com/us-en/snapcenter/protect-db2/create-resource-groups-secondary-protection-for-asa-r2-db2-resources.html["Activer la protection secondaire pour les ressources IBM Db2"]
* https://docs.netapp.com/us-en/snapcenter/protect-postgresql/create-resource-groups-secondary-protection-for-asa-r2-postgresql-resources.html["Activer la protection secondaire pour les ressources PostgreSQL"]
* https://docs.netapp.com/us-en/snapcenter/protect-mysql/create-resource-groups-secondary-protection-for-asa-r2-mysql-resources.html["Activer la protection secondaire pour les ressources MySQL"]
* https://docs.netapp.com/us-en/snapcenter/protect-scu/create-resource-groups-secondary-protection-for-asa-r2-unix-resources.html["Activer la protection secondaire pour les systèmes de fichiers Unix"]


*Opérations non prises en charge par SnapCenter pour les systèmes ASA r2*

* Des snapshots inviolables
* Volumes FlexGroup
* Migration des systèmes de stockage ASA, AFF ou FAS vers les systèmes de stockage ASA r2
* Protection des bases de données avec un mélange de ressources ASA, AFF ou FAS et de ressources ASA r2
* Modification du nom des snapshots
* Provisionnement des ressources Windows
* Protection secondaire en cas de basculement de synchronisation active SnapMirror
* Protocole NVMe (Nonvolatile Memory Express) si SnapMirror Active Sync est activé
* Protection des applications exécutées sur AIX
* Mise à jour technologique
* Récupération après sinistre des ressources Microsoft SQL

