---
permalink: get-started/rbac-snapcenter.html 
sidebar: sidebar 
keywords: RBAC, roles, permissions, application-level RBAC, ONTAP permissions, default snapcenter roles, ONTAP permissions, SnapCenter Admin role 
summary: 'Le contrôle d"accès basé sur des rôles (RBAC) SnapCenter et les autorisations ONTAP permettent aux administrateurs SnapCenter de créer des rôles et de définir des autorisations d"accès. Cet accès géré de manière centralisée permet aux administrateurs d"applications de travailler en toute sécurité dans les environnements délégués.' 
---
= Contrôle d'accès basé sur des rôles dans SnapCenter
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Le contrôle d'accès basé sur des rôles (RBAC) SnapCenter et les autorisations ONTAP permettent aux administrateurs SnapCenter de déléguer le contrôle des ressources SnapCenter à différents utilisateurs ou groupes d'utilisateurs. Cet accès géré de manière centralisée permet aux administrateurs d'applications de travailler en toute sécurité dans les environnements délégués.

Vous pouvez créer et modifier des rôles et ajouter des accès aux ressources aux utilisateurs à tout moment. Cependant, lorsque vous configurez SnapCenter pour la première fois, vous devez au moins ajouter des utilisateurs ou des groupes Active Directory aux rôles, puis ajouter un accès aux ressources à ces utilisateurs ou groupes.


NOTE: Vous ne pouvez pas utiliser SnapCenter pour créer des comptes d'utilisateur ou de groupe. Vous devez créer des comptes d'utilisateur ou de groupe dans Active Directory du système d'exploitation ou de la base de données.



== Types de RBAC dans SnapCenter

SnapCenter utilise les types suivants de contrôle d'accès basé sur les rôles :

* RBAC SnapCenter
* RBAC au niveau des applications
* Plug-in SnapCenter pour VMware vSphere RBAC
* Autorisations ONTAP




=== RBAC SnapCenter

SnapCenter possède des rôles prédéfinis et vous pouvez affecter des utilisateurs ou des groupes d'utilisateurs à ces rôles. Les rôles prédéfinis sont :

* Rôle d'administrateur SnapCenter
* Rôle d'administrateur de clones et de sauvegarde des applications
* Rôle Backup and Clone Viewer
* Rôle d'administrateur de l'infrastructure


Lorsque vous attribuez un rôle à un utilisateur, seuls les travaux pertinents pour cet utilisateur sont visibles dans la page travaux, sauf si vous avez attribué le rôle SnapCenterAdmin.

Vous pouvez également créer de nouveaux rôles et gérer les autorisations et les utilisateurs. Vous pouvez attribuer des autorisations aux utilisateurs ou aux groupes pour accéder aux objets SnapCenter tels que les hôtes, les connexions de stockage et les groupes de ressources.

Vous pouvez attribuer des autorisations RBAC aux utilisateurs et groupes au sein de la même forêt et aux utilisateurs appartenant à différentes forêts. Vous ne pouvez pas attribuer d'autorisations RBAC aux utilisateurs appartenant à des groupes imbriqués dans les forêts.


NOTE: Si vous créez un rôle personnalisé, il doit contenir toutes les autorisations du rôle SnapCenterAdmin. Si vous copiez uniquement certaines autorisations, par exemple, l'ajout ou le retrait d'hôte, vous ne pouvez pas effectuer ces opérations.

Les utilisateurs doivent fournir une authentification lors de la connexion, via l'interface utilisateur graphique ou via les applets de commande PowerShell. Si les utilisateurs sont membres de plusieurs rôles, après avoir saisi des informations d'identification, ils sont invités à spécifier le rôle qu'ils souhaitent utiliser. Les utilisateurs doivent également fournir une authentification pour l'exécution des API.



=== RBAC au niveau des applications

SnapCenter utilise les identifiants pour vérifier que les utilisateurs SnapCenter autorisés disposent également des autorisations au niveau de l'application.

Par exemple, si vous souhaitez effectuer des opérations de protection des données dans un environnement SQL Server, vous devez définir des informations d'identification avec les informations d'identification Windows ou SQL appropriées. Le serveur SnapCenter authentifie les informations d'identification définies à l'aide de l'une ou l'autre méthode. Si vous souhaitez effectuer des opérations de protection des données dans un environnement de système de fichiers Windows sur un système de stockage ONTAP, le rôle admin SnapCenter doit avoir admin Privileges sur l'hôte Windows.

De même, si vous souhaitez effectuer des opérations de protection des données sur une base de données Oracle et si l'authentification du système d'exploitation est désactivée dans l'hôte de la base de données, vous devez définir les informations d'identification avec la base de données Oracle ou les informations d'identification Oracle ASM. Le serveur SnapCenter authentifie les informations d'identification définies à l'aide de l'une de ces méthodes, en fonction de l'opération.



=== Plug-in SnapCenter pour VMware vSphere RBAC

Si vous utilisez le plug-in SnapCenter pour la protection de données cohérente avec les machines virtuelles, vCenter Server offre un niveau supplémentaire de contrôle d'accès basé sur des rôles (RBAC). Le plug-in SnapCenter VMware prend en charge le RBAC vCenter Server et ONTAP RBAC. https://docs.netapp.com/us-en/sc-plugin-vmware-vsphere/scpivs44_types_of_rbac_for_snapcenter_users.html["En savoir plus"^]

|===


| *Meilleure pratique :* NetApp vous recommande de créer un rôle ONTAP pour les opérations du plug-in SnapCenter pour VMware vSphere et de lui attribuer tous les privilèges requis. 
|===


=== Autorisations ONTAP

Vous devez créer un compte vsadmin avec les autorisations requises pour accéder au système de stockage. link:../install/task_add_a_user_or_group_and_assign_role_and_assets.html["En savoir plus"]



== Autorisations attribuées aux rôles SnapCenter prédéfinis

Lorsque vous ajoutez un utilisateur à un rôle, vous devez attribuer l'autorisation StorageConnection pour activer la communication SVM (Storage Virtual machine) ou affecter un SVM à l'utilisateur pour permettre l'utilisation de la SVM. L'autorisation Storage Connection permet aux utilisateurs de créer des connexions SVM.

Par exemple, un utilisateur avec le rôle administrateur SnapCenter peut créer des connexions SVM et les affecter à un utilisateur avec le rôle Administrateur App Backup and Clone, qui par défaut n'a pas la permission de créer ou de modifier des connexions SVM. Sans connexion SVM, les utilisateurs ne peuvent pas mener à bien les opérations de sauvegarde, de clonage ou de restauration.



=== Rôle d'administrateur SnapCenter

Toutes les autorisations sont activées pour le rôle d'administrateur SnapCenter. Vous ne pouvez pas modifier les autorisations pour ce rôle. Vous pouvez ajouter des utilisateurs et des groupes au rôle ou les supprimer.



=== Rôle d'administrateur de clones et de sauvegarde des applications

Le rôle d'administrateur d'applications et de clones dispose des autorisations nécessaires pour effectuer des actions administratives pour les sauvegardes d'applications et les tâches liées au clonage. Ce rôle ne dispose pas des autorisations nécessaires pour la gestion des hôtes, le provisionnement, la gestion des connexions de stockage ou l'installation à distance.

|===
| Autorisations | Activé | Création | Lecture | Mise à jour | Supprimer 


 a| 
Groupe de ressources
 a| 
Sans objet
 a| 
Oui.
 a| 
Oui.
 a| 
Oui.
 a| 
Oui.



 a| 
Politique
 a| 
Sans objet
 a| 
Oui.
 a| 
Oui.
 a| 
Oui.
 a| 
Oui.



 a| 
Sauvegarde
 a| 
Sans objet
 a| 
Oui.
 a| 
Oui.
 a| 
Oui.
 a| 
Oui.



 a| 
Hôte
 a| 
Sans objet
 a| 
Oui.
 a| 
Oui.
 a| 
Oui.
 a| 
Oui.



 a| 
Connexion de stockage
 a| 
Sans objet
 a| 
Non
 a| 
Oui.
 a| 
Non
 a| 
Non



 a| 
Clonage
 a| 
Sans objet
 a| 
Oui.
 a| 
Oui.
 a| 
Oui.
 a| 
Oui.



 a| 
Provisionnement
 a| 
Sans objet
 a| 
Non
 a| 
Oui.
 a| 
Non
 a| 
Non



 a| 
Tableau de bord
 a| 
Oui.
 a| 
Sans objet
 a| 
Sans objet
 a| 
Sans objet
 a| 
Sans objet



 a| 
Rapports
 a| 
Oui.
 a| 
Sans objet
 a| 
Sans objet
 a| 
Sans objet
 a| 
Sans objet



 a| 
Restaurer
 a| 
Oui.
 a| 
Sans objet
 a| 
Sans objet
 a| 
Sans objet
 a| 
Sans objet



 a| 
Ressource
 a| 
Oui.
 a| 
Oui.
 a| 
Oui.
 a| 
Oui.
 a| 
Oui.



 a| 
Installation/désinstallation du plug-in
 a| 
Non
 a| 
Sans objet
 a| 
 a| 
Sans objet
 a| 
Sans objet



 a| 
Migration
 a| 
Non
 a| 
Sans objet
 a| 
Sans objet
 a| 
Sans objet
 a| 
Sans objet



 a| 
Montage
 a| 
Oui.
 a| 
Oui.
 a| 
Sans objet
 a| 
Sans objet
 a| 
Sans objet



 a| 
Démonter
 a| 
Oui.
 a| 
Oui.
 a| 
Sans objet
 a| 
Sans objet
 a| 
Sans objet



 a| 
Restauration complète du volume
 a| 
Non
 a| 
Non
 a| 
Sans objet
 a| 
Sans objet
 a| 
Sans objet



 a| 
Protection secondaire
 a| 
Non
 a| 
Non
 a| 
Sans objet
 a| 
Sans objet
 a| 
Sans objet



 a| 
Moniteur de tâche
 a| 
Oui.
 a| 
Sans objet
 a| 
Sans objet
 a| 
Sans objet
 a| 
Sans objet

|===


=== Rôle Backup and Clone Viewer

Le rôle de la visionneuse de sauvegarde et de clonage dispose d'une vue en lecture seule de toutes les autorisations. Ce rôle est également doté d'autorisations pour la découverte, le reporting et l'accès au Tableau de bord.

|===
| Autorisations | Activé | Création | Lecture | Mise à jour | Supprimer 


 a| 
Groupe de ressources
 a| 
Sans objet
 a| 
Non
 a| 
Oui.
 a| 
Non
 a| 
Non



 a| 
Politique
 a| 
Sans objet
 a| 
Non
 a| 
Oui.
 a| 
Non
 a| 
Non



 a| 
Sauvegarde
 a| 
Sans objet
 a| 
Non
 a| 
Oui.
 a| 
Non
 a| 
Non



 a| 
Hôte
 a| 
Sans objet
 a| 
Non
 a| 
Oui.
 a| 
Non
 a| 
Non



 a| 
Connexion de stockage
 a| 
Sans objet
 a| 
Non
 a| 
Oui.
 a| 
Non
 a| 
Non



 a| 
Clonage
 a| 
Sans objet
 a| 
Non
 a| 
Oui.
 a| 
Non
 a| 
Non



 a| 
Provisionnement
 a| 
Sans objet
 a| 
Non
 a| 
Oui.
 a| 
Non
 a| 
Non



 a| 
Tableau de bord
 a| 
Oui.
 a| 
Sans objet
 a| 
Sans objet
 a| 
Sans objet
 a| 
Sans objet



 a| 
Rapports
 a| 
Oui.
 a| 
Sans objet
 a| 
Sans objet
 a| 
Sans objet
 a| 
Sans objet



 a| 
Restaurer
 a| 
Non
 a| 
Non
 a| 
Sans objet
 a| 
Sans objet
 a| 
Sans objet



 a| 
Ressource
 a| 
Non
 a| 
Non
 a| 
Oui.
 a| 
Oui.
 a| 
Non



 a| 
Installation/désinstallation du plug-in
 a| 
Non
 a| 
Sans objet
 a| 
Sans objet
 a| 
Sans objet
 a| 
Sans objet



 a| 
Migration
 a| 
Non
 a| 
Sans objet
 a| 
Sans objet
 a| 
Sans objet
 a| 
Sans objet



 a| 
Montage
 a| 
Oui.
 a| 
Sans objet
 a| 
Sans objet
 a| 
Sans objet
 a| 
Sans objet



 a| 
Démonter
 a| 
Oui.
 a| 
Sans objet
 a| 
Sans objet
 a| 
Sans objet
 a| 
Sans objet



 a| 
Restauration complète du volume
 a| 
Non
 a| 
Sans objet
 a| 
Sans objet
 a| 
Sans objet
 a| 
Sans objet



 a| 
Protection secondaire
 a| 
Non
 a| 
Sans objet
 a| 
Sans objet
 a| 
Sans objet
 a| 
Sans objet



 a| 
Moniteur de tâche
 a| 
Oui.
 a| 
Sans objet
 a| 
Sans objet
 a| 
Sans objet
 a| 
Sans objet

|===


=== Rôle d'administrateur de l'infrastructure

Le rôle d'administrateur de l'infrastructure possède des autorisations pour la gestion des hôtes, la gestion du stockage, le provisionnement, les groupes de ressources, les rapports d'installation à distance, Et l'accès au Tableau de bord.

|===
| Autorisations | Activé | Création | Lecture | Mise à jour | Supprimer 


 a| 
Groupe de ressources
 a| 
Sans objet
 a| 
Oui.
 a| 
Oui.
 a| 
Oui.
 a| 
Oui.



 a| 
Politique
 a| 
Sans objet
 a| 
Non
 a| 
Oui.
 a| 
Oui.
 a| 
Oui.



 a| 
Sauvegarde
 a| 
Sans objet
 a| 
Oui.
 a| 
Oui.
 a| 
Oui.
 a| 
Oui.



 a| 
Hôte
 a| 
Sans objet
 a| 
Oui.
 a| 
Oui.
 a| 
Oui.
 a| 
Oui.



 a| 
Connexion de stockage
 a| 
Sans objet
 a| 
Oui.
 a| 
Oui.
 a| 
Oui.
 a| 
Oui.



 a| 
Clonage
 a| 
Sans objet
 a| 
Non
 a| 
Oui.
 a| 
Non
 a| 
Non



 a| 
Provisionnement
 a| 
Sans objet
 a| 
Oui.
 a| 
Oui.
 a| 
Oui.
 a| 
Oui.



 a| 
Tableau de bord
 a| 
Oui.
 a| 
Sans objet
 a| 
Sans objet
 a| 
Sans objet
 a| 
Sans objet



 a| 
Rapports
 a| 
Oui.
 a| 
Sans objet
 a| 
Sans objet
 a| 
Sans objet
 a| 
Sans objet



 a| 
Restaurer
 a| 
Oui.
 a| 
Sans objet
 a| 
Sans objet
 a| 
Sans objet
 a| 
Sans objet



 a| 
Ressource
 a| 
Oui.
 a| 
Oui.
 a| 
Oui.
 a| 
Oui.
 a| 
Oui.



 a| 
Installation/désinstallation du plug-in
 a| 
Oui.
 a| 
Sans objet
 a| 
Sans objet
 a| 
Sans objet
 a| 
Sans objet



 a| 
Migration
 a| 
Non
 a| 
Sans objet
 a| 
Sans objet
 a| 
Sans objet
 a| 
Sans objet



 a| 
Montage
 a| 
Non
 a| 
Sans objet
 a| 
Sans objet
 a| 
Sans objet
 a| 
Sans objet



 a| 
Démonter
 a| 
Non
 a| 
Sans objet
 a| 
Sans objet
 a| 
Sans objet
 a| 
Sans objet



 a| 
Restauration complète du volume
 a| 
Non
 a| 
Non
 a| 
Sans objet
 a| 
Sans objet
 a| 
Sans objet



 a| 
Protection secondaire
 a| 
Non
 a| 
Non
 a| 
Sans objet
 a| 
Sans objet
 a| 
Sans objet



 a| 
Moniteur de tâche
 a| 
Oui.
 a| 
Sans objet
 a| 
Sans objet
 a| 
Sans objet
 a| 
Sans objet

|===