---
permalink: 'release-notes/what"s-new-in-snapcenter62.html' 
sidebar: sidebar 
keywords: what is new, features, enhancements, 6.2 
summary: La version 6.2 du logiciel SnapCenter inclut plusieurs nouvelles fonctionnalités et améliorations. 
---
= Quoi de neuf dans le SnapCenter software 6.2
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La version 6.2 du logiciel SnapCenter inclut des correctifs de bogues connus et des mises à jour des versions qualifiées pour le SnapCenter Server et les plug-ins. Elle comprend également la fonctionnalité étendue suivante. Consultez le link:https://library.netapp.com/ecm/ecm_download_file/ECMLP3359467["SnapCenter 6.2.2 Notes de version"^] pour plus de détails.

|===
| Mise à jour | Description 


| link:../get-started/reference_supported_storage_systems_and_applications.html["Prise en charge des systèmes ASA r2"]  a| 
SnapCenter 6.2 (serveur et plug-ins) ainsi que ONTAP 9.17.1 prennent en charge la protection primaire et secondaire des applications exécutées sur des systèmes physiques (Linux et Windows) et des systèmes de fichiers de machines virtuelles (VMFS) à l'aide de groupes de cohérence hiérarchiques.

Après la mise à niveau vers SnapCenter 6.2 et ONTAP 9.17.1, SnapCenter transforme les groupes de cohérence plats en groupes de cohérence hiérarchiques lors de la première sauvegarde planifiée.

|===


[[bluexp-is-now-netapp-console]]
== BlueXP est désormais NetApp Console

La console NetApp , construite sur la base BlueXP améliorée et restructurée, fournit une gestion centralisée du stockage NetApp et des services de données NetApp dans les environnements sur site et cloud à l'échelle de l'entreprise, offrant des informations en temps réel, des flux de travail plus rapides et une administration simplifiée, hautement sécurisée et conforme.

Pour plus de détails sur ce qui a changé, consultez lelink:https://docs.netapp.com/us-en/bluexp-relnotes/index.html["Notes de version de la console NetApp"^] .
