---
permalink: 'release-notes/what"s-new-in-snapcenter601.html' 
sidebar: sidebar 
keywords: what is new, features, enhancements, 6.0.1 
summary: La version 6.0.1 du logiciel SnapCenter comprend plusieurs nouvelles fonctionnalités et améliorations. 
---
= Nouveautés du logiciel SnapCenter 6.0.1
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La version 6.0.1 du logiciel SnapCenter comprend plusieurs nouvelles fonctionnalités et améliorations.

|===
| Mise à jour | Description 


| link:https://docs.netapp.com/us-en/snapcenter/protect-azure/protect-applications-azure-netapp-files.html["Prise en charge des sauvegardes Azure NetApp Files"]  a| 
Vous pouvez désormais utiliser SnapCenter pour sauvegarder et cloner les applications résidant sur Azure NetApp Files vers Azure Blob Storage (magasin d'objets).



| link:https://docs.netapp.com/us-en/snapcenter/install/concept_configure_snapcenter_servers_for_high_availabiity_using_f5.html["Prise en charge de la haute disponibilité de SnapCenter sous Linux"]  a| 
La prise en charge de la configuration haute disponibilité pour SnapCenter est désormais étendue aux systèmes Linux. Vous pouvez utiliser les équilibreurs de charge standard pour cette configuration :

* Équilibreur de charge F5
* Microsoft Network Load Balancing (NLB)
* Services Web Amazon (AWS)
* Équilibrage de charge élastique (ELB)
* Équilibreur de charge Azure




| link:https://docs.netapp.com/us-en/snapcenter/admin/concept_monitor_jobs_schedules_events_and_logs.html#manage-scheduled-backup-jobs["Possibilité de gérer les tâches de sauvegarde planifiées"]  a| 
Vous pouvez maintenant définir un seuil pour vos tâches planifiées afin de contrôler le nombre de sauvegardes que vous souhaitez exécuter à un moment donné en fonction de la configuration matérielle de votre système.



| link:https://docs.netapp.com/us-en/snapcenter/admin/concept_monitor_jobs_schedules_events_and_logs.html#manage-stale-jobs["Possibilité de gérer des tâches obsolètes"]  a| 
Vous pouvez maintenant définir un planning prédéfini pour nettoyer les travaux obsolètes qui sont bloqués pendant plus de 72 heures.



| Fonctionnalités de protection des données incluses pour IBM DB2, Oracle application et le plug-in de stockage sous AIX  a| 
Prend en charge la protection des données d'IBM DB2, d'Oracle application et de Storage Plug-in fonctionnant sous AIX.

|===