---
permalink: protect-mysql/back-up-databases-using-powershell-cmdlets-mysql.html 
sidebar: sidebar 
keywords: SnapCenter Plug-in for MySQL 
summary: 'La sauvegarde d"une base de données inclut l"établissement d"une connexion avec le serveur SnapCenter, l"ajout de ressources, l"ajout d"une stratégie, la création d"un groupe de ressources de sauvegarde et la sauvegarde.' 
---
= Sauvegarder des bases de données à l'aide des applets de commande PowerShell
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La sauvegarde d'une base de données inclut l'établissement d'une connexion avec le serveur SnapCenter, l'ajout de ressources, l'ajout d'une stratégie, la création d'un groupe de ressources de sauvegarde et la sauvegarde.

.Avant de commencer
* Vous devez avoir préparé l'environnement PowerShell pour exécuter les applets de commande PowerShell.
* Vous devez avoir ajouté la connexion au système de stockage et créé une autorisation d'accès.


.Étapes
. Lancez une session de connexion avec le serveur SnapCenter pour un utilisateur spécifié à l'aide de l'applet de commande Open-SmConnection.
+
[listing]
----
Open-SmConnection  -SMSbaseurl  https:\\snapctr.demo.netapp.com:8146\
----
+
L'invite du nom d'utilisateur et du mot de passe s'affiche.

. Ajoutez des ressources manuelles à l'aide de l'applet de commande Add-SmResources.
+
Cet exemple montre comment ajouter une instance MySQL :

+
[listing]
----
PS C:\> Add-SmResource -HostName 10.32.212.13 -PluginCode MySQL -ResourceType Instance -ResourceName mysqlinst1 -StorageFootPrint (@{"VolumeName"="winmysql01_data01";"LUNName"="winmysql01_data01";"StorageSystem"="scsnfssvm"}) -MountPoints "D:\"
----
. Créez une stratégie de sauvegarde à l'aide de l'applet de commande Add-SmPolicy.
. Protégez la ressource ou ajoutez un nouveau groupe de ressources à SnapCenter à l'aide de l'applet de commande Add-SmResourceGroup.
. Lancez une nouvelle tâche de sauvegarde à l'aide de la cmdlet New-SmBackup.
+
Cet exemple montre comment sauvegarder un groupe de ressources :

+
[listing]
----
C:\PS> New-SmBackup -Resources @{"Host"="scs000211748.gdl.englab.netapp.com";"Uid"="mysqld_3306";"PluginName"="MySQL"} -Policy "MySQL_snapshotbased"
----
+
Cet exemple sauvegarde une ressource protégée :

+
[listing]
----
C:\PS> New-SMBackup -Resources @{"Host"="10.232.204.42";"Uid"="MDC\SID";"PluginName"="hana"} -Policy mysql_policy2
----
. Surveillez l'état du travail (en cours d'exécution, terminé ou en échec) à l'aide de l'applet de commande Get-smJobSummaryReport.
+
[listing]
----
PS C:\> Get-smJobSummaryReport -JobID 123
----
. Surveillez les détails de la tâche de sauvegarde comme ID de sauvegarde, nom de sauvegarde pour effectuer une opération de restauration ou de clonage à l'aide de l'applet de commande Get-SmBackupReport.
+
[listing]
----
PS C:\> Get-SmBackupReport -JobId 351
Output:
BackedUpObjects           : {DB1}
FailedObjects             : {}
IsScheduled               : False
HasMetadata               : False
SmBackupId                : 269
SmJobId                   : 2361
StartDateTime             : 10/4/2016 11:20:45 PM
EndDateTime               : 10/4/2016 11:21:32 PM
Duration                  : 00:00:46.2536470
CreatedDateTime           : 10/4/2016 11:21:09 PM
Status                    : Completed
ProtectionGroupName       : Verify_ASUP_Message_windows
SmProtectionGroupId       : 211
PolicyName                : test2
SmPolicyId                : 20
BackupName                : Verify_ASUP_Message_windows_scc54_10-04-2016_23.20.46.2758
VerificationStatus        : NotVerified
VerificationStatuses      :
SmJobError                :
BackupType                : SCC_BACKUP
CatalogingStatus          : NotApplicable
CatalogingStatuses        :
ReportDataCreatedDateTime :
----


Les informations relatives aux paramètres pouvant être utilisés avec la cmdlet et leurs descriptions peuvent être obtenues en exécutant _get-Help nom_commande_. Vous pouvez également vous reporter à la https://docs.netapp.com/us-en/snapcenter-cmdlets/index.html["Guide de référence de l'applet de commande du logiciel SnapCenter"^].
