---
permalink: protect-mysql/create-a-storage-system-connection-and-a-run-as-account-using-powershell-cmdlets-for-mysql.html 
sidebar: sidebar 
keywords: SnapCenter Plug-in for MySQL 
summary: 'Vous devez créer une connexion de machine virtuelle de stockage (SVM) et un identifiant avant d"utiliser les applets de commande PowerShell pour sauvegarder, restaurer ou cloner les bases de données MySQL.' 
---
= Créez une connexion au système de stockage et des informations d'identification à l'aide des applets de commande PowerShell pour MySQL
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous devez créer une connexion de machine virtuelle de stockage (SVM) et un identifiant avant d'utiliser les applets de commande PowerShell pour sauvegarder, restaurer ou cloner les bases de données MySQL.

.Avant de commencer
* Vous devez avoir préparé l'environnement PowerShell pour exécuter les applets de commande PowerShell.
* Pour créer des connexions de stockage, vous devez disposer des autorisations requises dans le rôle d'administrateur d'infrastructure.
* Vous devez vous assurer que les installations du plug-in ne sont pas en cours.
+
Les installations de plug-ins hôtes ne doivent pas être en cours d'ajout d'une connexion au système de stockage, car le cache hôte n'est pas nécessairement mis à jour et l'état des bases de données peut être affiché dans l'interface utilisateur graphique de SnapCenter sous la forme « non disponible pour la sauvegarde » ou « non sur le stockage NetApp ».

* Les noms des systèmes de stockage doivent être uniques.
+
SnapCenter ne prend pas en charge plusieurs systèmes de stockage portant le même nom sur des clusters différents. Chaque système de stockage pris en charge par SnapCenter doit disposer d'un nom unique et d'une adresse IP de LIF de données unique.



.Étapes
. Lancez une session de connexion PowerShell Core à l'aide de l'applet de commande Open-SmConnection.
+
[listing]
----
PS C:\> Open-SmConnection
----
. Créez une nouvelle connexion au système de stockage à l'aide de l'applet de commande Add-SmStorageConnection.
+
[listing]
----
PS C:\> Add-SmStorageConnection -Storage test_vs1 -Protocol Https
-Timeout 60
----
. Créez une nouvelle information d'identification à l'aide de l'applet de commande Add-SmCredential.
+
Cet exemple montre comment créer un nouvel identifiant nommé FinancieAdmin avec les informations d'identification Windows :

+
[listing]
----
PS C:> Add-SmCredential -Name FinanceAdmin -AuthMode Windows
-Credential sddev\administrator
----
. Ajoutez l'hôte de communication MySQL au serveur SnapCenter.
+
[listing]
----
PS C:> Add-SmHost -HostName 10.232.204.61 -OSType Windows -RunAsName FinanceAdmin -PluginCode mysql
----
. Installez le paquet et le plug-in SnapCenter pour MySQL sur l'hôte.
+
Pour Linux :

+
[listing]
----
PS C:> Install-SmHostPackage -HostNames 10.232.204.61 -ApplicationCode mysql
----
+
Pour Windows :

+
[listing]
----
Install-SmHostPackage -HostNames 10.232.204.61 -ApplicationCode mysql -FilesystemCode scw -RunAsName FinanceAdmin
----
. Définissez le chemin d'accès à SQLLIB.
+
Sous Windows, le plug-in MySQL utilise le chemin par défaut du dossier SQLLIB : « C:\Program Files\IBM\SQLLIB\BIN ».

+
Si vous souhaitez remplacer le chemin par défaut, utilisez la commande suivante.

+
[listing]
----
PS C:> Set-SmConfigSettings -Plugin -HostName 10.232.204.61 -PluginCode
MySQL -configSettings @{“MySQL_SQLLIB_CMD” = “<custom_path>\IBM\SQLLIB\BIN”}

----


Les informations relatives aux paramètres pouvant être utilisés avec la cmdlet et leurs descriptions peuvent être obtenues en exécutant _get-Help nom_commande_. Vous pouvez également vous reporter à la https://docs.netapp.com/us-en/snapcenter-cmdlets/index.html["Guide de référence de l'applet de commande du logiciel SnapCenter"^].
