---
permalink: protect-mysql/prerequisites-to-adding-hosts-and-installing-snapcenter-plug-in-for-mysql.html 
sidebar: sidebar 
keywords: credentials 
summary: 'Avant d"ajouter un hôte et d"installer les modules d"extension, vous devez remplir toutes les conditions requises. Le plug-in SnapCenter pour MySQL est disponible dans les environnements Windows et Linux.' 
---
= Conditions préalables pour ajouter des hôtes et installer le plug-in SnapCenter pour MySQL
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Avant d'ajouter un hôte et d'installer les modules d'extension, vous devez remplir toutes les conditions requises. Le plug-in SnapCenter pour MySQL est disponible dans les environnements Windows et Linux.

* Vous devez avoir installé Java 11 sur votre hôte.
+

NOTE: IBM Java n'est pas pris en charge.

* Pour Windows, le service de création de plug-in doit être exécuté à l'aide de l'utilisateur Windows « LocalSystem », qui est le comportement par défaut lorsque Plug-in pour MySQL est installé en tant qu'administrateur de domaine.
* Lors de l'installation d'un plug-in sur un hôte Windows, si vous spécifiez un identifiant qui n'est pas intégré ou si l'utilisateur appartient à un utilisateur de groupe de travail local, vous devez désactiver l'UAC sur l'hôte. Le plug-in SnapCenter pour Microsoft Windows sera déployé par défaut avec le plug-in MySQL sur les hôtes Windows.
* Le serveur SnapCenter doit avoir accès au port 8145 ou personnalisé du plug-in pour l'hôte MySQL.
* Pour MySQL 5.7, binlog doit être spécifié dans le fichier mysql config (my.cnf ou mysql-Server.cnf).




== Hôtes Windows

* Vous devez disposer d'un utilisateur de domaine disposant de privilèges d'administrateur local avec des autorisations de connexion locales sur l'hôte distant.
* Lors de l'installation du plug-in pour MySQL sur un hôte Windows, le plug-in SnapCenter pour Microsoft Windows est installé automatiquement.
* Vous devez avoir activé la connexion SSH par mot de passe pour l'utilisateur root ou non-root.
* Vous devez avoir installé Java 11 sur votre hôte Windows.
+
http://www.java.com/en/download/manual.jsp["Téléchargements Java pour tous les systèmes d'exploitation"]

+
https://imt.netapp.com/matrix/imt.jsp?components=121071;&solution=1259&isHWU&src=IMT["Matrice d'interopérabilité NetApp"]





== Hôtes Linux

* Vous devez avoir activé la connexion SSH par mot de passe pour l'utilisateur root ou non-root.
* Vous devez avoir installé Java 11 sur votre hôte Linux.
+
http://www.java.com/en/download/manual.jsp["Téléchargements Java pour tous les systèmes d'exploitation"]

+
https://imt.netapp.com/matrix/imt.jsp?components=121071;&solution=1259&isHWU&src=IMT["Matrice d'interopérabilité NetApp"]

* Pour les bases de données MySQL qui s'exécutent sur un hôte Linux, lors de l'installation de Plug-in pour MySQL, SnapCenter Plug-in pour UNIX est installé automatiquement.
* Vous devez avoir *bash* comme shell par défaut pour l'installation du plug-in.




== Commandes supplémentaires

Pour exécuter une commande supplémentaire sur le plug-in SnapCenter pour MySQL, vous devez l'inclure dans `allowed_commands.config` le fichier.

`allowed_commands.config` Le fichier se trouve dans le sous-répertoire "etc" du répertoire du plug-in SnapCenter pour MySQL.

.Hôtes Windows
Par défaut : `C:\Program Files\NetApp\SnapCenter\Snapcenter Plug-in Creator\etc\allowed_commands.config`

Chemin personnalisé : `<Custom_Directory>\NetApp\SnapCenter\Snapcenter Plug-in Creator\etc\allowed_commands.config`

.Hôtes Linux
Valeur par défaut : `/opt/NetApp/snapcenter/scc/etc/allowed_commands.config`

Chemin personnalisé : `<Custom_Directory>allowed_commands.config`

Pour autoriser des commandes supplémentaires sur l'hôte du plug-in, ouvrez `allowed_commands.config` fichier dans un éditeur. Entrez chaque commande sur une ligne distincte. Il n'est pas sensible à la casse.
Par exemple :

commande : mount

commande : umount

Assurez-vous de spécifier le chemin d'accès complet. Placez le chemin d'accès entre guillemets (") s'il contient des espaces.
Par exemple :

Commande : « C:\Program Files\NetApp\SnapCreator commands\sdcli.exe »

commande : myscript.bat

Si le `allowed_commands.config` le fichier n'est pas présent, les commandes ou l'exécution de script seront bloquées et le flux de travail échouera avec l'erreur suivante :

"[/mnt/mount -a] exécution non autorisée. Autoriser en ajoutant la commande dans le fichier %s sur l'hôte du plug-in. »

Si la commande ou le script n'est pas présent dans `allowed_commands.config`, l'exécution de la commande ou du script sera bloquée et le flux de travail échouera avec l'erreur suivante :

"[/mnt/mount -a] exécution non autorisée. Autoriser en ajoutant la commande dans le fichier %s sur l'hôte du plug-in. »


NOTE: Vous ne devez pas utiliser de caractère générique (*) pour autoriser toutes les commandes.



== Configurez les privilèges sudo pour les utilisateurs non-root pour l'hôte Linux

Les versions SnapCenter 2.0 et ultérieures permettent à un utilisateur non-root d'installer le package de plug-ins SnapCenter pour Linux et de démarrer le processus de plug-in. Les processus de plug-in s'exécutent en tant qu'utilisateur non racine efficace. Vous devez configurer les privilèges sudo pour que l'utilisateur non-root puisse accéder à plusieurs chemins.

*Ce dont vous aurez besoin*

* Sudo version 1.8.7 ou ultérieure.
* Pour l'utilisateur non root, assurez-vous que le nom de l'utilisateur non root et le groupe de l'utilisateur doivent être identiques.
* Modifiez le fichier _/etc/ssh/sshd_config_ pour configurer les algorithmes de code d'authentification de message : Mac hmac-sha2-256 et MAC hmac-sha2-512.
+
Redémarrez le service sshd après la mise à jour du fichier de configuration.

+
Exemple :

+
[listing]
----
#Port 22
#AddressFamily any
#ListenAddress 0.0.0.0
#ListenAddress ::
#Legacy changes
#KexAlgorithms diffie-hellman-group1-sha1
#Ciphers aes128-cbc
#The default requires explicit activation of protocol
Protocol 2
HostKey/etc/ssh/ssh_host_rsa_key
MACs hmac-sha2-256
----


*À propos de cette tâche*

Vous devez configurer les privilèges sudo pour que l'utilisateur non-root puisse accéder aux chemins suivants :

* /Home/_LINUX_USER_/.sc_netapp/snapcenter_linux_host_plugin.bin
* /Custom_location/NetApp/snapcenter/spl/installation/plugins/désinstaller
* /Custom_location/NetApp/snapcenter/spl/bin/spl


*Étapes*

. Connectez-vous à l'hôte Linux sur lequel vous souhaitez installer SnapCenter Plug-ins Package pour Linux.
. Ajoutez les lignes suivantes au fichier /etc/sudoers à l'aide de l'utilitaire visudo Linux.
+
[listing, subs="+quotes"]
----
Cmnd_Alias HPPLCMD = sha224:checksum_value== /home/_LINUX_USER_/.sc_netapp/snapcenter_linux_host_plugin.bin, /opt/NetApp/snapcenter/spl/installation/plugins/uninstall, /opt/NetApp/snapcenter/spl/bin/spl, /opt/NetApp/snapcenter/scc/bin/scc
Cmnd_Alias PRECHECKCMD = sha224:checksum_value== /home/_LINUX_USER_/.sc_netapp/Linux_Prechecks.sh
Cmnd_Alias CONFIGCHECKCMD = sha224:checksum_value== /opt/NetApp/snapcenter/spl/plugins/scu/scucore/configurationcheck/Config_Check.sh
Cmnd_Alias SCCMD = sha224:checksum_value== /opt/NetApp/snapcenter/spl/bin/sc_command_executor
Cmnd_Alias SCCCMDEXECUTOR =checksum_value== /opt/NetApp/snapcenter/scc/bin/sccCommandExecutor
_LINUX_USER_ ALL=(ALL) NOPASSWD:SETENV: HPPLCMD, PRECHECKCMD, CONFIGCHECKCMD, SCCCMDEXECUTOR, SCCMD
Defaults: _LINUX_USER_ !visiblepw
Defaults: _LINUX_USER_ !requiretty
----
+

NOTE: Si vous avez une configuration RAC, avec les autres commandes autorisées, vous devez ajouter ce qui suit au fichier /etc/sudoers : '/<crs_home>/bin/olsnodes'



Vous pouvez obtenir la valeur de _crs_Home_ à partir du fichier _/etc/oracle/olr.loc_.

_LINUX_USER_ est le nom de l'utilisateur non-root que vous avez créé.

Vous pouvez obtenir la valeur _checksum_value_ à partir du fichier *sc_unix_plugins_checksum.txt*, situé à l'adresse suivante :

* _C:\ProgramData\NetApp\SnapCenter\Package Repository\sc_unix_plugins_checksum.txt _ si le serveur SnapCenter est installé sur l'hôte Windows.
* _/opt/NetApp/snapcenter/SnapManagerWeb/Repository/sc_unix_plugins_checksum.txt _ si le serveur SnapCenter est installé sur un hôte Linux.



IMPORTANT: Cet exemple ne doit être utilisé que comme référence pour la création de vos propres données.
