---
permalink: protect-mysql/types-of-restore-performed-for-auto-discovered-mysql.html 
sidebar: sidebar 
keywords: SnapCenter Plug-in for mysql 
summary: 'SnapCenter prend en charge les types de restauration basés sur des volumes SnapRestore \(VBSR\), Single File SnapRestore et Connect-and-copy pour les bases de données MySQL découvertes automatiquement.' 
---
= Types de restauration pour les bases de données MySQL détectées automatiquement dans SnapCenter
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Le plug-in SnapCenter pour MySQL prend en charge les types de restauration Single File SnapRestore et Connect-and-copy pour les bases de données MySQL découvertes automatiquement.



[[single-file-snaprestore-is-performed-in-nfs-environments-for-the-following-scenarios]]
== Single File SnapRestore s'effectue dans des environnements NFS pour les scénarios suivants :

* Si seule l'option *ressource complète* est sélectionnée
* Lorsque la sauvegarde sélectionnée provient d'un emplacement secondaire SnapMirror ou SnapVault et que l'option *Complete Resource* est sélectionnée




[[single-file-snaprestore-is-performed-in-san-environments-for-the-following-scenarios]]
== Single File SnapRestore s'effectue dans des environnements SAN pour les scénarios suivants :

* Si seule l'option *ressource complète* est sélectionnée
* Lorsque la sauvegarde est sélectionnée depuis un emplacement secondaire SnapMirror ou SnapVault et l'option *Complete Resource* est sélectionnée

